import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const simulator=fs.readFileSync('components/PublicModelSimulator.tsx','utf8');const conversion=fs.readFileSync('components/PublicConversionForm.tsx','utf8');const benchmark=fs.readFileSync('components/Benchmark.tsx','utf8');const migration=fs.readFileSync('supabase/migrations/20260914_v9_public_flow_benchmark.sql','utf8');const authCss=fs.readFileSync('app/globals.css','utf8');
test('V9 removes dead simulation state and corporate-login consultant redirect',()=>{assert.ok(!simulator.includes('Simulação em configuração'));assert.ok(!simulator.includes('href="/acesso"'));assert.ok(simulator.includes('PublicConversionForm'));assert.ok(simulator.includes('SIMULAÇÃO ASSISTIDA'))});
test('V9 public conversion preserves separate commercial and customer email status',()=>{assert.ok(conversion.includes('Comercial:'));assert.ok(conversion.includes('Cliente:'));assert.ok(conversion.includes('/api/public-interest'))});
test('V9 benchmark contains executive, compare, radar, learning and LocNews integration',()=>{for(const text of ['benchmarkExecutive','COMPARADOR LADO A LADO','Radar estratégico • 5 eixos','O QUE PODEMOS APRENDER','/api/news'])assert.ok(benchmark.includes(text))});
test('V9 migration creates benchmark entities, snapshots, radar and generic public capture',()=>{for(const text of ['capture_public_commercial_interest','commercial_benchmark_entities','commercial_benchmark_snapshots','commercial_benchmark_radar','O Boticário','Cacau Show','Kopenhagen','Chiquinho Sorvetes'])assert.ok(migration.includes(text))});
test('V9 fixes corporate access title contrast and compact sidebar labels',()=>{assert.ok(authCss.includes('.authCard h1{color:#fff!important}'));assert.ok(authCss.includes('.sidebarItemText{display:block!important'))});
test('V9 resend supports assisted leads without requiring a simulation',()=>{const commercial=fs.readFileSync('app/api/admin/notifications/resend/route.ts','utf8');const customer=fs.readFileSync('app/api/admin/notifications/resend-customer/route.ts','utf8');assert.ok(commercial.includes('sendCommercialInterestEmail'));assert.ok(customer.includes('sendCustomerInterestEmail'));assert.ok(!commercial.includes('simulation_not_found'));assert.ok(!customer.includes('simulation_not_found'));assert.ok(commercial.includes('simulation_id:sim?.id||null'))});
test('V9 benchmark reference snapshot keeps period and supplied RA values',()=>{for(const text of ["2026-03-01","2026-08-31","7.2","76.6","6.6","66.2","7.5","74.7","4.0","29.6","Reclame Aqui"])assert.ok(migration.includes(text))});
