import { NextRequest } from "next/server";
import { Document, Image, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import { deterministicNarrative } from "@/lib/proposal-ai";
import fs from "node:fs";
import path from "node:path";

export const runtime="nodejs";
export const dynamic="force-dynamic";
const PAGE_SIZE:[number,number]=[960,540];
const s=StyleSheet.create({page:{position:"relative",fontFamily:"Helvetica",color:"#fff",backgroundColor:"#03133a"},bg:{position:"absolute",left:0,top:0,width:"100%",height:"100%"},panel:{position:"absolute",left:48,top:118,width:470,padding:24,borderRadius:14,backgroundColor:"rgba(3,18,55,0.84)",border:"1 solid rgba(112,238,72,0.35)"},panelWide:{position:"absolute",left:48,top:90,width:570,padding:22,borderRadius:14,backgroundColor:"rgba(3,18,55,0.86)",border:"1 solid rgba(112,238,72,0.30)"},kicker:{fontSize:8,letterSpacing:2,color:"#78ed48",marginBottom:8,textTransform:"uppercase"},title:{fontSize:24,fontWeight:700,lineHeight:1.08,marginBottom:10},subtitle:{fontSize:10.5,lineHeight:1.4,color:"#d8e5ff",marginBottom:16},heroValue:{fontSize:30,fontWeight:700,color:"#8cf25a",marginTop:2,marginBottom:12},grid:{flexDirection:"row",flexWrap:"wrap",gap:8},card:{width:"48%",padding:10,borderRadius:8,backgroundColor:"rgba(9,42,91,0.90)",border:"1 solid rgba(255,255,255,0.10)"},label:{fontSize:6.5,letterSpacing:.8,color:"#9eb3d9",textTransform:"uppercase",marginBottom:4},value:{fontSize:11,fontWeight:700,lineHeight:1.15},note:{fontSize:7.5,lineHeight:1.4,color:"#b9c8e0",marginTop:12},consultant:{position:"absolute",right:48,bottom:42,width:330,padding:18,borderRadius:12,backgroundColor:"rgba(4,22,61,0.88)",border:"1 solid rgba(126,239,74,0.45)"},consultantName:{fontSize:18,fontWeight:700,marginTop:5,marginBottom:4},consultantLine:{fontSize:9,color:"#dce6f7",marginTop:3},pageNo:{position:"absolute",right:26,bottom:18,fontSize:7,color:"rgba(255,255,255,0.65)"}});
const money=(n:any,currency="BRL")=>new Intl.NumberFormat("pt-BR",{style:"currency",currency}).format(Number(n)||0);
const text=(v:any,fallback="—")=>v===undefined||v===null||v===""?fallback:String(v);
const imageCache=new Map<string,string>();
function bg(name:string){if(imageCache.has(name))return imageCache.get(name)!;const file=fs.readFileSync(path.join(process.cwd(),"public","proposal-v13",name));const uri=`data:image/png;base64,${file.toString("base64")}`;imageCache.set(name,uri);return uri;}
function Cards({items}:{items:Array<[string,any]>}){return <View style={s.grid}>{items.map(([label,value],i)=><View key={i} style={s.card}><Text style={s.label}>{label}</Text><Text style={s.value}>{text(value)}</Text></View>)}</View>}
function DataPage({image,page,kicker,title,subtitle,hero,items,note}:{image:string;page:number;kicker:string;title:string;subtitle:string;hero?:string;items:Array<[string,any]>;note?:string}){return <Page size={PAGE_SIZE} style={s.page}><Image src={bg(image)} style={s.bg}/><View style={s.panelWide}><Text style={s.kicker}>{kicker}</Text><Text style={s.title}>{title}</Text><Text style={s.subtitle}>{subtitle}</Text>{hero&&<Text style={s.heroValue}>{hero}</Text>}<Cards items={items}/>{note&&<Text style={s.note}>{note}</Text>}</View><Text style={s.pageNo}>{String(page).padStart(2,"0")}</Text></Page>}
function ProposalPdf({body}:{body:any}){
 const client=body.client||{};const sim=body.simulation||{};const proposal=body.proposal||{};const d=sim.details||{};const narrative=proposal.aiNarrative||deterministicNarrative(client,sim);
 const gain=Number(sim.monthly)||0;const capital=Number(sim.capital)||0;const annual=Number(sim.annual)||gain*12;const dre=d.dreEvolution&&typeof d.dreEvolution==="object"?d.dreEvolution:null;const showDre=Boolean(d.dreIncludeInProposal&&dre);
 const validUntil=(()=>{try{const base=proposal.date?new Date(`${proposal.date}T12:00:00`):new Date();base.setDate(base.getDate()+Number(proposal.validityDays||7));return base.toLocaleDateString("pt-BR")}catch{return `${proposal.validityDays||7} dias`;}})();
 return <Document title={`Proposta Locagora - ${text(client.name,"Cliente")}`} author="Locagora">
  <Page size={PAGE_SIZE} style={s.page}><Image src={bg("cover.png")} style={s.bg}/><View style={s.panel}><Text style={s.kicker}>PROPOSTA COMERCIAL</Text><Text style={s.title}>Preparado para {text(client.name,"Cliente Locagora")}</Text><Text style={s.subtitle}>{text(sim.name,"Solução Locagora")} • cenário comercial selecionado</Text><Text style={s.label}>GANHO MENSAL PROJETADO</Text><Text style={s.heroValue}>{money(gain)}</Text><Cards items={[["Investimento",money(capital)],["Validade",validUntil],["Objetivo",client.goal],["Prioridade",client.priority]]}/></View></Page>
  <DataPage image="page-1.png" page={1} kicker="01 • OPORTUNIDADE" title={narrative.opportunityTitle||"Uma oportunidade alinhada ao perfil."} subtitle={narrative.opportunityText||"Cenário construído a partir do perfil informado e das premissas selecionadas."} hero={money(gain)} items={[["Renda mensal",money(gain)],["Renda anual",money(annual)],["Capital",money(capital)],["Solução",sim.name]]}/>
  <DataPage image="page-2.png" page={2} kicker="02 • ESTRUTURA DA OPERAÇÃO" title="Uma configuração objetiva e mensurável." subtitle={narrative.operationSummary||"Estrutura gerada pelo simulador comercial sem alterar as premissas confirmadas."} items={[["Plano",d.plan],["Quantidade",d.qty],["Ciclo",d.cycle],["Modelo",d.model||sim.name]]}/>
  <DataPage image="page-3.png" page={3} kicker="03 • ATIVOS E COMPOSIÇÃO" title="O que sustenta o cenário financeiro." subtitle="Composição de ativos e valores vinculados ao cenário selecionado." items={[["Ativos",money(d.assets)],["Valor unitário",money(d.unitValue)],["Quantidade",d.qty],["Modelo",d.model||sim.name]]}/>
  <DataPage image="page-4.png" page={4} kicker="04 • PROJEÇÃO FINANCEIRA" title="Primeiro o ganho. Depois, o investimento." subtitle={narrative.financialNarrative||"Leitura financeira do cenário comercial selecionado."} hero={money(gain)} items={[["Investimento",money(capital)],["ROI anual simples",d.roiAnnual?`${Number(d.roiAnnual).toFixed(1)}%`:"—"],["36 meses - renda",money(gain*36)],["Payback simples",d.paybackMonths?`${Number(d.paybackMonths).toFixed(1)} meses`:"—"]]} note="Projeções comerciais não constituem garantia de rentabilidade. Operação, contrato, tributos, liquidez e condições aplicáveis devem ser considerados."/>
  {showDre?<DataPage image="page-5.png" page={5} kicker="05 • DRE E EVOLUÇÃO DE ATIVOS" title="DRE opcional com evolução da frota." subtitle={`${text(dre.modeLabel,"Cenário selecionado")} • ${Number(dre.reinvestPct)||0}% do resultado destinado à reaplicação.`} items={[["Frota inicial",`${Number(dre.initialAssets)||0} motos`],["Frota final",`${Number(dre.finalAssets)||0} motos`],["Novos ativos",`+${Number(dre.addedAssets)||0}`],["Resultado operacional",money(dre.totalOperatingResult)],["Reaplicado em ativos",money(dre.totalReinvested)],["Disponível ao cliente",money(dre.totalAvailableToClient)],["Custo por novo ativo",money(dre.unitAssetCost)],["Saldo reinvestimento",money(dre.endingPool)]]} note="Cenário comercial e operacional ilustrativo. A estratégia de reaplicação não constitui recomendação financeira individual nem garantia de resultado."/>:<DataPage image="page-5.png" page={5} kicker="05 • ESCALA E POTENCIAL" title="Uma solução preparada para evoluir." subtitle={narrative.scaleNarrative||"O potencial de evolução depende das regras da solução, da capacidade operacional e das condições comerciais aprovadas."} items={[["Renda mensal",money(gain)],["Referência anual",money(annual)],["Estrutura",d.qty?`${d.qty} unidades/ativos`:"—"],["Horizonte",d.horizon||d.contractYears?`${d.horizon||d.contractYears} anos`:"—"]]}/>} 
  <DataPage image="page-6.png" page={6} kicker="06 • RESUMO EXECUTIVO" title="Os números essenciais em uma página." subtitle={narrative.executiveSummary||"Síntese do cenário para apoiar a decisão comercial e a formalização."} items={[["Cliente",client.name],["Produto",sim.name],["Investimento",money(capital)],["Ganho mensal",money(gain)],["Ganho anual",money(annual)],["ROI anual simples",d.roiAnnual?`${Number(d.roiAnnual).toFixed(1)}%`:"—"]]}/>
  <DataPage image="page-7.png" page={7} kicker="07 • PRÓXIMOS PASSOS" title="Pronto para o próximo passo." subtitle={narrative.closingText||"Validar condição comercial, revisar documentação definitiva e confirmar a implantação conforme o produto selecionado."} items={[["1","Validar condição comercial"],["2","Formalizar documentos"],["3","Confirmar implantação"],["4","Iniciar operação"]]}/>
  <Page size={PAGE_SIZE} style={s.page}><Image src={bg("page-8.png")} style={s.bg}/><View style={s.consultant}><Text style={s.kicker}>CONSULTOR RESPONSÁVEL</Text><Text style={s.consultantName}>{text(proposal.consultant,"Consultor Locagora")}</Text><Text style={s.consultantLine}>{text(proposal.consultantPhone,"Contato a confirmar")}</Text><Text style={s.consultantLine}>Cliente: {text(client.name)}</Text><Text style={s.consultantLine}>Produto: {text(sim.name)}</Text><Text style={s.consultantLine}>Validade da proposta: {validUntil}</Text></View><Text style={s.pageNo}>08</Text></Page>
  <Page size={PAGE_SIZE} style={s.page}><Image src={bg("back-cover.png")} style={s.bg}/></Page>
 </Document>;
}
export async function POST(req:NextRequest){const body=await req.json();if(!body?.simulation)return Response.json({error:"simulation_required"},{status:400});const buffer=await renderToBuffer(<ProposalPdf body={body}/>);return new Response(new Uint8Array(buffer),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="proposta-locagora-v13.pdf"`,"Cache-Control":"no-store"}})}
