"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { DEFAULT_COMMERCIAL_CONFIG, normalizeCommercialConfig, type CommercialConfig } from "@/lib/commercial-config";
import { ArrowLeft, BarChart3, CheckCircle2, FileUp, RefreshCcw, Save, ShieldCheck, UsersRound } from "lucide-react";
import Link from "next/link";
import Phase5Admin from "./Phase5Admin";
import V8GovernanceAdmin from "./V8GovernanceAdmin";
import PublicPresentationAdmin from "./PublicPresentationAdmin";
import TestimonialAdmin from "./TestimonialAdmin";
import BenchmarkAdmin from "./BenchmarkAdmin";
import MarketIntelligenceAdmin from "./MarketIntelligenceAdmin";
import ProductCatalogAdmin from "./ProductCatalogAdmin";

const money=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(n||0);

type DocRow={id:string;slug:string;title:string;public_url:string;active:boolean;updated_at:string};
const docOptions=[
  ["franquias","Franquias Locagora 2026"],["exclusive","Franquia Nacional Exclusive"],["locinvest","LocInvest"],["internacional","Locagora Internacional"],["cotas","Cotas Locagora"]
] as const;

export default function AdminPanel(){
 const supabase=useMemo(()=>createClient(),[]);
 const [checked,setChecked]=useState(false);const [admin,setAdmin]=useState(false);const [claimable,setClaimable]=useState(false);
 const [config,setConfig]=useState<CommercialConfig>(DEFAULT_COMMERCIAL_CONFIG);const [status,setStatus]=useState("");const [docs,setDocs]=useState<DocRow[]>([]);
 const [docSlug,setDocSlug]=useState("franquias");const [file,setFile]=useState<File|null>(null);const [uploading,setUploading]=useState(false);
 const refresh=async()=>{
   setStatus("");
   try{
     const {data:isAdmin,error:aerr}=await supabase.rpc("is_commercial_admin"); if(aerr)throw aerr;
     setAdmin(Boolean(isAdmin));
     const {data:canClaim}=await supabase.rpc("can_claim_commercial_admin");setClaimable(Boolean(canClaim));
     const {data:setting}=await supabase.from("commercial_settings").select("value").eq("key","pricing").maybeSingle();if(setting?.value)setConfig(normalizeCommercialConfig(setting.value));
     const {data:documents}=await supabase.from("commercial_documents").select("id,slug,title,public_url,active,updated_at").order("updated_at",{ascending:false});setDocs((documents||[]) as DocRow[]);
   }catch(e){setStatus(e instanceof Error?e.message:"Não foi possível carregar o painel.");}
   finally{setChecked(true)}
 };
 useEffect(()=>{void refresh()},[]);
 const setNum=(path:string,value:string)=>{const n=Number(value)||0;setConfig(prev=>{const copy=structuredClone(prev) as any;const parts=path.split(".");let obj=copy;for(let i=0;i<parts.length-1;i++)obj=obj[parts[i]];obj[parts.at(-1)!]=n;return copy;});};
 const setArrayNum=(path:string,index:number,value:string)=>{const n=Number(value)||0;setConfig(prev=>{const copy=structuredClone(prev) as any;const parts=path.split(".");let obj=copy;for(let i=0;i<parts.length;i++)obj=obj[parts[i]];obj[index]=n;return copy;});};
 const claim=async()=>{setStatus("Ativando perfil...");const {data,error}=await supabase.rpc("claim_commercial_admin");if(error)setStatus(error.message);else{setStatus(data?"Administrador ativado.":"Não foi possível ativar este perfil.");await refresh();}};
 const publish=async()=>{setStatus("Publicando alterações...");const {data:user}=await supabase.auth.getUser();const {error}=await supabase.from("commercial_settings").upsert({key:"pricing",value:config,published:true,updated_at:new Date().toISOString(),updated_by:user.user?.id||null});setStatus(error?error.message:"Alterações publicadas. Novos acessos já usarão estes parâmetros.");};
 const upload=async()=>{if(!file)return;setUploading(true);setStatus("");try{const safe=file.name.normalize("NFD").replace(/[^a-zA-Z0-9._-]+/g,"-");const path=`${docSlug}/${Date.now()}-${safe}`;const {error:upErr}=await supabase.storage.from("commercial-public-docs").upload(path,file,{upsert:false,contentType:"application/pdf"});if(upErr)throw upErr;const {data:urlData}=supabase.storage.from("commercial-public-docs").getPublicUrl(path);const title=docOptions.find(x=>x[0]===docSlug)?.[1]||docSlug;const {data:user}=await supabase.auth.getUser();await supabase.from("commercial_documents").update({active:false}).eq("slug",docSlug);const {error:dbErr}=await supabase.from("commercial_documents").insert({slug:docSlug,title,storage_path:path,public_url:urlData.publicUrl,active:true,updated_by:user.user?.id||null});if(dbErr)throw dbErr;setFile(null);setStatus("PDF publicado com sucesso.");await refresh();}catch(e){setStatus(e instanceof Error?e.message:"Falha no upload.");}finally{setUploading(false)}};
 if(!checked)return <div className="adminLoading">Validando acesso administrativo...</div>;
 if(!admin)return <main className="adminScreen"><section className="adminCard"><ShieldCheck/><h1>Painel Administrativo V14 • V8</h1><p>Este painel controla parâmetros comerciais e materiais públicos. O primeiro administrador corporativo pode ativar o próprio perfil uma única vez.</p>{status&&<div className="statusWarn">{status}</div>}{claimable?<button className="primary" onClick={claim}>Ativar meu perfil administrador</button>:<div className="statusWarn">Seu usuário corporativo não possui permissão de administrador.</div>}<a href="/central">Voltar à Central</a></section></main>;
 return <main className="adminWorkspace"><div className="phase7TopNav"><Link href="/central"><ArrowLeft size={16}/> Voltar à Central Comercial</Link><span>Administração • alterações controladas</span></div><header className="adminHero"><div><small>ADMIN • V9.0</small><h1>Configuração comercial central</h1><p>Altere uma vez e publique para que novos acessos usem os mesmos parâmetros. Propostas já emitidas permanecem como snapshot.</p></div><button className="secondary" onClick={()=>void refresh()}><RefreshCcw/> Recarregar</button></header><section className="adminSection adminControlCenter"><div className="sectionHead"><small>CENTRAL ADMINISTRATIVA</small><h2>Gestão, CRM e inteligência</h2><p>Estes módulos ficam concentrados na engrenagem administrativa e só aparecem para administradores autorizados.</p></div><div className="adminHubGrid"><Link href="/crm?from=admin" className="adminHubCard"><UsersRound/><div><b>CRM • Pipeline</b><span>Leads, atividades, tarefas e acompanhamento comercial.</span></div></Link><Link href="/analytics?from=admin" className="adminHubCard"><BarChart3/><div><b>Analytics • Funil</b><span>Conversão, desempenho e inteligência comercial.</span></div></Link></div></section>{status&&<div className="adminStatus"><CheckCircle2/>{status}</div>}
 <section className="adminSection"><div className="sectionHead"><small>LOCINVEST</small><h2>Planos, motos, 3 opções de taxa e renda padrão</h2><p>As três taxas publicadas viram opções para o consultor. Não há digitação livre de taxa fora do Admin.</p></div><div className="adminPlanGrid">{(["start","premium","exclusive"] as const).map(k=><div className="adminGroup" key={k}><h3>{k.toUpperCase()}</h3><label>Valor da moto<input type="number" value={config.locinvest[k].bike} onChange={e=>setNum(`locinvest.${k}.bike`,e.target.value)}/></label>{config.locinvest[k].feeOptions.map((v,i)=><label key={i}>Taxa ADM • opção {i+1}<input type="number" value={v} onChange={e=>setArrayNum(`locinvest.${k}.feeOptions`,i,e.target.value)}/></label>)}<label>Renda / moto / mês<input type="number" value={config.locinvest[k].income} onChange={e=>setNum(`locinvest.${k}.income`,e.target.value)}/></label><label>Apropriação / moto<input type="number" value={config.locinvest[k].appropriation} onChange={e=>setNum(`locinvest.${k}.appropriation`,e.target.value)}/></label></div>)}</div></section>
 <section className="adminSection"><div className="sectionHead"><small>EUROLOC</small><h2>Taxas e renda por faixa</h2><p>As opções abaixo alimentam diretamente o simulador EUROLOC.</p></div><div className="adminPlanGrid">{(["start","exclusive","premium","black"] as const).map(k=><div className="adminGroup" key={k}><h3>{k.toUpperCase()}</h3>{config.euroloc[k].feeOptions.map((v,i)=><label key={i}>Taxa ADM • opção {i+1}<input type="number" value={v} onChange={e=>setArrayNum(`euroloc.${k}.feeOptions`,i,e.target.value)}/></label>)}<label>Renda / moto / mês<input type="number" value={config.euroloc[k].income} onChange={e=>setNum(`euroloc.${k}.income`,e.target.value)}/></label></div>)}</div></section>
 <section className="adminSection"><div className="sectionHead"><small>LOCMILLION</small><h2>Composição do projeto</h2></div><div className="adminFormGrid"><label>Projeto total<input type="number" value={config.locmillion.total} onChange={e=>setNum("locmillion.total",e.target.value)}/></label><label>Taxa ADM<input type="number" value={config.locmillion.adm} onChange={e=>setNum("locmillion.adm",e.target.value)}/></label><label>Estrutura / implantação<input type="number" value={config.locmillion.activation} onChange={e=>setNum("locmillion.activation",e.target.value)}/></label><label>Base de ativos<input type="number" value={config.locmillion.assetBase} onChange={e=>setNum("locmillion.assetBase",e.target.value)}/></label><label>Quantidade de motos<input type="number" value={config.locmillion.bikes} onChange={e=>setNum("locmillion.bikes",e.target.value)}/></label><label>Valor unitário<input type="number" value={config.locmillion.unitValue} onChange={e=>setNum("locmillion.unitValue",e.target.value)}/></label><label>Renda mensal projeto<input type="number" value={config.locmillion.monthly} onChange={e=>setNum("locmillion.monthly",e.target.value)}/></label></div></section>
 <section className="adminSection"><div className="sectionHead"><small>FRANQUIAS</small><h2>Taxas publicadas e valores estruturais</h2><p>Brasil e Internacional usam somente as opções publicadas aqui.</p></div><div className="adminPlanGrid"><div className="adminGroup"><h3>FRANQUIA BRASIL</h3>{config.franchiseNational.feeOptions.map((v,i)=><label key={i}>Taxa de franquia • opção {i+1}<input type="number" value={v} onChange={e=>setArrayNum("franchiseNational.feeOptions",i,e.target.value)}/></label>)}</div><div className="adminGroup"><h3>FRANQUIA INTERNACIONAL</h3>{config.franchiseInternational.feeOptions.map((v,i)=><label key={i}>Taxa de franquia • opção {i+1}<input type="number" value={v} onChange={e=>setArrayNum("franchiseInternational.feeOptions",i,e.target.value)}/></label>)}<label>Câmbio padrão EUR/BRL<input type="number" step=".01" value={config.franchiseInternational.fx} onChange={e=>setNum("franchiseInternational.fx",e.target.value)}/></label></div></div><div className="adminFormGrid"><label>Moto Franquia Nacional<input type="number" value={config.franchiseNational.bikeValue} onChange={e=>setNum("franchiseNational.bikeValue",e.target.value)}/></label><label>Intermediação / moto<input type="number" value={config.franchiseNational.intermediationPerBike} onChange={e=>setNum("franchiseNational.intermediationPerBike",e.target.value)}/></label><label>Capital de giro / moto<input type="number" value={config.franchiseNational.workingPerBike} onChange={e=>setNum("franchiseNational.workingPerBike",e.target.value)}/></label><label>Receita locação / moto<input type="number" value={config.franchiseNational.rentalPerBike} onChange={e=>setNum("franchiseNational.rentalPerBike",e.target.value)}/></label><label>Royalties (%)<input type="number" step=".1" value={config.franchiseNational.royaltyPct} onChange={e=>setNum("franchiseNational.royaltyPct",e.target.value)}/></label><label>Mini-Master taxa<input type="number" value={config.miniMaster.fee} onChange={e=>setNum("miniMaster.fee",e.target.value)}/></label><label>Mini-Master estrutura<input type="number" value={config.miniMaster.structure} onChange={e=>setNum("miniMaster.structure",e.target.value)}/></label><label>Master Regional investimento<input type="number" value={config.masterRegional.referenceInvestment} onChange={e=>setNum("masterRegional.referenceInvestment",e.target.value)}/></label></div><div className="adminPreview">Exemplo atual: LocMillion {money(config.locmillion.total)} • Master {money(config.masterRegional.referenceInvestment)}</div></section>
 <div className="adminPublishBar"><div><small>PUBLICAÇÃO GLOBAL</small><b>As alterações entram para novos acessos e novas simulações.</b></div><button className="primary" onClick={()=>void publish()}><Save/> Publicar alterações</button></div>
 <V8GovernanceAdmin/>
 <Phase5Admin/>
 <ProductCatalogAdmin/><PublicPresentationAdmin/><TestimonialAdmin/><MarketIntelligenceAdmin/><BenchmarkAdmin/>
 <section className="adminSection"><div className="sectionHead"><small>MATERIAIS PÚBLICOS</small><h2>Substituir PDF de cada produto</h2><p>O arquivo publicado aparece no portal público. O histórico de arquivos permanece no Storage.</p></div><div className="adminUploadRow"><select value={docSlug} onChange={e=>setDocSlug(e.target.value)}>{docOptions.map(([slug,title])=><option key={slug} value={slug}>{title}</option>)}</select><input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="primary" disabled={!file||uploading} onClick={()=>void upload()}><FileUp/>{uploading?"Enviando...":"Publicar PDF"}</button></div><div className="adminDocs">{docs.map(d=><a href={d.public_url} target="_blank" rel="noreferrer" key={d.id}><b>{d.title}</b><span>{d.active?"PUBLICADO":"ARQUIVO ANTERIOR"}</span><small>{new Date(d.updated_at).toLocaleString("pt-BR")}</small></a>)}</div></section>
 </main>;
}
