"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { ArrowLeft, BarChart3, Download, Info, RefreshCcw, ShieldCheck, TrendingUp } from "lucide-react";
import Link from "next/link";
import AdminModuleNav from "./AdminModuleNav";

type EventRow={event_name:string;created_at:string;route?:string|null;product_route?:string|null;premise_version?:number|null;metadata:Record<string,unknown>|null};
const labels:Record<string,string>={public_simulator_viewed:"Visitas ao simulador",public_simulation_calculated:"Simulações calculadas",public_lead_submit_started:"Pedidos de contato iniciados",public_lead_captured:"Leads capturados",commercial_notification_sent:"E-mails enviados"};
const funnel=["public_simulator_viewed","public_simulation_calculated","public_lead_submit_started","public_lead_captured","commercial_notification_sent"];
const pct=(a:number,b:number)=>b>0?`${Math.round((a/b)*100)}%`:"—";
const csvCell=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;

export default function AnalyticsDashboard(){
  const supabase=useMemo(()=>createClient(),[]);
  const [rows,setRows]=useState<EventRow[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [days,setDays]=useState(30);
  const load=async(nextDays=days)=>{setLoading(true);setError("");const since=new Date(Date.now()-nextDays*86400000).toISOString();const {data,error}=await supabase.from("commercial_analytics_events").select("event_name,created_at,route,product_route,premise_version,metadata").gte("created_at",since).order("created_at",{ascending:false}).limit(5000);if(error)setError(error.message);else setRows((data||[]) as EventRow[]);setLoading(false);};
  useEffect(()=>{void load(days)},[days]);
  const counts=useMemo(()=>Object.fromEntries(funnel.map(name=>[name,rows.filter(r=>r.event_name===name).length])),[rows]);
  const failures=useMemo(()=>rows.filter(r=>r.event_name==="public_lead_capture_failed"||r.event_name==="commercial_notification_failed").length,[rows]);
  const productBreakdown=useMemo(()=>{const map:Record<string,number>={};for(const row of rows){const key=row.product_route||"sem produto";map[key]=(map[key]||0)+1;}return Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,8);},[rows]);
  const exportCsv=()=>{const lines=[["Evento","Data","Rota","Produto","Versão de premissa"],...rows.map(r=>[r.event_name,new Date(r.created_at).toLocaleString("pt-BR"),r.route||"",r.product_route||"",r.premise_version||""])].map(row=>row.map(csvCell).join(";"));const blob=new Blob(["\ufeff"+lines.join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`locagora-analytics-${days}d-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);};
  return <main className="analyticsPage"><div aria-label="Voltar à Central Comercial"><AdminModuleNav current="analytics"/></div><header className="analyticsHeader"><div><small>ANALYTICS • V9.0</small><h1>Funil comercial sem PII</h1><p>Entenda onde as pessoas avançam ou abandonam a jornada, sem copiar nome, e-mail ou telefone para a camada analítica.</p></div><div className="analyticsActions"><label>Período<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 dias</option><option value={30}>30 dias</option><option value={90}>90 dias</option></select></label><button className="secondary" onClick={()=>void load(days)}><RefreshCcw size={17}/> Atualizar</button><button className="secondary" onClick={exportCsv}><Download size={17}/> CSV</button></div></header><section className="analyticsExplainer"><Info size={19}/><div><b>Como ler esta tela</b><p><strong>Visita</strong> mede entrada no simulador; <strong>simulação</strong> mede cálculo concluído; <strong>pedido de contato</strong> indica intenção de falar com a equipe; <strong>lead capturado</strong> confirma gravação no CRM; <strong>e-mail enviado</strong> confirma a notificação comercial. A queda entre duas etapas mostra onde priorizar melhorias.</p></div></section>
  <section className="analyticsKpis"><article><BarChart3/><span>Eventos</span><b>{rows.length}</b></article><article><TrendingUp/><span>Conversão simulação → lead</span><b>{pct(counts.public_lead_captured||0,counts.public_simulation_calculated||0)}</b></article><article><ShieldCheck/><span>Falhas observadas</span><b>{failures}</b></article></section>
  {error&&<div className="statusWarn">{error}</div>}{loading?<div className="analyticsEmpty">Carregando eventos…</div>:<><section className="analyticsFunnel"><div className="analyticsFunnelHead"><small>FUNIL • {days} DIAS</small><h2>Da visita ao contato comercial</h2></div>{funnel.map((name,index)=>{const count=counts[name]||0;const prev=index===0?count:(counts[funnel[index-1]]||0);return <article key={name}><div><span>{index+1}</span><b>{labels[name]}</b></div><strong>{count}</strong><small>{index===0?"base":`${pct(count,prev)} da etapa anterior`}</small></article>})}</section><section className="analyticsBreakdown"><div className="analyticsFunnelHead"><small>ORIGEM / MODELO</small><h2>Eventos por produto</h2><p>Ajuda a identificar quais jornadas geram mais atividade sem registrar dados pessoais.</p></div><div className="v8BreakdownBars">{productBreakdown.length?productBreakdown.map(([name,count])=><article key={name}><span>{name}</span><div><i style={{width:`${Math.max(5,Math.round(count/Math.max(1,productBreakdown[0][1])*100))}%`}}/></div><b>{count}</b></article>):<p>Sem eventos no período.</p>}</div></section></>}
  <section className="analyticsPrivacy"><ShieldCheck/><div><b>Contrato de privacidade da Fase 6</b><p>Os eventos guardam apenas sessão técnica aleatória, rota, produto, versão de premissas e métricas operacionais não identificáveis. PII continua restrita ao CRM.</p></div></section></main>;
}
