"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, ArrowUpRight, CheckCircle2, Info, RefreshCw, Scale, Sparkles } from "lucide-react";
import { DEFAULT_BENCHMARKS, projectAnnualRate, projectLocagora, type CapitalBenchmark } from "@/lib/capital-comparator";
import { loadMarketAssumptions, loadProductFinancialProfile, persistComparisonScenario, type FinancialProfile, type MarketAssumption } from "@/lib/comparison-repository";
import type { ComparisonSnapshot, Simulation } from "@/lib/types";
import styles from "./CapitalOpportunityComparator.module.css";

const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(Number(v)||0);
const numberBR=(v:number)=>new Intl.NumberFormat("pt-BR",{maximumFractionDigits:0}).format(Number(v)||0);
const parseBR=(v:string)=>Number(String(v||"").replace(/\D/g,""))||0;
const pct=(v:number)=>`${(Number(v)||0).toFixed(2).replace(".",",")}%`;
const STORAGE="locagora_capital_comparator_v3";

type Props={simulation?:Simulation|null;selected?:ComparisonSnapshot|null;onSelect?:(snapshot:ComparisonSnapshot)=>void;onContinue?:()=>void;onBack?:()=>void;embedded?:boolean};
type Candidate={id:string;label:string;kind:"product"|"benchmark";benchmarkKey?:string;annualRate?:number;taxOnGain?:number;projection:{finalValue:number;grossGain:number;netGain:number;monthlyEquivalent:number};sourceName?:string;referenceDate?:string;assumption?:MarketAssumption};

const assumptionFor=(rows:MarketAssumption[],key:string)=>rows.find(x=>x.assumption_key===key);
const benchmarkKey=(id:string)=>({"cdi-cdb":"CDI","tesouro-selic":"SELIC","ipca":"IPCA_PLUS_REAL","fii":"FII_DY","imovel":"PROPERTY_RENT_YIELD"}[id]||id);
const scenarioType=(id:string)=>({"cdi-cdb":"cdi_cdb","tesouro-selic":"tesouro_selic","ipca":"tesouro_ipca_plus","fii":"fii","imovel":"rental_property"}[id]||"custom") as any;

export default function CapitalOpportunityComparator({simulation,selected,onSelect,onContinue,onBack,embedded=false}:Props){
 const [capital,setCapital]=useState(simulation?.capital||100000);const [monthly,setMonthly]=useState(simulation?.monthly||0);const [product,setProduct]=useState(simulation?.name||"Cenário Locagora");const [months,setMonths]=useState(36);const [reinvest,setReinvest]=useState(false);const [benchmarks,setBenchmarks]=useState<CapitalBenchmark[]>(DEFAULT_BENCHMARKS);const [assumptions,setAssumptions]=useState<MarketAssumption[]>([]);const [profile,setProfile]=useState<FinancialProfile|null>(null);const [rateStatus,setRateStatus]=useState("Carregando referências...");const [saving,setSaving]=useState(false);const [status,setStatus]=useState("");
 useEffect(()=>{if(simulation){setCapital(simulation.capital);setMonthly(simulation.monthly);setProduct(simulation.name)}},[simulation]);
 async function refreshRates(){setRateStatus("Atualizando referências...");try{const [market,financial]=await Promise.all([loadMarketAssumptions(),simulation?loadProductFinancialProfile(simulation.sourceRoute):Promise.resolve(null)]);setAssumptions(market);setProfile(financial);setBenchmarks(prev=>prev.map(b=>{const a=assumptionFor(market,benchmarkKey(b.id));return{...b,annualRate:a?.value==null?b.annualRate:Number(a.value)}}));setRateStatus(`Premissas carregadas ${new Date().toLocaleString("pt-BR")}`)}catch{setRateStatus("Não foi possível atualizar agora; mantendo as últimas premissas salvas.")}}
 useEffect(()=>{try{const saved=localStorage.getItem(STORAGE);if(saved){const x=JSON.parse(saved);if(x?.benchmarks)setBenchmarks(x.benchmarks);if(x?.months)setMonths(x.months);if(typeof x?.reinvest==="boolean")setReinvest(x.reinvest)}}catch{}void refreshRates()},[]);
 useEffect(()=>{try{localStorage.setItem(STORAGE,JSON.stringify({benchmarks,months,reinvest}))}catch{}},[benchmarks,months,reinvest]);
 useEffect(()=>{if(profile?.default_term_months)setMonths(profile.default_term_months);if(profile&&!profile.allow_reinvestment)setReinvest(false)},[profile]);
 const incomeIsNet=profile?.income_basis==="net"||profile?.taxation_model==="withheld_at_source";const productTax=incomeIsNet?0:Number(profile?.tax_rate_pct||0);const locGross=projectLocagora(capital,monthly,months,reinvest);const locTax=locGross.grossGain>0?locGross.grossGain*(productTax/100):0;const loc={...locGross,netGain:locGross.grossGain-locTax,finalValue:capital+locGross.grossGain-locTax,monthlyEquivalent:(locGross.grossGain-locTax)/months};
 const rows=useMemo(()=>benchmarks.filter(x=>x.enabled).map(x=>{const a=assumptionFor(assumptions,benchmarkKey(x.id));const projection=projectAnnualRate(capital,x.annualRate,x.taxOnGain,months);return{id:x.id,label:x.label,kind:"benchmark" as const,benchmarkKey:benchmarkKey(x.id),annualRate:x.annualRate,taxOnGain:x.taxOnGain,projection,sourceName:a?.source_name||undefined,referenceDate:a?.reference_date||undefined,assumption:a}}),[benchmarks,capital,months,assumptions]);
 const productCandidate:Candidate={id:"product",label:product,kind:"product",projection:loc};const all=[productCandidate,...rows];const best=Math.max(...all.map(x=>x.projection.netGain),0);const simpleAnnual=capital>0?(monthly*12/capital)*100:0;
 async function choose(candidate:Candidate){if(!simulation){setStatus("Abra o comparador pela Jornada para salvar o cenário na proposta.");return}setSaving(true);setStatus("Salvando cenário selecionado...");try{const grossFinal=candidate.kind==="product"?locGross.finalValue:capital+candidate.projection.grossGain;const taxAmount=Math.max(0,grossFinal-candidate.projection.finalValue);const snapshot=await persistComparisonScenario({simulation,scenarioType:candidate.kind==="product"?"product":scenarioType(candidate.id),benchmarkKey:candidate.benchmarkKey,label:candidate.label,horizonMonths:months,reinvestment:candidate.kind==="product"?reinvest:true,annualReturnPct:candidate.kind==="product"?simpleAnnual:candidate.annualRate,grossFinalValue:grossFinal,taxAmount,netFinalValue:candidate.projection.finalValue,netGain:candidate.projection.netGain,accumulatedReturnPct:capital>0?(candidate.projection.netGain/capital)*100:0,monthlyEquivalent:candidate.projection.monthlyEquivalent,taxationSnapshot:candidate.kind==="product"?{model:profile?.taxation_model||"configurable",ratePct:productTax,incomeBasis:profile?.income_basis||"configurable"}:{taxOnGainPct:candidate.taxOnGain||0},assumptionsSnapshot:candidate.assumption?{[candidate.assumption.assumption_key]:candidate.assumption}: {},sourceName:candidate.sourceName,sourceReferenceDate:candidate.referenceDate});onSelect?.(snapshot);setStatus(`${candidate.label} selecionado para apresentação e proposta.`)}catch(e){setStatus(e instanceof Error?e.message:"Não foi possível salvar o cenário.")}finally{setSaving(false)}}
 return <main className={embedded?styles.embedded:styles.workspace}>
  {!embedded&&<section className={styles.hero}><div><small>V9.3.2 • COMPARADOR INTEGRADO</small><h1>Comparador de Oportunidades de Capital</h1><p>Simulação, referências, cenário selecionado e proposta usam o mesmo capital, horizonte e snapshot comercial.</p></div><div className={styles.heroBadge}><Scale/><span><b>Comparação assistida</b><small>Premissas rastreáveis</small></span></div></section>}
  <section className={styles.notice}><Info/><div><b>Ferramenta comercial de comparação, não recomendação de investimento.</b><span>Taxas e regras tributárias vêm das premissas e perfis publicados. A proposta congela o cenário escolhido para preservar os números históricos.</span></div></section>
  <section className={styles.inputGrid}><label><span>Capital comparado</span><input type="text" inputMode="numeric" value={numberBR(capital)} onChange={e=>setCapital(parseBR(e.target.value))}/></label><label><span>Renda mensal Locagora</span><input type="text" inputMode="numeric" value={numberBR(monthly)} onChange={e=>setMonthly(parseBR(e.target.value))}/></label><label><span>Horizonte</span><select value={months} onChange={e=>setMonths(Number(e.target.value))}><option value={12}>12 meses</option><option value={24}>24 meses</option><option value={36}>36 meses</option><option value={60}>60 meses</option><option value={120}>120 meses</option></select></label><label className={styles.toggle}><span>Reinvestir renda Locagora</span><input type="checkbox" disabled={profile?.allow_reinvestment===false} checked={reinvest} onChange={e=>setReinvest(e.target.checked)}/><i/></label><button className={styles.importBtn} type="button" onClick={()=>void refreshRates()}><RefreshCw/> Atualizar premissas</button></section>
  <section className={styles.locCard}><div className={styles.locHead}><div><small>CENÁRIO LOCAGORA • IMPORTADO DA SIMULAÇÃO</small><h2>{product}</h2></div><Sparkles/></div><div className={styles.metrics}><div><span>Capital</span><b>{money(capital)}</b></div><div><span>Renda mensal</span><b>{money(monthly)}</b></div><div><span>Retorno anual simples</span><b>{pct(simpleAnnual)}</b></div><div><span>Resultado líquido em {months} meses</span><b>{money(loc.netGain)}</b></div></div><p>Tributação do produto: {profile?`${profile.taxation_model} • base ${profile.income_basis}${profile.tax_rate_pct!=null?` • ${pct(profile.tax_rate_pct)}`:" • taxa definida pelo ADM"}`:"perfil financeiro aguardando publicação"}.</p></section>
  <section className={styles.benchSection}><div className={styles.sectionHead}><div><small>PREMISSAS EXTERNAS</small><h2>Referências para comparação</h2><p className={styles.rateStatus}>{rateStatus}</p></div></div><div className={styles.benchmarkGrid}>{benchmarks.map(b=>{const a=assumptionFor(assumptions,benchmarkKey(b.id));return <article key={b.id} className={!b.enabled?styles.disabled:""}><div className={styles.cardTitle}><label className={styles.check}><input type="checkbox" checked={b.enabled} onChange={e=>setBenchmarks(v=>v.map(x=>x.id===b.id?{...x,enabled:e.target.checked}:x))}/><CheckCircle2/></label><b>{b.label}</b></div><label><span>Taxa de referência (% a.a.)</span><input type="number" step="0.01" value={b.annualRate} onChange={e=>setBenchmarks(v=>v.map(x=>x.id===b.id?{...x,annualRate:Number(e.target.value)}:x))}/></label><label><span>IR sobre ganho (%)</span><input type="number" min="0" max="100" step="0.5" value={b.taxOnGain} onChange={e=>setBenchmarks(v=>v.map(x=>x.id===b.id?{...x,taxOnGain:Number(e.target.value)}:x))}/></label><small className={styles.source}>{a?.source_name||"Premissa ADM"}{a?.reference_date?` • ${new Date(a.reference_date+"T12:00:00").toLocaleDateString("pt-BR")}`:""}</small></article>})}</div></section>
  <section className={styles.results}><div className={styles.sectionHead}><div><small>RESULTADO COMPARATIVO</small><h2>Mesmo capital • mesmo horizonte</h2></div><ArrowUpRight/></div><div className={styles.tableWrap}><table><thead><tr><th>Oportunidade</th><th>Premissa</th><th>Ganho líquido/projetado</th><th>Valor econômico ao fim</th><th>Média/mês</th><th></th></tr></thead><tbody>{all.map(r=><tr key={r.id} className={r.projection.netGain===best?styles.best:""}><td><b>{r.label}</b><small>{r.kind==="product"?"Produto Locagora":"Referência de mercado"}</small></td><td>{r.kind==="product"?`${money(monthly)}/mês`: `${pct(r.annualRate||0)} a.a. • IR ${pct(r.taxOnGain||0)}`}</td><td>{money(r.projection.netGain)}</td><td>{money(r.projection.finalValue)}</td><td>{money(r.projection.monthlyEquivalent)}</td><td><button className={selected?.label===r.label?styles.selectedBtn:styles.selectBtn} disabled={saving} onClick={()=>void choose(r)}>{selected?.label===r.label?<><CheckCircle2/> Selecionado</>:<>Selecionar <ArrowRight/></>}</button></td></tr>)}</tbody></table></div><div className={styles.footnote}>Maior resultado matemático não significa automaticamente melhor investimento. Liquidez, risco, garantias, volatilidade, tributação e natureza do ativo precisam ser avaliados separadamente.</div>{status&&<p className={styles.selectionStatus}>{status}</p>}</section>
  {embedded&&<div className={styles.journeyActions}>{onBack&&<button className="secondary" onClick={onBack}>Voltar à confirmação</button>}{onContinue&&<button className="primary" disabled={!selected} onClick={onContinue}>Continuar com cenário selecionado <ArrowRight size={16}/></button>}</div>}
 </main>
}
