"use client";
import { IntranetHighlights } from "./IntranetModule";
import { ArrowRight, Bike, BookOpenText, Building2, ExternalLink, Gauge, Headphones, Landmark, Megaphone, Newspaper, Network, Scale, Settings, Users } from "lucide-react";
import { ACCESS_PROFILE_LABELS, DEPARTMENT_LABELS, MODULE_LABELS, allowedCorporatePages, normalizeAccessProfile, normalizeDepartment, type CorporatePage } from "@/lib/corporate-access";

type User={name?:string|null;department?:string|null;job_title?:string|null;access_profile?:string|null;module_permissions?:string[]|null;role?:string|null};
const meta:Record<Exclude<CorporatePage,"home">,{icon:any,desc:string}>={
 announcements:{icon:Megaphone,desc:"Avisos da empresa e do seu setor."},documents:{icon:BookOpenText,desc:"Manuais, políticas e documentos internos."},directory:{icon:Users,desc:"Encontre colegas e contatos profissionais."},news:{icon:Newspaper,desc:"Mercado, notícias e inteligência."},solutions:{icon:Building2,desc:"Produtos, franquias e simuladores."},network:{icon:Network,desc:"Rede, Masters, bases e expansão."},history:{icon:BookOpenText,desc:"História e posicionamento institucional."},benchmark:{icon:Gauge,desc:"Referências e comparação de mercado."},capital:{icon:Scale,desc:"Comparador de oportunidades de capital."},support:{icon:Headphones,desc:"Contatos, objeções e apoio interno."},quality:{icon:Settings,desc:"Homologação e qualidade do sistema."}
};
const deptIcon:Record<string,any>={COMERCIAL:Building2,DIRETORIA:Landmark,FINANCEIRO:Landmark,RH:Users,MARKETING:Megaphone,OPERACOES:Bike,CS:Headphones,TI_SUPORTE:Settings,JURIDICO:BookOpenText};
export default function CorporateHome({user,onOpen}:{user:User|null;onOpen:(p:CorporatePage)=>void}){
 const department=normalizeDepartment(user?.department),profile=normalizeAccessProfile(user?.access_profile),pages=allowedCorporatePages(user).filter((p):p is Exclude<CorporatePage,"home">=>p!=="home"),DeptIcon=deptIcon[department]||Building2,isAdmin=String(user?.role||"").toUpperCase()==="ADMIN"||profile==="ADMINISTRADOR";
 return <main className="workspace"><section className="panel" style={{background:"linear-gradient(120deg,#071a3f,#143f8e)",color:"white",padding:30}}><div style={{display:"flex",gap:18,alignItems:"center",flexWrap:"wrap"}}><div style={{width:58,height:58,borderRadius:16,display:"grid",placeItems:"center",background:"rgba(255,255,255,.1)"}}><DeptIcon size={28}/></div><div><small style={{color:"#76ec3f",fontWeight:900,letterSpacing:1.2}}>INTRANET LOCAGORA</small><h1 style={{margin:"6px 0 4px",fontSize:34}}>Olá, {user?.name?.split(" ")[0]||"colaborador"}.</h1><p style={{margin:0,color:"#d6e1f5"}}>{DEPARTMENT_LABELS[department]}{user?.job_title?` • ${user.job_title}`:""} • {ACCESS_PROFILE_LABELS[profile]}</p></div></div></section>
 <IntranetHighlights onOpen={onOpen}/><section className="panel"><div className="sectionHead"><small>SEUS ATALHOS</small><h2>Ferramentas disponíveis para o seu perfil</h2><p>Os módulos são organizados pelo departamento e pelas permissões adicionais definidas no ADM.</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:12,marginTop:18}}>{pages.map(p=>{const Icon=meta[p].icon;return <button key={p} onClick={()=>onOpen(p)} style={{textAlign:"left",border:"1px solid #dce4ef",borderRadius:16,padding:18,background:"#fff",display:"flex",gap:14,alignItems:"flex-start"}}><span style={{width:42,height:42,borderRadius:12,background:"#eef4ff",color:"#0d46b8",display:"grid",placeItems:"center",flex:"0 0 auto"}}><Icon size={20}/></span><span style={{minWidth:0}}><b style={{display:"block",color:"#111c31"}}>{MODULE_LABELS[p]}</b><small style={{display:"block",color:"#68778e",lineHeight:1.45,marginTop:5}}>{meta[p].desc}</small><span style={{display:"inline-flex",alignItems:"center",gap:5,color:"#0d46b8",fontWeight:800,fontSize:11,marginTop:10}}>Abrir <ArrowRight size={13}/></span></span></button>})}{isAdmin&&<a href="/admin/perfis" style={{textDecoration:"none",color:"inherit",border:"1px solid #c7d7ef",borderRadius:16,padding:18,background:"#f5f9ff",display:"flex",gap:14,alignItems:"flex-start"}}><span style={{width:42,height:42,borderRadius:12,background:"#0d46b8",color:"white",display:"grid",placeItems:"center",flex:"0 0 auto"}}><Users size={20}/></span><span><b style={{display:"block"}}>Gestão de perfis</b><small style={{display:"block",color:"#68778e",lineHeight:1.45,marginTop:5}}>Departamentos, cargos e acessos por colaborador.</small><span style={{display:"inline-flex",alignItems:"center",gap:5,color:"#0d46b8",fontWeight:800,fontSize:11,marginTop:10}}>Abrir ADM <ArrowRight size={13}/></span></span></a>}</div></section>
 <section className="panel"><div className="sectionHead"><small>APLICATIVOS LOCAGORA</small><h2>Sistemas internos</h2></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:12,marginTop:16}}><a href="https://chamados-ti.locgrupo.com.br/#" target="_blank" rel="noreferrer" className="softBlock" style={{textDecoration:"none",color:"inherit",display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><span><b>Chamados LOC</b><small style={{display:"block",marginTop:5,color:"#68778e"}}>Suporte e TI</small></span><ExternalLink size={18}/></a><a href="https://rh-colaborador.quark.tec.br/" target="_blank" rel="noreferrer" className="softBlock" style={{textDecoration:"none",color:"inherit",display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><span><b>QuarkRH • Colaborador</b><small style={{display:"block",marginTop:5,color:"#68778e"}}>Portal do colaborador</small></span><ExternalLink size={18}/></a></div></section></main>;
}
