"use client";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, RefreshCcw, Save, Users } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { ACCESS_PROFILE_LABELS, DEPARTMENT_LABELS, MODULE_LABELS, type CorporateAccessProfile, type CorporateDepartment } from "@/lib/corporate-access";

type Row={profileId:string;name:string;email:string;department:CorporateDepartment;jobTitle:string;accessProfile:CorporateAccessProfile;modulePermissions:string[]};
const departments=Object.entries(DEPARTMENT_LABELS) as [CorporateDepartment,string][];
const profiles=Object.entries(ACCESS_PROFILE_LABELS) as [CorporateAccessProfile,string][];
const modules=Object.entries(MODULE_LABELS);
export default function CorporateProfilesAdmin(){
 const supabase=useMemo(()=>createClient(),[]);const [rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[status,setStatus]=useState("");
 const token=async()=>{const {data}=await supabase.auth.getSession();return data.session?.access_token||""};
 async function load(){setBusy(true);setStatus("");try{const t=await token();const accessRes=await fetch("/api/admin/access",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"});const access=await accessRes.json();if(!accessRes.ok)throw new Error(access.message||access.reason||"Falha ao carregar usuários.");const {data,error}=await supabase.from("users").select("id,department,job_title,access_profile,module_permissions");if(error)throw error;const byId=new Map((data||[]).map((x:any)=>[x.id,x]));setRows((access.members||[]).map((m:any)=>{const p:any=byId.get(m.profileId)||{};return{profileId:m.profileId,name:m.name||m.email,email:m.email,department:(p.department||"COMERCIAL") as CorporateDepartment,jobTitle:p.job_title||"",accessProfile:(p.access_profile||(String(m.role).toLowerCase()==="admin"?"ADMINISTRADOR":"COLABORADOR")) as CorporateAccessProfile,modulePermissions:Array.isArray(p.module_permissions)?p.module_permissions:[]}}));}catch(e){setStatus(e instanceof Error?e.message:"Falha ao carregar perfis corporativos.");}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 const patch=(id:string,change:Partial<Row>)=>setRows(xs=>xs.map(x=>x.profileId===id?{...x,...change}:x));
 const toggle=(row:Row,module:string)=>patch(row.profileId,{modulePermissions:row.modulePermissions.includes(module)?row.modulePermissions.filter(x=>x!==module):[...row.modulePermissions,module]});
 async function save(row:Row){setBusy(true);setStatus("Salvando perfil corporativo...");try{const {error}=await supabase.rpc("commercial_update_corporate_profile",{p_profile_id:row.profileId,p_department:row.department,p_job_title:row.jobTitle,p_access_profile:row.accessProfile,p_module_permissions:row.modulePermissions});if(error)throw error;setStatus(`Perfil de ${row.name} atualizado.`);}catch(e){setStatus(e instanceof Error?e.message:"Falha ao salvar perfil.");}finally{setBusy(false)}}
 return <details className="adminSection"><summary style={{cursor:"pointer",padding:"4px 0"}}><div className="sectionHead" style={{display:"inline-block",verticalAlign:"middle",marginLeft:8}}><small>PERFIS CORPORATIVOS</small><h2 style={{marginBottom:4}}>Departamentos, cargos e módulos</h2><p>Separe departamento, cargo e perfil de acesso. Libere módulos adicionais por colaborador quando necessário.</p></div></summary><div style={{marginTop:18}}><div className="v8AccessComposer"><div><b>{rows.length} perfis</b><small style={{display:"block"}}>Comercial, Diretoria, Financeiro, RH, Marketing, Operações, CS, TI/Suporte e Jurídico.</small></div><button className="secondary" onClick={()=>void load()} disabled={busy}><RefreshCcw size={17}/> Atualizar</button></div>{status&&<div className="adminStatus"><CheckCircle2/>{status}</div>}<div className="v8MemberList">{rows.map(row=><article key={row.profileId} style={{alignItems:"stretch",gap:12,display:"grid",gridTemplateColumns:"minmax(220px,1.2fr) minmax(160px,.8fr) minmax(180px,1fr) minmax(170px,.8fr)",padding:16}}><div><Users size={17}/><span><b>{row.name}</b><small>{row.email}</small></span></div><label style={{display:"grid",gap:6}}><small>Departamento</small><select value={row.department} onChange={e=>patch(row.profileId,{department:e.target.value as CorporateDepartment})}>{departments.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label style={{display:"grid",gap:6}}><small>Cargo / função</small><input value={row.jobTitle} onChange={e=>patch(row.profileId,{jobTitle:e.target.value})} placeholder="Ex.: Analista Financeiro"/></label><label style={{display:"grid",gap:6}}><small>Perfil de acesso</small><select value={row.accessProfile} onChange={e=>patch(row.profileId,{accessProfile:e.target.value as CorporateAccessProfile})}>{profiles.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div style={{gridColumn:"1/-1",display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}><small style={{fontWeight:800,color:"#50617b",marginRight:4}}>Módulos adicionais:</small>{modules.map(([id,label])=><label key={id} style={{display:"inline-flex",alignItems:"center",gap:5,fontSize:11,padding:"6px 9px",border:"1px solid #dce4ef",borderRadius:999,background:row.modulePermissions.includes(id)?"#eef8e9":"#fff"}}><input type="checkbox" checked={row.modulePermissions.includes(id)} onChange={()=>toggle(row,id)}/>{label}</label>)}<button className="primary" disabled={busy} onClick={()=>void save(row)} style={{marginLeft:"auto"}}><Save size={15}/> Salvar perfil</button></div></article>)}</div></div></details>;
}
