"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, Globe2 } from "lucide-react";
import { INTERNATIONAL_FRANCHISE, calculateInternationalDre, calculateInternationalInvestment } from "@/lib/franquia-internacional";
import { loadMotorcycles, motorcycleIntermediationBRL, motorcyclePriceBRL, type Motorcycle } from "@/lib/motorcycle-catalog";
import type { Simulation } from "@/lib/types";

const money=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(n)||0);
const eur=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"EUR"}).format(Number(n)||0);
const pct=(n:number)=>`${(Number(n)||0).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})}%`;

export default function FranquiaInternacionalCalculator({initialCapital,onBack,onSave,saveLabel}:{initialCapital:number;onBack:()=>void;onSave:(simulation:Simulation)=>void;saveLabel?:string;}){
 const [fee,setFee]=useState<number>(INTERNATIONAL_FRANCHISE.feeOptions[0]);
 const [qty,setQty]=useState(10); const [fx,setFx]=useState(6.20);
 const [brazilQty,setBrazilQty]=useState(10); const [europeQty,setEuropeQty]=useState(10);
 const [working,setWorking]=useState(600);
 const [brazilIntermediation,setBrazilIntermediation]=useState(0); const [europeIntermediation,setEuropeIntermediation]=useState(0);
 const [brazilBikes,setBrazilBikes]=useState<Motorcycle[]>([]); const [europeBikes,setEuropeBikes]=useState<Motorcycle[]>([]);
 const [brazilBikeId,setBrazilBikeId]=useState(""); const [europeBikeId,setEuropeBikeId]=useState("");
 const [brazilModel,setBrazilModel]=useState(INTERNATIONAL_FRANCHISE.brazilModels[0]); const [europeModel,setEuropeModel]=useState(INTERNATIONAL_FRANCHISE.europeModels[0]);
 const [brazilBikeValue,setBrazilBikeValue]=useState(16990); const [europeBikeValue,setEuropeBikeValue]=useState(24999);

 useEffect(()=>{void Promise.all([loadMotorcycles("brazil"),loadMotorcycles("international")]).then(([br,intl])=>{setBrazilBikes(br);setEuropeBikes(intl);if(br.length){const m=br[0];setBrazilBikeId(m.id);setBrazilModel(m.display_name);setBrazilBikeValue(motorcyclePriceBRL(m,fx));setBrazilIntermediation(motorcycleIntermediationBRL(m,fx));}if(intl.length){const m=intl[0];setEuropeBikeId(m.id);setEuropeModel(m.display_name);setEuropeBikeValue(motorcyclePriceBRL(m,fx));setEuropeIntermediation(motorcycleIntermediationBRL(m,fx));}})},[]);
 useEffect(()=>{const br=brazilBikes.find(x=>x.id===brazilBikeId);if(br){setBrazilBikeValue(motorcyclePriceBRL(br,fx));setBrazilIntermediation(motorcycleIntermediationBRL(br,fx));}const eu=europeBikes.find(x=>x.id===europeBikeId);if(eu){setEuropeBikeValue(motorcyclePriceBRL(eu,fx));setEuropeIntermediation(motorcycleIntermediationBRL(eu,fx));}},[fx,brazilBikeId,europeBikeId,brazilBikes,europeBikes]);
 const chooseBrazil=(id:string)=>{setBrazilBikeId(id);const m=brazilBikes.find(x=>x.id===id);if(m){setBrazilModel(m.display_name);setBrazilBikeValue(motorcyclePriceBRL(m,fx));setBrazilIntermediation(motorcycleIntermediationBRL(m,fx));}};
 const chooseEurope=(id:string)=>{setEuropeBikeId(id);const m=europeBikes.find(x=>x.id===id);if(m){setEuropeModel(m.display_name);setEuropeBikeValue(motorcyclePriceBRL(m,fx));setEuropeIntermediation(motorcycleIntermediationBRL(m,fx));}};

 const dre=useMemo(()=>calculateInternationalDre(qty,fx),[qty,fx]);
 const investment=useMemo(()=>calculateInternationalInvestment(fee,brazilQty,europeQty,brazilBikeValue,europeBikeValue,working,brazilIntermediation,europeIntermediation),[fee,brazilQty,europeQty,brazilBikeValue,europeBikeValue,working,brazilIntermediation,europeIntermediation]);
 const capitalFit=initialCapital<=0||investment.total<=initialCapital;
 const exp=dre.expenses as Record<string,number>; const rev=dre.revenue as Record<string,number>;
 const save=()=>onSave({id:Date.now(),name:`Franquia Internacional 2 em 1 — ${qty} motos Europa`,sourceRoute:"franq-i",capital:investment.total,monthly:dre.netBrl,annual:dre.netBrl*12,details:{qty:brazilQty+europeQty,model:`Brasil: ${brazilModel} • Europa: ${europeModel}`,brazilMotorcycleId:brazilBikeId||undefined,europeMotorcycleId:europeBikeId||undefined,brazilUnitValue:brazilBikeValue,europeUnitValue:europeBikeValue,assets:investment.brazilAssets+investment.europeAssets,franchiseFee:fee,workingCapital:investment.working,intermediation:investment.intermediation,brazilIntermediationPerBike:brazilIntermediation,europeIntermediationPerBike:europeIntermediation,internationalQty:qty,revenueEur:dre.revenueEur,expenseEur:dre.expenseEur,netEur:dre.netEur,margin:dre.margin,fx,plan:"Franquia Internacional 2 em 1",notes:["Motos, preços e intermediação importados do catálogo central administrado.","Preço e intermediação em EUR são convertidos pela cotação informada na simulação.","DRE internacional escalado linearmente a partir da base de 10 motos.","Estrutura combina operação Brasil + Europa."]},updatedAt:new Date().toISOString()});

 return <div className="franchiseModule">
  <section className="calculatorHero intlFranchiseHero"><div><small>LOCAGORA • FRANQUIA INTERNACIONAL 2 EM 1</small><h2>Brasil + Europa em uma única estrutura comercial.</h2><p>Selecione a moto de cada mercado a partir da frota cadastrada no Admin.</p></div><div className="miniMetrics"><div><span>DRE base</span><b>10 motos</b></div><div><span>Moeda operacional</span><b>EUR</b></div><div><span>Estrutura</span><b>2 em 1</b></div></div></section>
  <div className="calcLayout">
   <section className="panel"><div className="sectionHead"><small>INVESTIMENTO</small><h2>Estrutura Brasil + Europa</h2></div><div className="formGrid">
    <label>Taxa de franquia<select value={fee} onChange={e=>setFee(Number(e.target.value)||0)}>{INTERNATIONAL_FRANCHISE.feeOptions.map((f,i)=><option key={f+"-"+i} value={f}>{money(f)}</option>)}</select></label>
    <label>Capital de giro / moto<input type="number" value={working} onChange={e=>setWorking(Number(e.target.value)||0)}/></label>
    <label>Motos Brasil<input type="number" min={0} value={brazilQty} onChange={e=>setBrazilQty(Math.max(0,Math.round(Number(e.target.value)||0)))}/></label>
    <label>Moto Brasil{brazilBikes.length?<select value={brazilBikeId} onChange={e=>chooseBrazil(e.target.value)}>{brazilBikes.map(m=><option key={m.id} value={m.id}>{m.display_name} • {m.currency} {Number(m.base_price).toLocaleString("pt-BR")}</option>)}</select>:<input value={brazilModel} onChange={e=>setBrazilModel(e.target.value)}/>}<small>Somente motos ATIVAS para Brasil.</small></label>
    <label>Preço base Brasil (BRL)<input type="number" value={brazilBikeValue} readOnly={brazilBikes.length>0} onChange={e=>setBrazilBikeValue(Number(e.target.value)||0)}/></label>
    <label>Intermediação Brasil / moto<input type="number" value={brazilIntermediation} readOnly={brazilBikes.length>0} onChange={e=>setBrazilIntermediation(Number(e.target.value)||0)}/></label>
    <label>Motos Europa<input type="number" min={0} value={europeQty} onChange={e=>setEuropeQty(Math.max(0,Math.round(Number(e.target.value)||0)))}/></label>
    <label>Moto Exterior{europeBikes.length?<select value={europeBikeId} onChange={e=>chooseEurope(e.target.value)}>{europeBikes.map(m=><option key={m.id} value={m.id}>{m.display_name} • {m.currency} {Number(m.base_price).toLocaleString("pt-BR")}</option>)}</select>:<input value={europeModel} onChange={e=>setEuropeModel(e.target.value)}/>}<small>Somente motos ATIVAS para Exterior.</small></label>
    <label>Preço base Exterior convertido (BRL)<input type="number" value={europeBikeValue} readOnly={europeBikes.length>0} onChange={e=>setEuropeBikeValue(Number(e.target.value)||0)}/></label>
    <label>Intermediação Exterior / moto (BRL)<input type="number" value={europeIntermediation} readOnly={europeBikes.length>0} onChange={e=>setEuropeIntermediation(Number(e.target.value)||0)}/></label>
   </div><div className="line"><span>Taxa de franquia</span><b>{money(investment.fee)}</b></div><div className="line"><span>Ativos Brasil</span><b>{money(investment.brazilAssets)}</b></div><div className="line"><span>Ativos Europa</span><b>{money(investment.europeAssets)}</b></div><div className="line"><span>Capital de giro</span><b>{money(investment.working)}</b></div><div className="line"><span>Intermediação Brasil</span><b>{money(investment.brazilIntermediation)}</b></div><div className="line"><span>Intermediação Exterior</span><b>{money(investment.europeIntermediation)}</b></div><div className="statusOk"><span>Investimento total</span><b>{money(investment.total)}</b></div>{!capitalFit?<div className="statusWarn">O capital disponível do cliente está abaixo desta configuração.</div>:null}</section>
   <section className="panel resultPanel"><div className="sectionHead"><small>DRE INTERNACIONAL</small><h2>Resultado operacional</h2></div><div className="formGrid"><label>Motos na operação internacional<input type="number" min={1} value={qty} onChange={e=>setQty(Math.max(1,Math.round(Number(e.target.value)||1)))}/></label><label>Câmbio EUR/BRL<input type="number" step=".01" value={fx} onChange={e=>setFx(Number(e.target.value)||6.20)}/></label></div><div className="resultGrid"><div className="highlight"><span>Lucro líquido</span><b>{eur(dre.netEur)}</b><small>{money(dre.netBrl)}</small></div><div><span>Receita</span><b>{eur(dre.revenueEur)}</b><small>{money(dre.revenueBrl)}</small></div><div><span>Despesas</span><b>{eur(dre.expenseEur)}</b><small>{money(dre.expenseBrl)}</small></div><div><span>Margem líquida</span><b>{pct(dre.margin)}</b></div><div><span>Qtd. internacional</span><b>{qty}</b><small>motos</small></div><div><span>Câmbio</span><b>R$ {fx.toFixed(2).replace(".",",")}</b></div></div></section>
  </div>
  <section className="panel"><div className="sectionHead"><small>MODELOS SELECIONADOS</small><h2>Frotas da simulação</h2></div><div className="referenceGrid"><article><div className="assetIcon"><Globe2/></div><small>BRASIL</small><h3>{brazilModel}</h3><p>{money(brazilBikeValue)} / moto • intermediação {money(brazilIntermediation)}</p></article><article><div className="assetIcon"><Globe2/></div><small>EXTERIOR</small><h3>{europeModel}</h3><p>{money(europeBikeValue)} / moto • intermediação {money(europeIntermediation)}</p></article></div></section>
  <section className="panel"><div className="sectionHead"><small>DRE DETALHADO</small><h2>Receitas e despesas internacionais</h2></div><div className="calcLayout"><div><h3>Receitas</h3><div className="line"><span>Locação</span><b>{eur(rev.rental)}</b></div><div className="line"><span>Multa</span><b>{eur(rev.fine)}</b></div><div className="line"><span>Juros</span><b>{eur(rev.interest)}</b></div><div className="line"><span>Caução</span><b>{eur(rev.deposit)}</b></div><div className="statusOk"><span>Total receitas</span><b>{eur(dre.revenueEur)}</b></div></div><div><h3>Despesas</h3>{Object.entries(exp).map(([k,v])=><div className="line" key={k}><span>{k}</span><b>{eur(v)}</b></div>)}<div className="statusWarn"><span>Total despesas</span><b>{eur(dre.expenseEur)}</b></div></div></div></section>
  <section className="nextBar"><button className="secondary" onClick={onBack}><ArrowLeft size={16}/> Voltar às soluções</button><div><small>FRANQUIA INTERNACIONAL</small><b>{eur(dre.netEur)}/mês • {pct(dre.margin)} margem</b></div><button className="primary" onClick={save}><CheckCircle2 size={17}/> {saveLabel||"Adicionar à projeção"} <ArrowRight size={16}/></button></section>
 </div>;
}
