"use client";
import { useEffect, useMemo, useState } from "react";
import { RefreshCw, Save, Store } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
type Rate={reference_key:string;label:string;annual_rate:number;tax_on_gain:number;source_label:string|null;source_url:string|null;active:boolean};type Metric={metric_key:string;label:string;value:number;source_mode:"manual"|"external_json";source_url:string|null;updated_at?:string};
const NETWORK_KEYS=["franchises_sold","stores_brazil","stores_portugal_active","stores_portugal_structuring","stores_spain_active","stores_spain_structuring"];
export default function MarketIntelligenceAdmin(){const supabase=useMemo(()=>createClient(),[]);const [rates,setRates]=useState<Rate[]>([]);const [metrics,setMetrics]=useState<Metric[]>([]);const [status,setStatus]=useState("");async function load(){const [{data:r},{data:m}]=await Promise.all([supabase.from("commercial_capital_reference_rates").select("*").order("sort_order"),supabase.from("commercial_network_metrics").select("*").in("metric_key",NETWORK_KEYS)]);setRates((r||[]) as Rate[]);setMetrics((m||[]) as Metric[])}useEffect(()=>{void load()},[]);
 const metric=(key:string)=>metrics.find(x=>x.metric_key===key);const patchMetric=(key:string,value:number)=>setMetrics(v=>v.map(x=>x.metric_key===key?{...x,value}:x));
 async function save(){setStatus("Salvando...");const {data:{user}}=await supabase.auth.getUser();const now=new Date().toISOString();const a=await supabase.from("commercial_capital_reference_rates").upsert(rates.map(x=>({...x,updated_at:now,updated_by:user?.id||null})),{onConflict:"reference_key"});if(a.error)return setStatus(a.error.message);if(metrics.length){const b=await supabase.from("commercial_network_metrics").upsert(metrics.map(x=>({...x,updated_at:now,updated_by:user?.id||null})),{onConflict:"metric_key"});if(b.error)return setStatus(b.error.message)}setStatus("Inteligência de mercado e indicadores da Rede publicados.");void load()}
 async function autoRefresh(){const row=metric("franchises_sold");if(!row?.source_url)return setStatus("Informe uma URL JSON para franquias vendidas ou mantenha o modo manual.");setStatus("Atualizando fonte automática...");const {data:{session}}=await supabase.auth.getSession();const r=await fetch("/api/network-metrics/refresh",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session?.access_token||""}`},body:JSON.stringify({metricKey:"franchises_sold"})});const d=await r.json();setStatus(d.ok?`Franquias vendidas atualizadas: ${Number(d.value).toLocaleString("pt-BR")}`:(d.message||d.reason||"Falha na atualização."));if(d.ok)void load()}
 const numberInput=(key:string,label:string)=><label>{label}<input type="number" min="0" value={metric(key)?.value??0} onChange={e=>patchMetric(key,Math.max(0,Number(e.target.value)||0))}/></label>;
 const sold=metric("franchises_sold");
 return <details className="adminSection"><summary style={{cursor:"pointer",fontWeight:800,listStyle:"revert"}}><span style={{marginLeft:8}}>V9.3 • Inteligência de mercado — comparativos e rede de franquias</span></summary><div style={{marginTop:18}}><div className="sectionHead"><small>V9.3 • INTELIGÊNCIA DE MERCADO</small><h2>Comparativos financeiros e rede de franquias</h2><p>Referências financeiras e indicadores da presença Locagora ficam centralizados aqui.</p></div><div className="adminPlanGrid">{rates.map((x,i)=><div className="adminGroup" key={x.reference_key}><h3>{x.label}</h3><label>Retorno (% a.a.)<input type="number" step=".01" value={x.annual_rate} onChange={e=>setRates(v=>v.map((z,j)=>j===i?{...z,annual_rate:Number(e.target.value)||0}:z))}/></label><label>IR sobre ganho (%)<input type="number" step=".5" value={x.tax_on_gain} onChange={e=>setRates(v=>v.map((z,j)=>j===i?{...z,tax_on_gain:Number(e.target.value)||0}:z))}/></label><label>Fonte<input value={x.source_label||""} onChange={e=>setRates(v=>v.map((z,j)=>j===i?{...z,source_label:e.target.value}:z))}/></label></div>)}</div>
 <div className="adminGroup" style={{marginTop:16}}><h3><Store size={17}/> Rede Locagora • números editáveis</h3><div className="adminFormGrid">{numberInput("franchises_sold","Franquias vendidas")}{numberInput("stores_brazil","Lojas Brasil")}{numberInput("stores_portugal_active","Portugal • ativas")}{numberInput("stores_portugal_structuring","Portugal • estruturando")}{numberInput("stores_spain_active","Espanha • ativas")}{numberInput("stores_spain_structuring","Espanha • estruturando")}</div>{sold&&<div className="adminFormGrid"><label>Modo • franquias vendidas<select value={sold.source_mode} onChange={e=>setMetrics(v=>v.map(x=>x.metric_key==="franchises_sold"?{...x,source_mode:e.target.value as Metric["source_mode"]}:x))}><option value="manual">Manual pelo ADM</option><option value="external_json">Automático via JSON</option></select></label><label>URL da fonte automática<input placeholder="https://.../metricas.json" value={sold.source_url||""} onChange={e=>setMetrics(v=>v.map(x=>x.metric_key==="franchises_sold"?{...x,source_url:e.target.value}:x))}/></label></div>}<p style={{fontSize:12,color:"#68778e"}}>Portugal e Espanha são exibidos na Rede com total e detalhamento: verde = ativa; cinza = estruturando.</p><button className="secondary" onClick={()=>void autoRefresh()}><RefreshCw/> Atualizar franquias agora</button></div>
 {status&&<div className="adminStatus">{status}</div>}<div style={{marginTop:16}}><button className="primary" onClick={()=>void save()}><Save/> Publicar inteligência de mercado</button></div></div></details>
}
