"use client";
import { FormEvent,useMemo,useState } from "react";
import dynamic from "next/dynamic";
import { AlertTriangle,CheckCircle2,ExternalLink,MapPin,Phone,Search,Sparkles,XCircle } from "lucide-react";
import { NETWORK_POINTS,type NetworkPoint } from "@/lib/network";
import PageHero from "./PageHero";
import GoMarker from "./GoMarker";
import NetworkMetricsSummary from "./NetworkMetricsSummary";
import NetworkContactsDirectory from "./NetworkContactsDirectory";
const LeafletNetworkMap=dynamic(()=>import("./LeafletNetworkMap"),{ssr:false,loading:()=> <div className="mapSkeleton"><div className="skeleton skeletonMap"/></div>});
function googleQuery(p?:NetworkPoint|null){if(!p)return "Locagora Brasil";if(Number.isFinite(p.lat)&&Number.isFinite(p.lng))return `${p.lat},${p.lng}`;return p.address||`${p.city} ${p.state||""} ${p.country}`}
function googleLink(p:NetworkPoint){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(googleQuery(p))}`}
function tone(p:NetworkPoint):"active"|"master"|"future"{return p.future?"future":(p.type==="master"||p.type==="international")?"master":"active"}
type EligibilityResult={city:string;state:string;population:number;eligibility:"eligible"|"ineligible"|"review";reason:string;nearestMaster:null|{name:string;city:string;state:string;distanceKm:number};populationSource:string;distanceMethod:string};
type Suggestion={city:string;state:string};
const people=(n:number)=>new Intl.NumberFormat("pt-BR").format(Number(n)||0);
export default function NetworkPage(){
 const [q,setQ]=useState("");
 const [country,setCountry]=useState("Todos");
 const [selected,setSelected]=useState<NetworkPoint|null>(null);
 const [cityQuery,setCityQuery]=useState("");
 const [checking,setChecking]=useState(false);
 const [eligibility,setEligibility]=useState<EligibilityResult|null>(null);
 const [eligibilityError,setEligibilityError]=useState("");
 const [suggestions,setSuggestions]=useState<Suggestion[]>([]);
 const filtered=useMemo(()=>NETWORK_POINTS.filter(p=>{const ok=country==="Todos"||p.country===country;return ok&&[p.name,p.city,p.state,p.country,p.address,p.status,p.type].join(" ").toLowerCase().includes(q.toLowerCase().trim())}),[q,country]);
 const stats=useMemo(()=>({total:filtered.length,active:filtered.filter(p=>p.status.toLowerCase().includes("opera")).length,territorial:filtered.filter(p=>p.type==="master"||p.type==="international"||p.name.toLowerCase().includes("master")).length}),[filtered]);
 async function evaluateCity(e?:FormEvent){e?.preventDefault();const city=cityQuery.trim();if(!city)return;setChecking(true);setEligibility(null);setEligibilityError("");setSuggestions([]);try{const res=await fetch(`/api/master-eligibility?city=${encodeURIComponent(city)}`,{cache:"no-store"});const data=await res.json();if(!res.ok){setEligibilityError(data.error||"Não foi possível avaliar a cidade.");setSuggestions(Array.isArray(data.suggestions)?data.suggestions:[]);return;}setEligibility(data);}catch{setEligibilityError("Não foi possível consultar a elegibilidade agora.");}finally{setChecking(false)}}
 const eligibilityVisual=eligibility?.eligibility==="eligible"?{title:"PRAÇA ELEGÍVEL PARA MASTER",icon:<CheckCircle2 size={32}/>,bg:"linear-gradient(135deg,#063f2a 0%,#0b6b45 55%,#0fa968 100%)",border:"#31e494"}:eligibility?.eligibility==="review"?{title:"PRAÇA EM ANÁLISE TERRITORIAL",icon:<AlertTriangle size={32}/>,bg:"linear-gradient(135deg,#4c3505 0%,#8a620a 55%,#bd8b12 100%)",border:"#f6c650"}:{title:"PRAÇA INELEGÍVEL NESTE MOMENTO",icon:<XCircle size={32}/>,bg:"linear-gradient(135deg,#491515 0%,#7b2020 55%,#a52c2c 100%)",border:"#ff7878"};
 return <main className="workspace">
  <PageHero kicker="REDE LOCAGORA • PRESENÇA E EXPANSÃO" title="Onde a Locagora está presente." description="Unidades, Masters e territórios em uma visão única, com localização vinculada ao Google Maps e identidade visual própria da rede." actions={<div className="heroStatLine"><span><b>{stats.total}</b> pontos</span><span><b>{stats.active}</b> em operação</span><span><b>{stats.territorial}</b> Masters</span></div>}/>
  <NetworkMetricsSummary/>
  <section className="panel" style={{position:"relative",overflow:"hidden",border:"1px solid rgba(74,222,128,.35)",background:"radial-gradient(circle at top right,rgba(25,195,125,.18),transparent 34%),linear-gradient(135deg,rgba(5,26,48,.98),rgba(7,38,49,.98))"}}>
   <div style={{position:"absolute",right:-45,top:-55,width:180,height:180,borderRadius:"50%",background:"rgba(34,197,94,.12)",filter:"blur(2px)"}}/>
   <div style={{position:"relative",display:"grid",gap:18}}>
    <div style={{display:"flex",alignItems:"center",gap:12,flexWrap:"wrap"}}><span style={{display:"inline-flex",alignItems:"center",gap:7,padding:"7px 12px",borderRadius:999,background:"rgba(34,197,94,.15)",border:"1px solid rgba(74,222,128,.35)",fontWeight:800,fontSize:12,letterSpacing:1}}><Sparkles size={16}/> OPORTUNIDADE DE EXPANSÃO</span><div><h2 style={{margin:"0 0 3px"}}>Sua cidade pode receber uma Master Locagora?</h2><p style={{margin:0,opacity:.82}}>Digite o município e descubra imediatamente o potencial territorial da praça.</p></div></div>
    <form onSubmit={evaluateCity} style={{display:"flex",gap:10,flexWrap:"wrap"}}><label style={{flex:"1 1 320px",display:"flex",alignItems:"center",gap:9,padding:"0 14px",borderRadius:12,background:"white",color:"#10233f"}}><Search size={19}/><input aria-label="Cidade para avaliar Master" value={cityQuery} onChange={e=>setCityQuery(e.target.value)} placeholder="Ex.: Juiz de Fora, MG" style={{width:"100%",border:0,outline:0,padding:"14px 0",fontSize:16,background:"transparent"}}/></label><button className="primary" type="submit" disabled={checking||!cityQuery.trim()} style={{minWidth:190}}>{checking?"Analisando praça...":"Ver elegibilidade"}</button></form>
    <div style={{display:"flex",gap:8,flexWrap:"wrap",fontSize:12,opacity:.8}}><span>✓ Mais de 200 mil habitantes</span><span>•</span><span>✓ Sem Master em até 60 km</span><span>•</span><span>50–60 km = validação territorial</span></div>
    {eligibilityError&&<div className="statusWarn"><b>{eligibilityError}</b>{suggestions.length>0&&<div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:10}}>{suggestions.map(s=><button type="button" className="secondary" key={`${s.city}-${s.state}`} onClick={()=>setCityQuery(`${s.city}, ${s.state}`)}>{s.city} / {s.state}</button>)}</div>}</div>}
    {eligibility&&<div style={{border:`1px solid ${eligibilityVisual.border}`,background:eligibilityVisual.bg,borderRadius:18,padding:20,boxShadow:"0 18px 50px rgba(0,0,0,.22)"}}><div style={{display:"flex",gap:14,alignItems:"center",flexWrap:"wrap"}}><div>{eligibilityVisual.icon}</div><div style={{flex:1}}><small style={{fontWeight:900,letterSpacing:1.2}}>RESULTADO TERRITORIAL</small><h2 style={{margin:"3px 0"}}>{eligibilityVisual.title}</h2><b style={{fontSize:18}}>{eligibility.city} / {eligibility.state}</b></div>{eligibility.eligibility==="eligible"&&<span style={{padding:"9px 14px",borderRadius:999,background:"rgba(255,255,255,.18)",fontWeight:900}}>🔥 POTENCIAL DE EXPANSÃO</span>}</div><p style={{fontSize:16,margin:"15px 0 12px"}}>{eligibility.reason}</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10}}><div style={{padding:12,borderRadius:12,background:"rgba(0,0,0,.18)"}}><span style={{display:"block",opacity:.75,fontSize:12}}>POPULAÇÃO ESTIMADA</span><b style={{fontSize:19}}>{people(eligibility.population)} habitantes</b></div><div style={{padding:12,borderRadius:12,background:"rgba(0,0,0,.18)"}}><span style={{display:"block",opacity:.75,fontSize:12}}>MASTER MAIS PRÓXIMA</span><b style={{fontSize:19}}>{eligibility.nearestMaster?`${eligibility.nearestMaster.distanceKm.toLocaleString("pt-BR")} km`:"Nenhuma cadastrada"}</b>{eligibility.nearestMaster&&<small style={{display:"block",opacity:.78}}>{eligibility.nearestMaster.name}</small>}</div></div><p style={{margin:"12px 0 0",fontSize:11,opacity:.7}}>População: {eligibility.populationSource}. Distância: {eligibility.distanceMethod}.</p></div>}
   </div>
  </section>
  <NetworkContactsDirectory/>
  <section className="panel networkHeroPanel"><div className="networkFilters"><label><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cidade, estado, unidade, tipo ou endereço"/></label><div>{["Todos","Brasil","Portugal","Espanha"].map(c=><button type="button" key={c} className={country===c?"active":""} onClick={()=>{setCountry(c);setSelected(null)}}>{c}</button>)}</div></div></section>
  <section className="networkLayout googleNetworkLayout"><div className="googleMapShell brandedGoogleMap leafletShell"><LeafletNetworkMap points={filtered} selected={selected} onSelect={setSelected}/><div className="googleMapOverlay"><div className="mapOverlayTitle"><GoMarker tone={selected?tone(selected):"active"} small/><div><b>{selected?selected.name:"Rede Locagora"}</b><span>{selected?(selected.address||`${selected.city} • ${selected.country}`):"Clique em um GO para ver a unidade"}</span></div></div>{selected&&<a href={googleLink(selected)} target="_blank" rel="noreferrer"><ExternalLink size={14}/> Abrir no Google Maps</a>}</div><div className="goLegend"><span><GoMarker tone="active" small/> Em operação</span><span><GoMarker tone="master" small/> Master</span><span><GoMarker tone="future" small/> Futura</span></div></div><div className="networkList">{filtered.map(p=><article key={p.id} className={selected?.id===p.id?"selected":""} onClick={()=>setSelected(p)}><div className="networkCardTop"><GoMarker tone={tone(p)}/><div><div className="networkType">{p.future?"FUTURA MASTER":p.type.toUpperCase()}</div><h3>{p.name}</h3></div></div><p><MapPin size={15}/><span>{p.address||`${p.city} • ${p.country}`}</span></p>{p.phone&&p.phone!=="—"&&<p><Phone size={15}/><span>{p.phone}</span></p>}<div className="networkMeta"><b>{p.city}{p.state?` / ${p.state}`:""}</b><span className={`networkStatus ${tone(p)}`}>{p.status}</span></div><a onClick={e=>e.stopPropagation()} target="_blank" rel="noreferrer" href={googleLink(p)}>Google Maps ↗</a></article>)}</div></section>
 </main>
}
