"use client";
import { useEffect, useMemo, useState } from "react";
import dynamic from "next/dynamic";
import { ExternalLink, MapPin, Phone, Search, TrendingUp } from "lucide-react";
import { NETWORK_POINTS, type NetworkPoint } from "@/lib/network";
import { createClient } from "@/lib/supabase/client";
import PageHero from "./PageHero";
import GoMarker from "./GoMarker";
const LeafletNetworkMap = dynamic(()=>import("./LeafletNetworkMap"),{ssr:false,loading:()=> <div className="mapSkeleton"><div className="skeleton skeletonMap"/></div>});
function googleQuery(p?:NetworkPoint|null){if(!p)return "Locagora Brasil";if(Number.isFinite(p.lat)&&Number.isFinite(p.lng))return `${p.lat},${p.lng}`;return p.address||`${p.city} ${p.state||""} ${p.country}`;}
function googleLink(p:NetworkPoint){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(googleQuery(p))}`;}
function tone(p:NetworkPoint):"active"|"master"|"future"{return p.future?"future":(p.type==="master"||p.type==="international")?"master":"active";}
const fmt=(v:number|null)=>v==null||v<=0?"N/D":new Intl.NumberFormat("pt-BR",{maximumFractionDigits:0}).format(v);
export default function NetworkPage(){
 const supabase=useMemo(()=>createClient(),[]);const [q,setQ]=useState("");const [country,setCountry]=useState("Todos");const [selected,setSelected]=useState<NetworkPoint|null>(null);const [metrics,setMetrics]=useState<Record<string,number>>({});
 const filtered=useMemo(()=>NETWORK_POINTS.filter(p=>{const okCountry=country==="Todos"||p.country===country;const hay=[p.name,p.city,p.state,p.country,p.address,p.status,p.type].join(" ").toLowerCase();return okCountry&&hay.includes(q.toLowerCase().trim());}),[q,country]);
 const stats=useMemo(()=>({total:filtered.length,active:filtered.filter(p=>p.status.toLowerCase().includes("opera")).length,territorial:filtered.filter(p=>p.type==="master"||p.type==="international"||p.name.toLowerCase().includes("master")).length}),[filtered]);
 useEffect(()=>{let alive=true;(async()=>{const {data,error}=await supabase.from("commercial_network_metrics").select("metric_key,value").in("metric_key",["franchises_sold","stores_brazil","stores_portugal_active","stores_portugal_structuring","stores_spain_active","stores_spain_structuring"]);if(alive&&!error)setMetrics(Object.fromEntries((data||[]).map(x=>[x.metric_key,Number(x.value)])));})();return()=>{alive=false}},[supabase]);
 const soldLabel=fmt(metrics.franchises_sold??null);const brazil=metrics.stores_brazil??0;const ptActive=metrics.stores_portugal_active??0;const ptStruct=metrics.stores_portugal_structuring??0;const esActive=metrics.stores_spain_active??0;const esStruct=metrics.stores_spain_structuring??0;
 const countryCard=(flag:string,name:string,active:number,structuring:number)=><div style={{minWidth:190,flex:"1 1 190px",padding:"18px 20px",borderRadius:18,background:"rgba(255,255,255,.1)",border:"1px solid rgba(255,255,255,.16)"}}><div style={{fontSize:34,lineHeight:1}}>{flag}</div><div style={{marginTop:8,fontSize:13,fontWeight:900,letterSpacing:".08em"}}>{name.toUpperCase()}</div><strong style={{display:"block",fontSize:34,lineHeight:1.05,marginTop:6}}>{active+structuring>0?active+structuring:"N/D"}</strong><div style={{display:"flex",gap:12,flexWrap:"wrap",marginTop:10,fontSize:12,color:"rgba(255,255,255,.9)"}}><span><i style={{display:"inline-block",width:9,height:9,borderRadius:"50%",background:"#63e64c",marginRight:6}}/>{active} ativa{active===1?"":"s"}</span><span><i style={{display:"inline-block",width:9,height:9,borderRadius:"50%",background:"#b9c2cf",marginRight:6}}/>{structuring} estruturando</span></div></div>;
 return <main className="workspace">
  <PageHero kicker="REDE LOCAGORA • PRESENÇA E EXPANSÃO" title="Onde a Locagora está presente." description="Unidades, Masters e territórios em uma visão única, com localização vinculada ao Google Maps e identidade visual própria da rede." actions={<div className="heroStatLine"><span><b>{stats.total}</b> pontos</span><span><b>{stats.active}</b> em operação</span><span><b>{stats.territorial}</b> Masters</span></div>}/>
  <section className="panel" style={{marginBottom:16,overflow:"hidden",position:"relative",background:"linear-gradient(135deg,#082f63 0%,#0d4fa3 62%,#0a8f6a 140%)",color:"white",border:"none",boxShadow:"0 18px 45px rgba(8,47,99,.18)"}}>
   <div style={{position:"absolute",right:-90,top:-110,width:300,height:300,borderRadius:"50%",background:"rgba(255,255,255,.08)"}}/><div style={{position:"absolute",right:95,bottom:-120,width:230,height:230,borderRadius:"50%",background:"rgba(255,255,255,.05)"}}/>
   <div style={{position:"relative",display:"flex",alignItems:"center",justifyContent:"space-between",gap:24,flexWrap:"wrap",padding:"10px 4px"}}><div style={{display:"flex",alignItems:"center",gap:14}}><span style={{display:"grid",placeItems:"center",width:50,height:50,borderRadius:16,background:"rgba(255,255,255,.14)",border:"1px solid rgba(255,255,255,.18)"}}><TrendingUp size={25}/></span><div><small style={{display:"block",fontSize:11,fontWeight:900,letterSpacing:".12em",color:"#7ef1bd"}}>REDE LOCAGORA • INDICADOR COMERCIAL</small><h2 style={{margin:"6px 0 0",fontSize:"clamp(22px,2.2vw,34px)",lineHeight:1.05}}>Franquias vendidas</h2></div></div><div style={{minWidth:270,textAlign:"right"}}><span style={{display:"block",fontSize:11,fontWeight:900,letterSpacing:".1em",color:"rgba(255,255,255,.72)"}}>TOTAL PUBLICADO</span><strong style={{display:"block",fontSize:"clamp(58px,7vw,92px)",lineHeight:.95,letterSpacing:"-.045em",fontWeight:950,marginTop:8,fontVariantNumeric:"tabular-nums",textShadow:"0 8px 28px rgba(0,0,0,.18)"}}>{soldLabel}</strong><small style={{display:"block",marginTop:10,color:"rgba(255,255,255,.78)",fontSize:13}}>Atualização controlada pelo ADM</small></div></div>
   <div style={{position:"relative",display:"flex",gap:14,flexWrap:"wrap",marginTop:20,paddingTop:18,borderTop:"1px solid rgba(255,255,255,.16)"}}><div style={{minWidth:190,flex:"1 1 190px",padding:"18px 20px",borderRadius:18,background:"rgba(255,255,255,.1)",border:"1px solid rgba(255,255,255,.16)"}}><div style={{fontSize:12,fontWeight:900,letterSpacing:".1em",color:"#7ef1bd"}}>🇧🇷 BRASIL</div><strong style={{display:"block",fontSize:38,lineHeight:1.05,marginTop:8}}>{fmt(brazil)}</strong><small style={{color:"rgba(255,255,255,.78)"}}>lojas • editável pelo ADM</small></div>{countryCard("🇵🇹","Portugal",ptActive,ptStruct)}{countryCard("🇪🇸","Espanha",esActive,esStruct)}</div>
  </section>
  <section className="panel networkHeroPanel"><div className="networkFilters"><label><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cidade, estado, unidade, tipo ou endereço"/></label><div>{["Todos","Brasil","Portugal","Espanha"].map(c=><button type="button" key={c} className={country===c?"active":""} onClick={()=>{setCountry(c);setSelected(null)}}>{c}</button>)}</div></div></section>
  <section className="networkLayout googleNetworkLayout"><div className="googleMapShell brandedGoogleMap leafletShell"><LeafletNetworkMap points={filtered} selected={selected} onSelect={setSelected}/><div className="googleMapOverlay"><div className="mapOverlayTitle"><GoMarker tone={selected?tone(selected):"active"} small/><div><b>{selected?selected.name:"Rede Locagora"}</b><span>{selected?(selected.address||`${selected.city} • ${selected.country}`):"Clique em um GO para ver a unidade"}</span></div></div>{selected&&<a href={googleLink(selected)} target="_blank" rel="noreferrer"><ExternalLink size={14}/> Abrir no Google Maps</a>}</div><div className="goLegend"><span><GoMarker tone="active" small/> Em operação</span><span><GoMarker tone="master" small/> Master</span><span><GoMarker tone="future" small/> Futura</span></div></div>
   <div className="networkList">{filtered.map(p=><article key={p.id} className={selected?.id===p.id?"selected":""} onClick={()=>setSelected(p)}><div className="networkCardTop"><GoMarker tone={tone(p)}/><div><div className="networkType">{p.future?"FUTURA MASTER":p.type.toUpperCase()}</div><h3>{p.name}</h3></div></div><p><MapPin size={15}/><span>{p.address||`${p.city} • ${p.country}`}</span></p>{p.phone&&p.phone!=="—"&&<p><Phone size={15}/><span>{p.phone}</span></p>}<div className="networkMeta"><b>{p.city}{p.state?` / ${p.state}`:""}</b><span className={`networkStatus ${tone(p)}`}>{p.status}</span></div><a onClick={e=>e.stopPropagation()} target="_blank" rel="noreferrer" href={googleLink(p)}>Google Maps ↗</a></article>)}</div>
  </section>
 </main>;
}
