"use client";
import { useEffect, useMemo, useState } from "react";
import { Plus, Save, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { PUBLIC_PRODUCTS } from "@/lib/public-products";

type Status="active"|"paused"|"discontinued";type Row={slug:string;name:string;category:string;description:string;status:Status;is_custom:boolean};
const slugify=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
export default function ProductCatalogAdmin(){const supabase=useMemo(()=>createClient(),[]);const [rows,setRows]=useState<Row[]>([]);const [form,setForm]=useState({name:"",category:"Produto",description:""});const [status,setStatus]=useState("");
 const load=async()=>{const {data}=await supabase.from("commercial_public_product_catalog").select("slug,name,category,description,status,is_custom").order("name");setRows((data||[]) as Row[])};useEffect(()=>{void load()},[]);
 const sync=async()=>{const {data:{user}}=await supabase.auth.getUser();for(const p of PUBLIC_PRODUCTS)await supabase.from("commercial_public_product_catalog").upsert({slug:p.slug,name:p.name,eyebrow:p.eyebrow,category:p.category,description:p.description,audience:p.audience,scope:p.scope,structure:p.structure,profiles:p.profiles,tags:p.tags,status:"active",is_custom:false,updated_by:user?.id||null},{onConflict:"slug",ignoreDuplicates:true});setStatus("Produtos padrão sincronizados.");await load()};
 const add=async()=>{const slug=slugify(form.name);if(!slug)return setStatus("Informe o nome do produto.");const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from("commercial_public_product_catalog").insert({slug,name:form.name.trim(),category:form.category.trim()||"Produto",description:form.description.trim(),eyebrow:"NOVO PRODUTO • LOCAGORA",audience:"Consulte a apresentação e as condições vigentes.",scope:"A definir",structure:"A definir",profiles:["network"],tags:[form.category.trim()||"Produto"],status:"paused",is_custom:true,updated_by:user?.id||null});setStatus(error?error.message:"Produto criado em standby. Adicione a apresentação antes de publicar.");if(!error){setForm({name:"",category:"Produto",description:""});await load()}};
 const patch=async(row:Row,next:Status)=>{const {error}=await supabase.from("commercial_public_product_catalog").update({status:next,updated_at:new Date().toISOString()}).eq("slug",row.slug);setStatus(error?error.message:`${row.name}: ${next==="active"?"ativo":next==="paused"?"standby":"fora de comercialização"}.`);if(!error)await load()};
 const del=async(row:Row)=>{if(!confirm(`Excluir o produto “${row.name}” do catálogo?`))return;const {error}=await supabase.from("commercial_public_product_catalog").delete().eq("slug",row.slug);setStatus(error?error.message:"Produto removido do catálogo.");if(!error)await load()};
 return <details className="adminSection productCatalogAdmin"><summary style={{cursor:"pointer",padding:"4px 0"}}><div className="sectionHead" style={{display:"inline-block",verticalAlign:"middle",marginLeft:8}}><small>CATÁLOGO DE PRODUTOS</small><h2 style={{marginBottom:4}}>Adicionar, pausar ou retirar de comercialização</h2><p>Clique na seta para expandir ou recolher o catálogo.</p></div></summary><div style={{marginTop:18}}><div className="productCatalogAdd"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nome do novo produto"/><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Categoria"/><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Descrição curta"/><button className="primary" onClick={()=>void add()}><Plus/> Adicionar produto</button><button className="secondary" onClick={()=>void sync()}><Save/> Sincronizar produtos atuais</button></div><div className="productCatalogList">{rows.map(r=><article key={r.slug}><div><b>{r.name}</b><span>{r.category} • {r.slug}</span></div><div><select value={r.status} onChange={e=>void patch(r,e.target.value as Status)}><option value="active">Ativo</option><option value="paused">Standby</option><option value="discontinued">Fora de comercialização</option></select><button className="iconDanger" onClick={()=>void del(r)} title="Excluir produto"><Trash2/></button></div></article>)}</div>{status&&<div className="adminStatus">{status}</div>}</div></details>;
}