"use client";
import Image from "next/image";
import { useEffect, useMemo, useState, type ChangeEvent } from "react";
import { ArrowDown, ArrowUp, ImageUp, Plus, RotateCcw, Save, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { PUBLIC_PRODUCTS } from "@/lib/public-products";

type Status="active"|"paused"|"discontinued";
type Row={slug:string;name:string;category:string;description:string;status:Status;is_custom:boolean;thumbnail_url:string|null;thumbnail_path:string|null;thumbnail_position_x:number;thumbnail_position_y:number;display_order:number};
const slugify=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const fallback=(slug:string)=>PUBLIC_PRODUCTS.find(p=>p.slug===slug)?.slides[0]||null;
const accept=new Set(["image/jpeg","image/png","image/webp"]);

export default function ProductCatalogAdmin(){
 const supabase=useMemo(()=>createClient(),[]);const [rows,setRows]=useState<Row[]>([]);const [form,setForm]=useState({name:"",category:"Produto",description:""});const [status,setStatus]=useState("");const [busy,setBusy]=useState<string|null>(null);
 const load=async()=>{const {data}=await supabase.from("commercial_public_product_catalog").select("slug,name,category,description,status,is_custom,thumbnail_url,thumbnail_path,thumbnail_position_x,thumbnail_position_y,display_order").order("display_order").order("name");setRows((data||[]) as Row[])};
 const ensureDefaults=async()=>{const {data:{user}}=await supabase.auth.getUser();for(const [index,p] of PUBLIC_PRODUCTS.entries())await supabase.from("commercial_public_product_catalog").upsert({slug:p.slug,name:p.name,eyebrow:p.eyebrow,category:p.category,description:p.description,audience:p.audience,scope:p.scope,structure:p.structure,profiles:p.profiles,tags:p.tags,status:"active",is_custom:false,display_order:index+1,updated_by:user?.id||null},{onConflict:"slug",ignoreDuplicates:true});await load()};
 useEffect(()=>{void ensureDefaults()},[]);
 const sync=async()=>{setStatus("Sincronizando portfólio...");await ensureDefaults();setStatus("Projetos padrão sincronizados.")};
 const add=async()=>{const slug=slugify(form.name);if(!slug)return setStatus("Informe o nome do produto.");const {data:{user}}=await supabase.auth.getUser();const order=(rows.at(-1)?.display_order||rows.length)+1;const {error}=await supabase.from("commercial_public_product_catalog").insert({slug,name:form.name.trim(),category:form.category.trim()||"Produto",description:form.description.trim(),eyebrow:"NOVO PRODUTO • LOCAGORA",audience:"Consulte a apresentação e as condições vigentes.",scope:"A definir",structure:"A definir",profiles:["network"],tags:[form.category.trim()||"Produto"],status:"paused",is_custom:true,display_order:order,updated_by:user?.id||null});setStatus(error?error.message:"Produto criado em standby.");if(!error){setForm({name:"",category:"Produto",description:""});await load()}};
 const patchStatus=async(row:Row,next:Status)=>{const {error}=await supabase.from("commercial_public_product_catalog").update({status:next,updated_at:new Date().toISOString()}).eq("slug",row.slug);setStatus(error?error.message:`${row.name}: status atualizado.`);if(!error)await load()};
 const localPatch=(slug:string,change:Partial<Row>)=>setRows(v=>v.map(x=>x.slug===slug?{...x,...change}:x));
 const savePosition=async(row:Row)=>{setBusy(row.slug);const {error}=await supabase.from("commercial_public_product_catalog").update({thumbnail_position_x:row.thumbnail_position_x,thumbnail_position_y:row.thumbnail_position_y,updated_at:new Date().toISOString()}).eq("slug",row.slug);setBusy(null);setStatus(error?error.message:`${row.name}: enquadramento salvo.`)};
 const uploadThumb=async(row:Row,e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;if(!accept.has(file.type))return setStatus("Use JPG, PNG ou WebP.");if(file.size>5*1024*1024)return setStatus("A imagem deve ter no máximo 5 MB.");setBusy(row.slug);try{const safe=file.name.normalize("NFD").replace(/[^a-zA-Z0-9._-]+/g,"-");const path=`${row.slug}/${Date.now()}-${safe}`;const {error:up}=await supabase.storage.from("commercial-portfolio-thumbnails").upload(path,file,{contentType:file.type,upsert:false});if(up)throw up;const {data:url}=supabase.storage.from("commercial-portfolio-thumbnails").getPublicUrl(path);const {error:db}=await supabase.from("commercial_public_product_catalog").update({thumbnail_url:url.publicUrl,thumbnail_path:path,thumbnail_position_x:50,thumbnail_position_y:50,updated_at:new Date().toISOString()}).eq("slug",row.slug);if(db){await supabase.storage.from("commercial-portfolio-thumbnails").remove([path]);throw db}if(row.thumbnail_path)await supabase.storage.from("commercial-portfolio-thumbnails").remove([row.thumbnail_path]);setStatus(`${row.name}: miniatura publicada.`);await load()}catch(err){setStatus(err instanceof Error?err.message:"Falha ao enviar a miniatura.")}finally{setBusy(null)}};
 const restore=async(row:Row)=>{setBusy(row.slug);const old=row.thumbnail_path;const {error}=await supabase.from("commercial_public_product_catalog").update({thumbnail_url:null,thumbnail_path:null,thumbnail_position_x:50,thumbnail_position_y:50,updated_at:new Date().toISOString()}).eq("slug",row.slug);if(!error&&old)await supabase.storage.from("commercial-portfolio-thumbnails").remove([old]);setBusy(null);setStatus(error?error.message:`${row.name}: imagem padrão restaurada.`);if(!error)await load()};
 const move=async(index:number,dir:-1|1)=>{const other=index+dir;if(other<0||other>=rows.length)return;const a=rows[index],b=rows[other];setBusy(a.slug);const [{error:e1},{error:e2}]=await Promise.all([supabase.from("commercial_public_product_catalog").update({display_order:b.display_order}).eq("slug",a.slug),supabase.from("commercial_public_product_catalog").update({display_order:a.display_order}).eq("slug",b.slug)]);setBusy(null);setStatus(e1?.message||e2?.message||"Ordem do portfólio atualizada.");await load()};
 const del=async(row:Row)=>{if(!confirm(`Excluir o produto “${row.name}” do catálogo?`))return;const {error}=await supabase.from("commercial_public_product_catalog").delete().eq("slug",row.slug);if(!error&&row.thumbnail_path)await supabase.storage.from("commercial-portfolio-thumbnails").remove([row.thumbnail_path]);setStatus(error?error.message:"Produto removido do catálogo.");if(!error)await load()};
 return <details className="adminSection productCatalogAdmin"><summary style={{cursor:"pointer",padding:"4px 0"}}><div className="sectionHead" style={{display:"inline-block",verticalAlign:"middle",marginLeft:8}}><small>PORTFÓLIO • PROJETOS</small><h2 style={{marginBottom:4}}>Miniaturas, enquadramento, status e ordem</h2><p>Clique na seta para gerenciar os cards públicos sem alterar código.</p></div></summary><div style={{marginTop:18}}>
  <div className="productCatalogAdd"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nome do novo produto"/><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Categoria"/><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Descrição curta"/><button className="primary" onClick={()=>void add()}><Plus/> Adicionar produto</button><button className="secondary" onClick={()=>void sync()}><Save/> Sincronizar atuais</button></div>
  <div style={{display:"grid",gap:16,marginTop:18}}>{rows.map((r,index)=>{const src=r.thumbnail_url||fallback(r.slug);return <article key={r.slug} style={{display:"grid",gridTemplateColumns:"minmax(260px,360px) 1fr",gap:20,padding:18,border:"1px solid #dbe5f2",borderRadius:18,background:"#fff"}}>
   <div><div style={{position:"relative",aspectRatio:"16/9",overflow:"hidden",borderRadius:14,background:"#071f4b"}}>{src?<Image src={src} alt={`Miniatura ${r.name}`} fill sizes="360px" style={{objectFit:"cover",objectPosition:`${r.thumbnail_position_x}% ${r.thumbnail_position_y}%`}} unoptimized={src.startsWith("http")}/>:<div style={{display:"grid",placeItems:"center",height:"100%",color:"white",fontWeight:900}}>LOCAGORA</div>}</div><small style={{display:"block",marginTop:8}}>Pré-visualização 16:9 • {r.thumbnail_url?"personalizada":"imagem padrão"}</small></div>
   <div style={{display:"grid",gap:12}}><div><b style={{fontSize:18}}>{r.name}</b><span style={{display:"block",fontSize:12,color:"#64748b"}}>{r.category} • {r.slug}</span></div>
    <div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}><label className="secondary" style={{cursor:"pointer",display:"inline-flex",alignItems:"center",gap:7}}><ImageUp size={16}/> {busy===r.slug?"Processando...":"Trocar miniatura"}<input type="file" accept="image/jpeg,image/png,image/webp" hidden disabled={busy===r.slug} onChange={e=>void uploadThumb(r,e)}/></label><button className="secondary" disabled={!r.thumbnail_url||busy===r.slug} onClick={()=>void restore(r)}><RotateCcw size={16}/> Restaurar padrão</button></div>
    <label style={{display:"grid",gap:4}}><small>Enquadramento horizontal • {r.thumbnail_position_x}%</small><input type="range" min="0" max="100" value={r.thumbnail_position_x} onChange={e=>localPatch(r.slug,{thumbnail_position_x:Number(e.target.value)})}/></label>
    <label style={{display:"grid",gap:4}}><small>Enquadramento vertical • {r.thumbnail_position_y}%</small><input type="range" min="0" max="100" value={r.thumbnail_position_y} onChange={e=>localPatch(r.slug,{thumbnail_position_y:Number(e.target.value)})}/></label>
    <div style={{display:"flex",gap:8,flexWrap:"wrap",alignItems:"center"}}><button className="primary" disabled={busy===r.slug} onClick={()=>void savePosition(r)}><Save size={16}/> Salvar enquadramento</button><select value={r.status} onChange={e=>void patchStatus(r,e.target.value as Status)}><option value="active">Publicado</option><option value="paused">Standby</option><option value="discontinued">Fora de comercialização</option></select><button className="secondary" disabled={index===0||busy!==null} onClick={()=>void move(index,-1)} title="Subir"><ArrowUp size={16}/></button><button className="secondary" disabled={index===rows.length-1||busy!==null} onClick={()=>void move(index,1)} title="Descer"><ArrowDown size={16}/></button>{r.is_custom&&<button className="iconDanger" onClick={()=>void del(r)} title="Excluir produto"><Trash2/></button>}</div>
   </div></article>})}</div>{status&&<div className="adminStatus" style={{marginTop:14}}>{status}</div>}
 </div></details>;
}
