"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowUp, CirclePause, CirclePlay, FileImage, Plus, RefreshCcw, Save, Trash2, Upload, XCircle } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { PUBLIC_PRODUCTS } from "@/lib/public-products";

type Status="draft"|"published"|"paused"|"archived";
type Presentation={id:string;product_slug:string;title:string;status:Status;updated_at:string};
type Page={id:string;presentation_id:string;position:number;role:"cover"|"page"|"back_cover";public_url:string|null;storage_path:string|null};
const labels:Record<Status,string>={draft:"Rascunho",published:"Publicada",paused:"Pausada",archived:"Arquivada"};

export default function PublicPresentationAdmin(){
 const supabase=useMemo(()=>createClient(),[]);
 const [presentations,setPresentations]=useState<Presentation[]>([]); const [pages,setPages]=useState<Page[]>([]); const [productOptions,setProductOptions]=useState<{slug:string;name:string}[]>(PUBLIC_PRODUCTS.map(p=>({slug:p.slug,name:p.name})));
 const [selected,setSelected]=useState(""); const [status,setStatus]=useState(""); const [busy,setBusy]=useState(false);
 const current=presentations.find(p=>p.product_slug===selected); const currentPages=pages.filter(p=>p.presentation_id===current?.id).sort((a,b)=>a.position-b.position);
 const load=async()=>{setBusy(true);setStatus("");try{const {data:p,error:pe}=await supabase.from("commercial_public_presentations").select("id,product_slug,title,status,updated_at").order("title");if(pe)throw pe;const list=(p||[]) as Presentation[];setPresentations(list);if(!selected&&list[0])setSelected(list[0].product_slug);const {data:pg,error:pge}=await supabase.from("commercial_public_presentation_pages").select("id,presentation_id,position,role,public_url,storage_path").order("position");if(pge)throw pge;setPages((pg||[]) as Page[]);const {data:catalog}=await supabase.from("commercial_public_product_catalog").select("slug,name").order("name");if(catalog?.length){const merged=new Map(PUBLIC_PRODUCTS.map(x=>[x.slug,{slug:x.slug,name:x.name}]));for(const row of catalog as {slug:string;name:string}[])merged.set(row.slug,row);setProductOptions([...merged.values()]);if(!selected&&!list[0])setSelected([...merged.values()][0]?.slug||"");}else if(!selected&&!list[0])setSelected(PUBLIC_PRODUCTS[0]?.slug||"");}catch(e){const msg=e instanceof Error?e.message:"";setStatus(msg||"Não foi possível carregar apresentações. Verifique se a migration V8.5/V8.7 foi aplicada no Supabase.");}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);
 const ensure=async()=>{const product=productOptions.find(p=>p.slug===selected);if(!product)return;setBusy(true);try{const {data:user}=await supabase.auth.getUser();const {data:p,error}=await supabase.from("commercial_public_presentations").insert({product_slug:product.slug,title:product.name,status:"draft",updated_by:user.user?.id||null}).select("id").single();if(error)throw error;const slots=Array.from({length:10},(_,i)=>({presentation_id:p.id,position:i+1,role:i===0?"cover":i===9?"back_cover":"page",updated_by:user.user?.id||null}));const {error:se}=await supabase.from("commercial_public_presentation_pages").insert(slots);if(se)throw se;setStatus("Apresentação criada com 10 páginas.");await load();}catch(e){setStatus(e instanceof Error?e.message:"Falha ao criar apresentação.");}finally{setBusy(false)}};
 const changeStatus=async(next:Status)=>{if(!current)return;setBusy(true);const {error}=await supabase.from("commercial_public_presentations").update({status:next,updated_at:new Date().toISOString()}).eq("id",current.id);setStatus(error?error.message:`Status alterado para ${labels[next]}.`);await load();setBusy(false)};
 const upload=async(page:Page,file:File)=>{setBusy(true);setStatus("");try{const safe=file.name.normalize("NFD").replace(/[^a-zA-Z0-9._-]+/g,"-");const path=`${selected}/${page.id}/${Date.now()}-${safe}`;const {error:up}=await supabase.storage.from("commercial-public-presentations").upload(path,file,{contentType:file.type,upsert:false});if(up)throw up;const {data:url}=supabase.storage.from("commercial-public-presentations").getPublicUrl(path);const {data:user}=await supabase.auth.getUser();const {error:db}=await supabase.from("commercial_public_presentation_pages").update({storage_path:path,public_url:url.publicUrl,updated_at:new Date().toISOString(),updated_by:user.user?.id||null}).eq("id",page.id);if(db)throw db;setStatus(`Página ${page.position} substituída.`);await load();}catch(e){setStatus(e instanceof Error?e.message:"Falha ao enviar página.");}finally{setBusy(false)}};
 const addPage=async()=>{if(!current)return;setBusy(true);try{const sorted=currentPages;const back=sorted.find(p=>p.role==="back_cover");const insertAt=back?.position||sorted.length+1;for(const p of [...sorted].filter(p=>p.position>=insertAt).sort((a,b)=>b.position-a.position)){await supabase.from("commercial_public_presentation_pages").update({position:p.position+1}).eq("id",p.id);}const {error}=await supabase.from("commercial_public_presentation_pages").insert({presentation_id:current.id,position:insertAt,role:"page"});if(error)throw error;setStatus("Nova página adicionada antes da contracapa.");await load();}catch(e){setStatus(e instanceof Error?e.message:"Falha ao adicionar página.");}finally{setBusy(false)}};
 const delPage=async(page:Page)=>{if(currentPages.length<=2)return setStatus("A apresentação precisa manter ao menos capa e contracapa.");if(!confirm(`Excluir a página ${page.position}? Esta ação remove o slot da apresentação.`))return;setBusy(true);try{const {error}=await supabase.from("commercial_public_presentation_pages").delete().eq("id",page.id);if(error)throw error;const remain=currentPages.filter(p=>p.id!==page.id).sort((a,b)=>a.position-b.position);for(let i=0;i<remain.length;i++)await supabase.from("commercial_public_presentation_pages").update({position:i+1,role:i===0?"cover":i===remain.length-1?"back_cover":"page"}).eq("id",remain[i].id);setStatus("Página excluída.");await load();}catch(e){setStatus(e instanceof Error?e.message:"Falha ao excluir página.");}finally{setBusy(false)}};
 const move=async(page:Page,delta:number)=>{const target=currentPages.find(p=>p.position===page.position+delta);if(!target)return;setBusy(true);try{await supabase.from("commercial_public_presentation_pages").update({position:9999}).eq("id",page.id);await supabase.from("commercial_public_presentation_pages").update({position:page.position}).eq("id",target.id);await supabase.from("commercial_public_presentation_pages").update({position:target.position}).eq("id",page.id);const ordered=[...currentPages];const a=ordered.findIndex(p=>p.id===page.id),b=ordered.findIndex(p=>p.id===target.id);[ordered[a],ordered[b]]=[ordered[b],ordered[a]];for(let i=0;i<ordered.length;i++)await supabase.from("commercial_public_presentation_pages").update({role:i===0?"cover":i===ordered.length-1?"back_cover":"page"}).eq("id",ordered[i].id);await load();}catch(e){setStatus(e instanceof Error?e.message:"Falha ao reordenar.");}finally{setBusy(false)}};
 const deletePresentation=async()=>{if(!current||!confirm(`Excluir a apresentação “${current.title}”? As páginas serão removidas do catálogo.`))return;setBusy(true);const {error}=await supabase.from("commercial_public_presentations").delete().eq("id",current.id);setStatus(error?error.message:"Apresentação excluída.");setSelected("");await load();setBusy(false)};
 return <section className="adminSection publicPresentationAdmin"><div className="sectionHead"><small>APRESENTAÇÕES PÚBLICAS</small><h2>Gerenciar páginas de cada produto</h2><p>O padrão é 10 páginas (capa + 8 páginas + contracapa). Você pode adicionar, excluir, reordenar ou substituir páginas. Só apresentações publicadas aparecem no portal.</p></div>
  <div className="presentationAdminToolbar"><select value={selected} onChange={e=>setSelected(e.target.value)}>{productOptions.map(p=><option value={p.slug} key={p.slug}>{p.name}</option>)}</select><button className="secondary" onClick={()=>void load()} disabled={busy}><RefreshCcw size={16}/> Atualizar</button>{!current&&<button className="primary" onClick={()=>void ensure()} disabled={busy}><Plus size={16}/> Criar apresentação</button>}</div>
  {current&&<><div className="presentationStatusBar"><div><b>{current.title}</b><span>{currentPages.length} páginas • {labels[current.status]}</span></div><div><select value={current.status} onChange={e=>void changeStatus(e.target.value as Status)} disabled={busy}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select>{current.status==="published"?<button className="standbyButton" onClick={()=>void changeStatus("paused")} disabled={busy}><CirclePause size={16}/> Colocar em standby</button>:<button className="publishButton" onClick={()=>void changeStatus("published")} disabled={busy}><CirclePlay size={16}/> Publicar / Reativar</button>}<button className="secondary" onClick={()=>void addPage()} disabled={busy}><Plus size={16}/> Adicionar página</button><button className="dangerButton" onClick={()=>void deletePresentation()} disabled={busy}><Trash2 size={16}/> Excluir apresentação</button></div></div>
  <div className="presentationPageGrid">{currentPages.map((page,i)=><article className="presentationPageCard" key={page.id}><div className="presentationThumb">{page.public_url?<img src={page.public_url} alt={`Página ${page.position}`}/>:<div><FileImage/><span>Página sem arte</span></div>}<span>{page.role==="cover"?"CAPA":page.role==="back_cover"?"CONTRACAPA":`PÁGINA ${String(page.position-1).padStart(2,"0")}`}</span></div><div className="presentationPageActions"><label className="uploadMini"><Upload size={15}/> Substituir<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(page,f);e.currentTarget.value=""}} disabled={busy}/></label><button onClick={()=>void move(page,-1)} disabled={busy||i===0} title="Mover para esquerda"><ArrowUp size={15}/></button><button onClick={()=>void move(page,1)} disabled={busy||i===currentPages.length-1} title="Mover para direita"><ArrowDown size={15}/></button><button className="iconDanger" onClick={()=>void delPage(page)} disabled={busy}><XCircle size={16}/></button></div></article>)}</div></>}
  {status&&<div className="adminStatus"><Save size={16}/>{status}</div>}
 </section>;
}
