"use client";
import { useEffect,useMemo,useState } from "react";
import { Archive,CheckCircle2,Inbox,RefreshCcw } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
type Feedback={id:string;name:string|null;email:string|null;category:string;message:string;page_path:string|null;status:"new"|"reviewed"|"archived";created_at:string};
const label:Record<Feedback["status"],string>={new:"Nova",reviewed:"Revisada",archived:"Arquivada"};
export default function PublicFeedbackAdmin(){const supabase=useMemo(()=>createClient(),[]);const [rows,setRows]=useState<Feedback[]>([]);const [filter,setFilter]=useState<"all"|Feedback["status"]>("new");const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
 async function load(){setBusy(true);setStatus("");let q=supabase.from("commercial_public_feedback").select("id,name,email,category,message,page_path,status,created_at").order("created_at",{ascending:false}).limit(200);if(filter!=="all")q=q.eq("status",filter);const {data,error}=await q;if(error)setStatus(error.message);else setRows((data||[]) as Feedback[]);setBusy(false)}useEffect(()=>{void load()},[filter]);
 async function setState(row:Feedback,next:Feedback["status"]){setBusy(true);const {error}=await supabase.from("commercial_public_feedback").update({status:next}).eq("id",row.id);setStatus(error?error.message:`Mensagem marcada como ${label[next].toLowerCase()}.`);await load();setBusy(false)}
 return <details className="adminSection"><summary style={{cursor:"pointer",padding:"4px 0"}}><div className="sectionHead" style={{display:"inline-block",verticalAlign:"middle",marginLeft:8}}><small>VOZ DO PÚBLICO</small><h2 style={{marginBottom:4}}>Sugestões e opiniões recebidas</h2><p>Clique na seta para abrir a caixa de mensagens enviadas pelo acesso público.</p></div></summary><div style={{marginTop:18}}><div style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{(["new","reviewed","archived","all"] as const).map(x=><button key={x} type="button" className={filter===x?"primary":"secondary"} onClick={()=>setFilter(x)}>{x==="all"?"Todas":x==="new"?"Novas":x==="reviewed"?"Revisadas":"Arquivadas"}</button>)}</div><button className="secondary" type="button" disabled={busy} onClick={()=>void load()}><RefreshCcw size={16}/> Atualizar</button></div>{status&&<div className="adminStatus" style={{marginTop:12}}>{status}</div>}<div style={{display:"grid",gap:12,marginTop:16}}>{rows.length?rows.map(r=><article key={r.id} style={{padding:16,border:"1px solid #dbe5f1",borderRadius:16,background:r.status==="new"?"#f7fbff":"#fff"}}><div style={{display:"flex",justifyContent:"space-between",gap:14,flexWrap:"wrap"}}><div><b>{r.name||"Visitante"}</b><div style={{fontSize:12,color:"#64748b"}}>{r.email||"Sem e-mail"} • {r.category} • {new Date(r.created_at).toLocaleString("pt-BR")}</div>{r.page_path&&<small style={{display:"block",marginTop:4,color:"#64748b"}}>Origem: {r.page_path}</small>}</div><span style={{fontSize:12,fontWeight:800}}>{label[r.status]}</span></div><p style={{whiteSpace:"pre-wrap",lineHeight:1.5}}>{r.message}</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{r.status!=="reviewed"&&<button className="secondary" type="button" disabled={busy} onClick={()=>void setState(r,"reviewed")}><CheckCircle2 size={15}/> Marcar revisada</button>}{r.status!=="archived"&&<button className="secondary" type="button" disabled={busy} onClick={()=>void setState(r,"archived")}><Archive size={15}/> Arquivar</button>}{r.status!=="new"&&<button className="secondary" type="button" disabled={busy} onClick={()=>void setState(r,"new")}><Inbox size={15}/> Voltar para novas</button>}</div></article>):<div style={{padding:18,border:"1px dashed #cbd5e1",borderRadius:16,color:"#64748b"}}>Nenhuma mensagem nesta categoria.</div>}</div></div></details>}
