"use client";
import Image from "next/image";
import { ChevronLeft, ChevronRight, Expand, ExternalLink, FileText, Minimize2, Repeat2, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import type { PublicProduct } from "@/lib/public-products";

type DbPresentation={id:string;status:"draft"|"published"|"paused"|"archived"};
type DbPage={id:string;position:number;role:string;public_url:string|null};
type InternalPresentation={id:string;title:string;presentation_url:string;presentation_type:string;is_default:boolean;sort_order:number};
const financialSlugAlias:Record<string,string>={euroloc:"locinvest-europa",cotas:"cotas-internacionais",exclusive:"exclusive-brasil","franquia-internacional":"exclusive-internacional","franquia-2x1":"exclusive-2x1"};

export default function PublicProductGallery({product}:{product:PublicProduct}){
  const [index,setIndex]=useState(0); const [pdf,setPdf]=useState<string|undefined>(); const [presentation,setPresentation]=useState<DbPresentation|null|undefined>(undefined); const [pages,setPages]=useState<DbPage[]>([]); const [fullscreen,setFullscreen]=useState(false); const [internal,setInternal]=useState<InternalPresentation[]>([]); const [selectedInternal,setSelectedInternal]=useState<InternalPresentation|null>(null); const [switcher,setSwitcher]=useState(false); const [isCollaborator,setIsCollaborator]=useState(false); const stageRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{(async()=>{try{const supabase=createClient();const financialSlug=financialSlugAlias[product.slug]||product.slug;const [{data:doc},{data:p},{data:{user}},{data:internalRows}]=await Promise.all([supabase.from("commercial_documents").select("public_url").eq("slug",product.slug).eq("active",true).maybeSingle(),supabase.from("commercial_public_presentations").select("id,status").eq("product_slug",product.slug).maybeSingle(),supabase.auth.getUser(),supabase.from("commercial_product_presentations").select("id,title,presentation_url,presentation_type,is_default,sort_order").eq("product_slug",financialSlug).eq("active",true).order("sort_order")]);if(doc?.public_url)setPdf(doc.public_url);if(user){setIsCollaborator(true);const list=(internalRows||[]) as InternalPresentation[];setInternal(list);const stored=localStorage.getItem("locagora_selected_presentation_id");setSelectedInternal(list.find(x=>x.id===stored)||list.find(x=>x.is_default)||null)}if(p){setPresentation(p as DbPresentation);if(p.status==="published"){const {data:pg}=await supabase.from("commercial_public_presentation_pages").select("id,position,role,public_url").eq("presentation_id",p.id).order("position");setPages((pg||[]) as DbPage[]);}else setPages([]);}else setPresentation(null);}catch{setPresentation(null);}})();},[product.slug]);
  const legacy=Array.from({length:10},(_,i)=>({id:`legacy-${i}`,position:i+1,role:i===0?"cover":i===9?"back_cover":"page",public_url:product.slides[i]||null}));
  const slides=presentation===null?legacy:pages; const count=slides.length; const prev=()=>count&&setIndex(i=>(i-1+count)%count); const next=()=>count&&setIndex(i=>(i+1)%count);
  useEffect(()=>{if(index>=count)setIndex(0)},[count,index]);
  useEffect(()=>{const on=()=>setFullscreen(Boolean(document.fullscreenElement));document.addEventListener("fullscreenchange",on);return()=>document.removeEventListener("fullscreenchange",on)},[]);
  const toggleFullscreen=async()=>{if(!stageRef.current)return;if(!document.fullscreenElement)await stageRef.current.requestFullscreen();else await document.exitFullscreen();};
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(!fullscreen)return;if(e.key==="ArrowLeft")prev();if(e.key==="ArrowRight")next();};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)});
  const chooseInternal=async(item:InternalPresentation)=>{setSelectedInternal(item);setSwitcher(false);const sessionId=localStorage.getItem("locagora_commercial_session_id");if(sessionId)await createClient().from("commercial_sessions").update({selected_presentation_id:item.id,updated_at:new Date().toISOString()}).eq("id",sessionId);localStorage.setItem("locagora_selected_presentation_id",item.id)};
  if(presentation&&presentation.status!=="published"&&!selectedInternal)return <section className="publicProductViewer publicPresentationUnavailable"><FileText/><h3>Apresentação temporariamente indisponível</h3><p>Este material está {presentation.status==="paused"?"pausado":"fora de publicação"} no momento.</p></section>;
  if(!count&&!selectedInternal)return <section className="publicProductViewer publicPresentationUnavailable"><FileText/><h3>Apresentação em atualização</h3><p>O conteúdo deste produto está sendo preparado.</p></section>;
  const slide=slides[index];
  return <section className="publicProductViewer">
    {selectedInternal?<div className="internalPresentationFrame"><iframe src={selectedInternal.presentation_url} title={selectedInternal.title} allowFullScreen/><div className="internalPresentationLabel"><span><b>{selectedInternal.title}</b><small>Apresentação selecionada para este atendimento</small></span></div></div>:<><div className="publicSlideStage" ref={stageRef}>
      <button onClick={prev} className="slideArrow left" aria-label="Anterior"><ChevronLeft/></button>
      {slide?.public_url?<Image src={slide.public_url} alt={`${product.name} - página ${index+1}`} width={1920} height={1080} className="publicSlide" priority={index===0} unoptimized={slide.public_url.startsWith("http")}/>:<div className="publicSlidePlaceholder"><small>{index===0?"CAPA":index===count-1?"CONTRACAPA":`PÁGINA ${String(index).padStart(2,"0")}`}</small><h3>{product.name}</h3><p>Conteúdo desta página em atualização.</p></div>}
      <button onClick={next} className="slideArrow right" aria-label="Próxima"><ChevronRight/></button>
      <div className="presentationOverlay"><span>Página {index+1} de {count}</span><button onClick={()=>void toggleFullscreen()}>{fullscreen?<Minimize2 size={17}/>:<Expand size={17}/>} {fullscreen?"Sair da tela cheia":"Tela cheia"}</button></div>
    </div><div className="slideDots slidePageNav">{slides.map((_,i)=><button key={_.id} onClick={()=>setIndex(i)} className={i===index?"active":""} aria-label={`Ir para página ${i+1}`}>{String(i+1).padStart(2,"0")}</button>)}</div></>}
    <div className="publicMaterialActions"><span><FileText size={17}/> {selectedInternal?selectedInternal.title:`Apresentação • ${index+1} de ${count}`}</span><div className="materialActionButtons">{isCollaborator&&internal.length>0&&<button type="button" className="switchPresentationBtn" onClick={()=>setSwitcher(true)}><Repeat2 size={16}/> Trocar apresentação</button>}{pdf&&<a href={pdf} target="_blank" rel="noreferrer"><ExternalLink size={16}/> Ver PDF publicado</a>}</div></div>
    {switcher&&<div className="presentationSwitcherBackdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setSwitcher(false)}}><section className="presentationSwitcher" role="dialog" aria-modal="true"><div className="presentationSwitcherHead"><div><small>MATERIAL DO ATENDIMENTO</small><h3>Trocar apresentação</h3><p>Escolha o material que ficará associado a esta sessão comercial.</p></div><button onClick={()=>setSwitcher(false)} aria-label="Fechar"><X/></button></div><div className="presentationSwitcherList">{internal.map(item=><button key={item.id} className={selectedInternal?.id===item.id?"selected":""} onClick={()=>void chooseInternal(item)}><span><b>{item.title}</b><small>{item.presentation_type}{item.is_default?" • padrão":""}</small></span>{selectedInternal?.id===item.id&&<strong>EM USO</strong>}</button>)}</div></section></div>}
  </section>
}
