"use client";
import { useEffect,useMemo,useState } from "react";
import { ChevronDown,Eye,EyeOff,ImagePlus,Save,Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Banner={id:string;title:string;subtitle:string;city:string;state:string|null;country:string;image_url:string;storage_path:string|null;target_url:string|null;display_order:number;active:boolean};
type Lead={id:string;name:string;mobile:string;email:string|null;city:string;state:string|null;has_cnh_a:boolean|null;works_with_delivery:boolean|null;preferred_contact:string;status:string;created_at:string};
const inputStyle={border:"1px solid #ccd8dd",borderRadius:10,padding:"11px 12px",font:"inherit",width:"100%"} as const;

export default function RentalBannerAdmin(){
 const supabase=useMemo(()=>createClient(),[]);const [banners,setBanners]=useState<Banner[]>([]);const [leads,setLeads]=useState<Lead[]>([]);const [status,setStatus]=useState("");const [uploading,setUploading]=useState(false);const [file,setFile]=useState<File|null>(null);const [form,setForm]=useState({title:"Aluguel de motos Locagora",subtitle:"",city:"",state:"",country:"Brasil",targetUrl:"/aluguel#cadastro-motoboy",displayOrder:"0"});
 const load=async()=>{const [{data:b},{data:l}]=await Promise.all([supabase.from("commercial_rental_banners").select("*").order("display_order").order("created_at"),supabase.from("commercial_rental_leads").select("id,name,mobile,email,city,state,has_cnh_a,works_with_delivery,preferred_contact,status,created_at").order("created_at",{ascending:false}).limit(100)]);setBanners((b||[]) as Banner[]);setLeads((l||[]) as Lead[])};useEffect(()=>{void load()},[]);
 const add=async()=>{if(!file||!form.city.trim())return setStatus("Selecione a imagem e informe a cidade.");if(!["image/jpeg","image/png","image/webp"].includes(file.type))return setStatus("Use JPG, PNG ou WebP.");setUploading(true);setStatus("");try{const ext=(file.name.split(".").pop()||"webp").toLowerCase();const path=`${form.city.toLowerCase().replace(/[^a-z0-9]+/g,"-")}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error:upErr}=await supabase.storage.from("commercial-rental-banners").upload(path,file,{contentType:file.type,upsert:false});if(upErr)throw upErr;const {data:url}=supabase.storage.from("commercial-rental-banners").getPublicUrl(path);const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from("commercial_rental_banners").insert({title:form.title.trim(),subtitle:form.subtitle.trim(),city:form.city.trim(),state:form.state.trim()||null,country:form.country.trim()||"Brasil",image_url:url.publicUrl,storage_path:path,target_url:form.targetUrl.trim()||null,display_order:Number(form.displayOrder)||0,active:true,created_by:user?.id||null,updated_by:user?.id||null});if(error){await supabase.storage.from("commercial-rental-banners").remove([path]);throw error}setFile(null);setForm({title:"Aluguel de motos Locagora",subtitle:"",city:"",state:"",country:"Brasil",targetUrl:"/aluguel#cadastro-motoboy",displayOrder:String(banners.length)});setStatus("Banner publicado.");await load()}catch(e){setStatus(e instanceof Error?e.message:"Falha ao publicar banner.")}finally{setUploading(false)}};
 const patch=async(id:string,changes:Partial<Banner>)=>{const {error}=await supabase.from("commercial_rental_banners").update({...changes,updated_at:new Date().toISOString()}).eq("id",id);setStatus(error?error.message:"Banner atualizado.");if(!error)await load()};
 const remove=async(b:Banner)=>{if(!confirm(`Excluir o banner de ${b.city}?`))return;const {error}=await supabase.from("commercial_rental_banners").delete().eq("id",b.id);if(!error&&b.storage_path)await supabase.storage.from("commercial-rental-banners").remove([b.storage_path]);setStatus(error?error.message:"Banner removido.");if(!error)await load()};
 const leadStatus=async(id:string,next:string)=>{const {error}=await supabase.from("commercial_rental_leads").update({status:next,updated_at:new Date().toISOString()}).eq("id",id);setStatus(error?error.message:"Lead atualizado.");if(!error)await load()};
 return <details className="adminSection"><summary style={{cursor:"pointer",padding:"4px 0"}}><div className="sectionHead" style={{display:"inline-block",verticalAlign:"middle",marginLeft:8}}><small>ALUGUEL DE MOTOS</small><h2 style={{marginBottom:4}}>Banners por cidade e contatos de motoboys</h2><p>Cadastre campanhas rotativas e acompanhe interessados.</p></div><ChevronDown size={18}/></summary><div style={{marginTop:20,display:"grid",gap:24}}>
   <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12,alignItems:"end"}}>
    <label>Título<input style={inputStyle} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Cidade<input style={inputStyle} value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>UF / Estado<input style={inputStyle} value={form.state} onChange={e=>setForm({...form,state:e.target.value})}/></label><label>País<input style={inputStyle} value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></label><label>Ordem<input style={inputStyle} type="number" value={form.displayOrder} onChange={e=>setForm({...form,displayOrder:e.target.value})}/></label><label style={{gridColumn:"1/-1"}}>Texto complementar<input style={inputStyle} value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})} placeholder="Ex.: Motos disponíveis para entregadores da região."/></label><label style={{gridColumn:"1/-1"}}>Destino ao clicar<input style={inputStyle} value={form.targetUrl} onChange={e=>setForm({...form,targetUrl:e.target.value})}/></label><label style={{gridColumn:"1/-1"}}>Banner 16:9 • JPG, PNG ou WebP • até 8 MB<input style={inputStyle} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary" onClick={()=>void add()} disabled={uploading||!file}><ImagePlus size={17}/>{uploading?"Publicando...":"Adicionar banner"}</button>
   </section>
   <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:14}}>{banners.map(b=><article key={b.id} style={{border:"1px solid #dce5e9",borderRadius:16,overflow:"hidden",background:"#fff"}}><img src={b.image_url} alt={b.title} style={{display:"block",width:"100%",aspectRatio:"16/9",objectFit:"cover"}}/><div style={{padding:14,display:"grid",gap:10}}><div><b>{b.city}{b.state?` • ${b.state}`:""}</b><div style={{fontSize:13,color:"#6a7880"}}>{b.title}</div></div><div style={{display:"flex",gap:8,alignItems:"center"}}><button className="secondary" onClick={()=>void patch(b.id,{active:!b.active})}>{b.active?<><Eye size={15}/> Ativo</>:<><EyeOff size={15}/> Oculto</>}</button><input style={{...inputStyle,width:82}} type="number" value={b.display_order} onChange={e=>void patch(b.id,{display_order:Number(e.target.value)||0})}/><button className="iconDanger" onClick={()=>void remove(b)} title="Excluir"><Trash2 size={16}/></button></div></div></article>)}</div>
   <section><div className="sectionHead"><small>INTERESSADOS</small><h3 style={{margin:"4px 0"}}>Cadastros recebidos</h3><p>Primeira etapa do futuro fluxo de locação digital.</p></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:820}}><thead><tr><th style={{textAlign:"left",padding:10}}>Data</th><th style={{textAlign:"left",padding:10}}>Nome</th><th style={{textAlign:"left",padding:10}}>Cidade</th><th style={{textAlign:"left",padding:10}}>Contato</th><th style={{textAlign:"left",padding:10}}>CNH A</th><th style={{textAlign:"left",padding:10}}>Delivery</th><th style={{textAlign:"left",padding:10}}>Status</th></tr></thead><tbody>{leads.map(l=><tr key={l.id} style={{borderTop:"1px solid #e5ecef"}}><td style={{padding:10}}>{new Date(l.created_at).toLocaleDateString("pt-BR")}</td><td style={{padding:10}}><b>{l.name}</b></td><td style={{padding:10}}>{l.city}{l.state?`/${l.state}`:""}</td><td style={{padding:10}}><a href={`https://wa.me/55${l.mobile.replace(/\D/g,"")}`} target="_blank" rel="noreferrer">{l.mobile}</a>{l.email&&<div style={{fontSize:12}}>{l.email}</div>}</td><td style={{padding:10}}>{l.has_cnh_a?"Sim":"Não informado"}</td><td style={{padding:10}}>{l.works_with_delivery?"Sim":"Não informado"}</td><td style={{padding:10}}><select style={inputStyle} value={l.status} onChange={e=>void leadStatus(l.id,e.target.value)}><option value="new">Novo</option><option value="contacted">Contatado</option><option value="qualified">Qualificado</option><option value="converted">Convertido</option><option value="archived">Arquivado</option></select></td></tr>)}</tbody></table>{leads.length===0&&<div style={{padding:18,color:"#6a7880"}}>Nenhum cadastro recebido ainda.</div>}</div></section>
   {status&&<div className="adminStatus"><Save size={16}/>{status}</div>}
 </div></details>
}
