"use client";
import { useEffect, useMemo, useState } from "react";
import { Plus, RefreshCcw, Save, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { PUBLIC_PRODUCTS } from "@/lib/public-products";

type Row={id:string;title:string;franchisee_name:string|null;location:string|null;youtube_url:string;youtube_video_id:string;placement:string[];sort_order:number;active:boolean;featured:boolean};
const videoId=(url:string)=>{try{const u=new URL(url.trim());if(u.hostname.includes("youtu.be"))return u.pathname.replace("/","").slice(0,20);if(u.hostname.includes("youtube.com")){const v=u.searchParams.get("v");if(v)return v;const p=u.pathname.split("/").filter(Boolean);const ix=p.findIndex(x=>["embed","shorts","live"].includes(x));if(ix>=0&&p[ix+1])return p[ix+1];}}catch{}return ""};

export default function TestimonialAdmin(){
 const supabase=useMemo(()=>createClient(),[]);const [rows,setRows]=useState<Row[]>([]);const [form,setForm]=useState({title:"",franchisee_name:"",location:"",youtube_url:"",placement:["history"],active:true,featured:false});const [status,setStatus]=useState("");
 const load=async()=>{const {data,error}=await supabase.from("commercial_public_testimonials").select("*").order("sort_order");setRows((data||[]) as Row[]);if(error)setStatus(error.message)};useEffect(()=>{void load()},[]);
 const togglePlacement=(p:string)=>setForm(v=>({...v,placement:v.placement.includes(p)?v.placement.filter(x=>x!==p):[...v.placement,p]}));
 const add=async()=>{const id=videoId(form.youtube_url);if(!id)return setStatus("Cole um link válido do YouTube.");if(!form.title.trim())return setStatus("Informe um título.");const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from("commercial_public_testimonials").insert({...form,title:form.title.trim(),franchisee_name:form.franchisee_name.trim()||null,location:form.location.trim()||null,youtube_video_id:id,sort_order:(rows.at(-1)?.sort_order||0)+10,updated_by:user?.id||null});setStatus(error?error.message:"Depoimento publicado.");if(!error){setForm({title:"",franchisee_name:"",location:"",youtube_url:"",placement:["history"],active:true,featured:false});await load()}};
 const patch=async(row:Row,change:Partial<Row>)=>{const {error}=await supabase.from("commercial_public_testimonials").update({...change,updated_at:new Date().toISOString()}).eq("id",row.id);setStatus(error?error.message:"Depoimento atualizado.");if(!error)await load()};
 const del=async(row:Row)=>{if(!confirm(`Excluir o vídeo “${row.title}”?`))return;const {error}=await supabase.from("commercial_public_testimonials").delete().eq("id",row.id);setStatus(error?error.message:"Depoimento excluído.");if(!error)await load()};
 const placements=["history",...PUBLIC_PRODUCTS.map(p=>p.slug)];
 return <details className="adminSection testimonialAdmin"><summary style={{cursor:"pointer",padding:"4px 0"}}><div className="sectionHead" style={{display:"inline-block",verticalAlign:"middle",marginLeft:8}}><small>DEPOIMENTOS • YOUTUBE</small><h2 style={{marginBottom:4}}>Escolha os vídeos que aparecem no portal</h2><p>Clique na seta para expandir ou recolher a gestão de depoimentos.</p></div></summary><div style={{marginTop:18}}><div className="testimonialAdminForm"><label>Título<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Franqueado<input value={form.franchisee_name} onChange={e=>setForm({...form,franchisee_name:e.target.value})}/></label><label>Cidade / país<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label className="wide">Link do YouTube<input value={form.youtube_url} onChange={e=>setForm({...form,youtube_url:e.target.value})} placeholder="https://www.youtube.com/watch?v=..."/></label><div className="wide testimonialPlacements">{placements.map(p=><button type="button" key={p} className={form.placement.includes(p)?"active":""} onClick={()=>togglePlacement(p)}>{p==="history"?"História":PUBLIC_PRODUCTS.find(x=>x.slug===p)?.name||p}</button>)}</div><label className="inline"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Ativo</label><label className="inline"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Destaque</label><button className="primary" onClick={()=>void add()}><Plus/> Adicionar vídeo</button></div><div className="testimonialAdminList">{rows.map(r=><article key={r.id}><div><b>{r.title}</b><span>{r.franchisee_name||"Sem nome"}{r.location?` • ${r.location}`:""}</span><small>{r.placement.join(" • ")}</small></div><div><button className="secondary" onClick={()=>void patch(r,{active:!r.active})}>{r.active?"Colocar em standby":"Reativar"}</button><button className="secondary" onClick={()=>void patch(r,{featured:!r.featured})}>{r.featured?"Remover destaque":"Destacar"}</button><button className="iconDanger" onClick={()=>void del(r)}><Trash2/></button></div></article>)}</div>{status&&<div className="adminStatus"><Save size={16}/>{status}</div>}<button className="secondary" onClick={()=>void load()}><RefreshCcw size={16}/> Atualizar vídeos</button></div></details>
}