"use client";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Activity, CheckCircle2, RefreshCcw, ShieldCheck, Trash2, UserPlus, Users } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Member={profileId:string;userId:string;email:string;name:string;role:"admin"|"gestor"|"sdr"|"closer";active:boolean;teamName:string;accessCreated:boolean;createdAt:string;updatedAt:string};
type Audit={id:number;action:string;entity_type:string;entity_id?:string|null;actor_email?:string|null;metadata:Record<string,unknown>;created_at:string};
type Health={aiConfigured:boolean;proposalModelConfigured:boolean;supabaseConfigured:boolean;serviceRoleConfigured?:boolean;resendConfigured?:boolean;leadFromEmailConfigured?:boolean;appUrlConfigured:boolean;generatedAt:string};
const roleLabels={admin:"Administrador",gestor:"Gestor",sdr:"SDR",closer:"Closer"};
const Summary=({kicker,title,description}:{kicker:string;title:string;description:string})=><summary style={{cursor:"pointer",padding:"4px 0"}}><div className="sectionHead" style={{display:"inline-block",verticalAlign:"middle",marginLeft:8}}><small>{kicker}</small><h2 style={{marginBottom:4}}>{title}</h2><p>{description}</p></div></summary>;

export default function V8GovernanceAdmin(){
 const supabase=useMemo(()=>createClient(),[]);
 const [members,setMembers]=useState<Member[]>([]);const [audits,setAudits]=useState<Audit[]>([]);const [health,setHealth]=useState<Health|null>(null);const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
 const [newName,setNewName]=useState("");const [newEmail,setNewEmail]=useState("");const [newTeam,setNewTeam]=useState("");const [newRole,setNewRole]=useState<Member["role"]>("closer");
 const token=async()=>{const {data}=await supabase.auth.getSession();return data.session?.access_token||""};
 const load=async()=>{setBusy(true);setStatus("");try{const t=await token();const [accessRes,healthRes,auditRes]=await Promise.all([fetch("/api/admin/access",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"}),fetch("/api/system/status",{cache:"no-store"}),supabase.from("commercial_audit_log").select("id,action,entity_type,entity_id,actor_email,metadata,created_at").order("created_at",{ascending:false}).limit(30)]);const access=await accessRes.json();if(!accessRes.ok)throw new Error(access.message||access.reason||"Falha ao carregar acessos.");setMembers(access.members||[]);setHealth(await healthRes.json());if(!auditRes.error)setAudits((auditRes.data||[]) as Audit[]);}catch(e){setStatus(e instanceof Error?e.message:"Falha ao carregar governança.");}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);
 const createMember=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setStatus("Cadastrando colaborador...");try{const t=await token();const res=await fetch("/api/admin/access",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({action:"create",name:newName,email:newEmail,teamName:newTeam,role:newRole})});const data=await res.json();if(!res.ok)throw new Error(data.message||data.reason||"Falha ao cadastrar colaborador.");setNewName("");setNewEmail("");setNewTeam("");setNewRole("closer");await load();setStatus(data.message||"Colaborador cadastrado com sucesso.");}catch(e){setStatus(e instanceof Error?e.message:"Falha ao cadastrar colaborador.");}finally{setBusy(false)}};
 const updateMember=async(member:Member)=>{setBusy(true);setStatus("Salvando usuário...");try{const t=await token();const res=await fetch("/api/admin/access",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({profileId:member.profileId,userId:member.userId,role:member.role,teamName:member.teamName})});const data=await res.json();if(!res.ok)throw new Error(data.message||data.reason||"Falha ao atualizar acesso.");await load();setStatus("Usuário atualizado com sucesso.");}catch(e){setStatus(e instanceof Error?e.message:"Falha ao atualizar acesso.");}finally{setBusy(false)}};
 const patch=(id:string,change:Partial<Member>)=>setMembers(xs=>xs.map(x=>x.profileId===id?{...x,...change}:x));
 const revoke=async(member:Member)=>{if(!confirm(`Bloquear o acesso de ${member.email}?`))return;setBusy(true);setStatus("Bloqueando acesso...");try{const t=await token();const res=await fetch("/api/admin/access",{method:"DELETE",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({profileId:member.profileId,userId:member.userId})});const data=await res.json();if(!res.ok)throw new Error(data.message||data.reason||"Falha ao bloquear acesso.");await load();setStatus("Acesso bloqueado.");}catch(e){setStatus(e instanceof Error?e.message:"Falha ao bloquear acesso.");}finally{setBusy(false)}};
 const checks=health?[{label:"Supabase público",ok:health.supabaseConfigured},{label:"Chave servidor",ok:Boolean(health.serviceRoleConfigured)},{label:"Resend",ok:Boolean(health.resendConfigured)},{label:"Remetente comercial",ok:Boolean(health.leadFromEmailConfigured)},{label:"URL da aplicação",ok:health.appUrlConfigured}]:[];
 return <>
  <details className="adminSection v8Governance"><Summary kicker="V8 • GOVERNANÇA E ACESSOS" title="Usuários, permissões e equipes" description="Clique na seta para expandir ou recolher a gestão de acessos."/><div style={{marginTop:18}}>
   <form onSubmit={createMember} style={{display:"grid",gridTemplateColumns:"minmax(220px,1.2fr) minmax(260px,1.4fr) minmax(150px,.7fr) minmax(220px,1fr) auto",gap:12,alignItems:"end",padding:18,border:"1px solid #dbe5f2",borderRadius:16,background:"#f8fbff",marginBottom:18}}>
    <label style={{display:"grid",gap:6}}><small>Nome</small><input required minLength={2} value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Nome do colaborador"/></label>
    <label style={{display:"grid",gap:6}}><small>E-mail corporativo</small><input required type="email" value={newEmail} onChange={e=>setNewEmail(e.target.value)} placeholder="nome@locgrupo.com.br"/></label>
    <label style={{display:"grid",gap:6}}><small>Posição</small><select value={newRole} onChange={e=>setNewRole(e.target.value as Member["role"])}>{Object.entries(roleLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
    <label style={{display:"grid",gap:6}}><small>Equipe</small><input value={newTeam} onChange={e=>setNewTeam(e.target.value)} placeholder="Ex.: Equipe Minas"/></label>
    <button className="primary" disabled={busy} type="submit"><UserPlus size={17}/>{busy?"Salvando...":"Cadastrar colaborador"}</button>
   </form>
   <div className="v8AccessComposer"><div><b>{members.length} usuários cadastrados</b><small style={{display:"block"}}>Pré-cadastros também aparecem nesta lista, mesmo antes do primeiro login.</small></div><button className="secondary" onClick={()=>void load()} disabled={busy}><RefreshCcw size={17}/> Atualizar lista</button></div>
   {status&&<div className="adminStatus"><CheckCircle2/>{status}</div>}
   <div className="v8MemberList">{members.length?members.map(m=><article key={m.profileId} className={!m.active?"inactive":""} style={{alignItems:"stretch",gap:12}}>
     <div style={{minWidth:240}}><Users size={17}/><span><b>{m.name||m.email}</b><small>{m.email}</small><small>{m.active?(m.accessCreated?"Ativo • acesso criado":"Cadastrado • aguardando 1º acesso"):"Bloqueado"}</small></span></div>
     <label style={{display:"grid",gap:6,minWidth:170}}><small>Permissão</small><select value={m.role} onChange={e=>patch(m.profileId,{role:e.target.value as Member["role"]})}>{Object.entries(roleLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
     <label style={{display:"grid",gap:6,minWidth:190,flex:1}}><small>Equipe</small><input value={m.teamName||""} onChange={e=>patch(m.profileId,{teamName:e.target.value})} placeholder="Ex.: Equipe Minas, Closer BH"/></label>
     <div style={{display:"flex",gap:8,alignItems:"end"}}><button className="primary" disabled={busy} onClick={()=>void updateMember(m)}>{m.active?"Salvar":"Reativar"}</button>{m.active&&<button className="v8Danger" onClick={()=>void revoke(m)} title="Bloquear acesso"><Trash2 size={16}/> Bloquear</button>}</div>
   </article>):<p>Nenhum usuário cadastrado.</p>}</div>
  </div></details>
  <details className="adminSection"><Summary kicker="V8 • SAÚDE DO SISTEMA" title="Produção e integrações" description="Clique na seta para expandir ou recolher o diagnóstico técnico."/><div className="v8HealthGrid" style={{marginTop:18}}>{checks.map(c=><article key={c.label} className={c.ok?"ok":"warn"}><ShieldCheck/><span>{c.label}</span><b>{c.ok?"Configurado":"Pendente"}</b></article>)}</div></details>
  <details className="adminSection"><Summary kicker="V8 • AUDITORIA" title="Alterações críticas recentes" description="Clique na seta para expandir ou recolher o histórico de alterações."/><div className="v8AuditList" style={{marginTop:18}}>{audits.length?audits.map(a=><article key={a.id}><Activity size={16}/><div><b>{a.action.replaceAll("_"," ")}</b><span>{a.actor_email||"sistema"} • {new Date(a.created_at).toLocaleString("pt-BR")}</span><small>{a.entity_type}{a.entity_id?` • ${a.entity_id}`:""}</small></div></article>):<p>Nenhum evento de auditoria registrado ainda.</p>}</div></details>
 </>;
}