"use client";
import type { ComparisonSnapshot, Simulation } from "@/lib/types";

type Benchmark = {brand_name?:string;initial_investment_min?:number|null;initial_investment_max?:number|null;franchise_fee_min?:number|null;franchise_fee_max?:number|null;installation_capital_min?:number|null;installation_capital_max?:number|null;working_capital_min?:number|null;working_capital_max?:number|null;payback_months_min?:number|null;payback_months_max?:number|null;average_monthly_revenue?:number|null;average_profit_margin_pct?:number|null;abf_operations?:number|null;source_name?:string|null;source_reference_date?:string|null};
const currency=(value?:number|null)=>value==null?"N/D":new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(value);
const moneyRange=(a?:number|null,b?:number|null)=>a==null&&b==null?"N/D":a!=null&&b!=null&&a!==b?`${currency(a)} a ${currency(b)}`:a!=null&&b==null?`A partir de ${currency(a)}`:currency(a??b);
const numberRange=(a?:number|null,b?:number|null,suffix="")=>a==null&&b==null?"N/D":a!=null&&b!=null&&a!==b?`${a} a ${b}${suffix}`:`${a??b}${suffix}`;
const percent=(v?:number|null)=>v==null?"N/D":`${v.toLocaleString("pt-BR",{maximumFractionDigits:1})}%`;
export function getFranchiseComparison(snapshot:ComparisonSnapshot|null|undefined){const data=snapshot?.assumptionsSnapshot as Record<string,unknown>|undefined;if(data?.comparisonKind!=="franchise")return null;const competitors=Array.isArray(data.competitors)?data.competitors as Benchmark[]:data.competitor?[data.competitor as Benchmark]:[];return competitors.length?{competitors:competitors.slice(0,4),loc:(data.locagora||{}) as Benchmark}:null;}
export async function exportFranchiseComparisonPdf(snapshot:ComparisonSnapshot,simulation:Simulation,clientName="Cliente"){
 const comparison=getFranchiseComparison(snapshot);if(!comparison)throw new Error("Selecione pelo menos uma franquia antes de exportar.");
 const {jsPDF}=await import("jspdf");const pdf=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});const W=297;const margin=13;const columns=[{name:"LocAgora",row:comparison.loc},...comparison.competitors.map(row=>({name:row.brand_name||"Franquia",row}))];const colW=(W-margin*2-57)/columns.length;const start=margin+57;
 pdf.setFillColor(5,25,64);pdf.rect(0,0,W,39,"F");pdf.setTextColor(255,255,255);pdf.setFont("helvetica","bold");pdf.setFontSize(18);pdf.text("LOCAGORA | COMPARATIVO DE FRANQUIAS",margin,17);pdf.setFontSize(10);pdf.setFont("helvetica","normal");pdf.text(`Cliente: ${clientName}  |  Capital da simulacao: ${currency(simulation.capital)}  |  ${new Date().toLocaleDateString("pt-BR")}`,margin,29);
 const indicators:{name:string;value:(r:Benchmark)=>string}[]=[{name:"Investimento total",value:r=>moneyRange(r.initial_investment_min,r.initial_investment_max)},{name:"Taxa de franquia",value:r=>moneyRange(r.franchise_fee_min,r.franchise_fee_max)},{name:"Instalacao / estrutura",value:r=>moneyRange(r.installation_capital_min,r.installation_capital_max)},{name:"Capital de giro",value:r=>moneyRange(r.working_capital_min,r.working_capital_max)},{name:"Payback",value:r=>numberRange(r.payback_months_min,r.payback_months_max," meses")},{name:"Faturamento mensal",value:r=>currency(r.average_monthly_revenue)},{name:"Margem divulgada",value:r=>percent(r.average_profit_margin_pct)},{name:"Operacoes ABF",value:r=>r.abf_operations==null?"N/D":r.abf_operations.toLocaleString("pt-BR")}];
 pdf.setFontSize(9);pdf.setFont("helvetica","bold");pdf.setTextColor(255,255,255);pdf.setFillColor(13,72,115);pdf.rect(margin,46,W-2*margin,15,"F");pdf.text("Indicador",margin+3,55);columns.forEach((c,i)=>pdf.text(pdf.splitTextToSize(c.name,colW-3).slice(0,2),start+i*colW+2,52));
 indicators.forEach((indicator,index)=>{const y=61+index*13;pdf.setFillColor(index%2?245:233,index%2?248:242,index%2?252:248);pdf.rect(margin,y,W-2*margin,13,"F");pdf.setTextColor(17,35,58);pdf.setFont("helvetica","bold");pdf.setFontSize(9);pdf.text(indicator.name,margin+3,y+8);pdf.setFont("helvetica","normal");pdf.setFontSize(8);columns.forEach((c,i)=>pdf.text(pdf.splitTextToSize(indicator.value(c.row),colW-4).slice(0,2),start+i*colW+2,y+6))});
 pdf.setTextColor(35,51,70);pdf.setFontSize(8);pdf.text("Fontes por franquia:",margin,175);comparison.competitors.forEach((r,i)=>pdf.text(pdf.splitTextToSize(`${r.brand_name||"Franquia"}: ${r.source_name||"Fonte cadastrada"}${r.source_reference_date?` (${r.source_reference_date})`:""}`,W-2*margin).slice(0,1),margin,181+i*4));pdf.setFontSize(7);pdf.text("N/D = dado nao divulgado ou nao verificado. Dados das redes podem variar por formato, regiao e data.",margin,201);pdf.text("Valores LocAgora sao projecoes da simulacao, nao garantias. Compare conceitos financeiros equivalentes antes de decidir.",margin,205);
 pdf.save(`Comparativo_LocAgora_${clientName.replace(/[^a-zA-Z0-9_-]+/g,"_")}.pdf`);
}
