"use client";
import type {ComparisonSnapshot,Simulation} from "@/lib/types";
type Benchmark={brand_name?:string;initial_investment_min?:number|null;initial_investment_max?:number|null;franchise_fee_min?:number|null;franchise_fee_max?:number|null;installation_capital_min?:number|null;installation_capital_max?:number|null;working_capital_min?:number|null;working_capital_max?:number|null;payback_months_min?:number|null;payback_months_max?:number|null;average_monthly_revenue?:number|null;average_profit_margin_pct?:number|null;abf_operations?:number|null;source_name?:string|null;source_reference_date?:string|null;monthly_fixed_costs?:number|null;contribution_margin_pct?:number|null;logo_url?:string|null};
const currency=(v?:number|null)=>v==null?"N/D":new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(v);
const moneyRange=(a?:number|null,b?:number|null)=>a==null&&b==null?"N/D":a!=null&&b!=null&&a!==b?`${currency(a)} a ${currency(b)}`:a!=null&&b==null?`A partir de ${currency(a)}`:currency(a??b);
const range=(a?:number|null,b?:number|null,s="")=>a==null&&b==null?"N/D":a!=null&&b!=null&&a!==b?`${Number(a.toFixed(1))} a ${Number(b.toFixed(1))}${s}`:`${Number((a??b)!.toFixed(1))}${s}`;
const pct=(v?:number|null)=>v==null?"N/D":`${v.toLocaleString("pt-BR",{maximumFractionDigits:1})}%`;
const breakEven=(r:Benchmark)=>r.monthly_fixed_costs!=null&&r.monthly_fixed_costs>=0&&r.contribution_margin_pct!=null&&r.contribution_margin_pct>0&&r.contribution_margin_pct<=100?currency(r.monthly_fixed_costs/(r.contribution_margin_pct/100)):"N/D";
const adequacy=(r:Benchmark,capital:number)=>r.initial_investment_min==null&&r.initial_investment_max==null?"N/D":r.initial_investment_min!=null&&capital<r.initial_investment_min?`Faltam ${currency(r.initial_investment_min-capital)}`:r.initial_investment_max!=null&&capital>=r.initial_investment_max?"Faixa coberta":r.initial_investment_min!=null&&capital>=r.initial_investment_min?"Dentro da faixa":"Confirmar com a rede";
export function getFranchiseComparison(snapshot:ComparisonSnapshot|null|undefined){const data=snapshot?.assumptionsSnapshot as Record<string,unknown>|undefined;if(data?.comparisonKind!=="franchise")return null;const competitors=Array.isArray(data.competitors)?data.competitors as Benchmark[]:data.competitor?[data.competitor as Benchmark]:[];return competitors.length?{competitors:competitors.slice(0,4),loc:(data.locagora||{}) as Benchmark}:null;}
export async function exportFranchiseComparisonPdf(snapshot:ComparisonSnapshot,simulation:Simulation,clientName="Cliente"){
 const comparison=getFranchiseComparison(snapshot);if(!comparison)throw new Error("Selecione pelo menos uma franquia antes de exportar.");const {jsPDF}=await import("jspdf");const pdf=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});const W=297,margin=13;const columns=[{name:"LocAgora",row:comparison.loc},...comparison.competitors.map(row=>({name:row.brand_name||"Franquia",row}))];const colW=(W-margin*2-57)/columns.length,start=margin+57;
 pdf.setFillColor(5,25,64);pdf.rect(0,0,W,39,"F");pdf.setTextColor(255,255,255);pdf.setFont("helvetica","bold");pdf.setFontSize(17);pdf.text("LOCAGORA | COMPARATIVO DE FRANQUIAS",margin,16);pdf.setFontSize(9);pdf.setFont("helvetica","normal");pdf.text(pdf.splitTextToSize(`Cliente: ${clientName} | Capital igual de referencia: ${currency(simulation.capital)} | ${new Date().toLocaleDateString("pt-BR")}`,W-2*margin).slice(0,2),margin,27);
 const indicators:{name:string;value:(r:Benchmark,i:number)=>string}[]=[{name:"Capital de referencia",value:()=>currency(simulation.capital)},{name:"Adequacao do capital",value:(r,i)=>i===0?"Capital simulado":adequacy(r,simulation.capital)},{name:"Investimento divulgado",value:r=>moneyRange(r.initial_investment_min,r.initial_investment_max)},{name:"Taxa de franquia",value:r=>moneyRange(r.franchise_fee_min,r.franchise_fee_max)},{name:"Instalacao / estrutura",value:r=>moneyRange(r.installation_capital_min,r.installation_capital_max)},{name:"Capital de giro",value:r=>moneyRange(r.working_capital_min,r.working_capital_max)},{name:"Payback",value:r=>range(r.payback_months_min,r.payback_months_max," meses")},{name:"Faturamento mensal",value:r=>currency(r.average_monthly_revenue)},{name:"Margem divulgada",value:r=>pct(r.average_profit_margin_pct)},{name:"Break-even operacional",value:r=>breakEven(r)},{name:"Operacoes ABF",value:r=>r.abf_operations==null?"N/D":r.abf_operations.toLocaleString("pt-BR")}];
 pdf.setFontSize(9);pdf.setFont("helvetica","bold");pdf.setTextColor(255,255,255);pdf.setFillColor(13,72,115);pdf.rect(margin,43,W-2*margin,15,"F");pdf.text("Indicador",margin+3,52);columns.forEach((c,i)=>pdf.text(pdf.splitTextToSize(c.name,colW-3).slice(0,2),start+i*colW+2,49));
 indicators.forEach((indicator,index)=>{const y=58+index*10;pdf.setFillColor(index%2?245:233,index%2?248:242,index%2?252:248);pdf.rect(margin,y,W-2*margin,10,"F");pdf.setTextColor(17,35,58);pdf.setFont("helvetica","bold");pdf.setFontSize(8);pdf.text(indicator.name,margin+2,y+6);pdf.setFont("helvetica","normal");pdf.setFontSize(7);columns.forEach((c,i)=>pdf.text(pdf.splitTextToSize(indicator.value(c.row,i),colW-4).slice(0,2),start+i*colW+2,y+4))});
 pdf.setTextColor(35,51,70);pdf.setFontSize(8);pdf.text("Fontes por franquia:",margin,174);comparison.competitors.forEach((r,i)=>pdf.text(pdf.splitTextToSize(`${r.brand_name||"Franquia"}: ${r.source_name||"Fonte nao informada"}${r.source_reference_date?` (${r.source_reference_date})`:""}`,W-2*margin).slice(0,1),margin,180+i*4));pdf.setFontSize(7);pdf.text("N/D = dado nao divulgado ou nao verificado. Break-even = custos fixos / margem de contribuicao; nao equivale ao payback.",margin,200);pdf.text("O capital de referencia nao altera o investimento divulgado. Valores LocAgora sao projecoes, nao garantias.",margin,205);pdf.save(`Comparativo_LocAgora_${clientName.replace(/[^a-zA-Z0-9_-]+/g,"_")}.pdf`);
}
