export type NetworkPoint={
  id:string;type:string;name:string;city:string;state:string;country:string;status:string;address:string;phone:string;phoneNote:string;lat:number;lng:number;future?:boolean;
};

export const NETWORK_POINTS:NetworkPoint[]=[
  {
    "id": "n1",
    "type": "international",
    "name": "Masters Locagora Portugal",
    "city": "Portugal",
    "state": "PT",
    "country": "Portugal",
    "status": "Em operação",
    "address": "Operações Master em Portugal",
    "phone": "",
    "phoneNote": "",
    "lat": 39.3999,
    "lng": -8.2245,
    "future": false
  },
  {
    "id": "n2",
    "type": "international",
    "name": "Futura Master Locagora Espanha",
    "city": "Espanha",
    "state": "ES",
    "country": "Espanha",
    "status": "Futura Master",
    "address": "Praça internacional em implantação",
    "phone": "",
    "phoneNote": "",
    "lat": 40.4637,
    "lng": -3.7492,
    "future": true
  },
  {
    "id": "n3",
    "type": "locadora",
    "name": "Locagora Canindé",
    "city": "São Paulo",
    "state": "SP",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Cruzeiro do Sul, 130 - Canindé, São Paulo - SP, 03033-020",
    "phone": "0800 000 1372",
    "phoneNote": "Central Locagora",
    "lat": -23.5505,
    "lng": -46.6333,
    "future": false
  },
  {
    "id": "n4",
    "type": "locadora",
    "name": "Locagora Sorocaba",
    "city": "Sorocaba",
    "state": "SP",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Rua Antonio de Andrade, 276 - Jardim Faculdade, Sorocaba - SP, 18030-300",
    "phone": "0800 000 1372",
    "phoneNote": "Central Locagora",
    "lat": -23.5015,
    "lng": -47.4526,
    "future": false
  },
  {
    "id": "n5",
    "type": "locadora",
    "name": "Locagora Barreiro",
    "city": "Belo Horizonte",
    "state": "MG",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Sinfrônio Brochado, 840 - Barreiro, Belo Horizonte - MG, 30640-000",
    "phone": "0800 000 1372",
    "phoneNote": "Central Locagora",
    "lat": -19.9167,
    "lng": -43.9345,
    "future": false
  },
  {
    "id": "n6",
    "type": "locadora",
    "name": "Locagora Aracaju",
    "city": "Aracaju",
    "state": "SE",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Coelho e Campos, 521 - Centro, Aracaju - SE, 49010-720",
    "phone": "0800 000 1372",
    "phoneNote": "Central Locagora",
    "lat": -10.9472,
    "lng": -37.0731,
    "future": false
  },
  {
    "id": "n7",
    "type": "locadora",
    "name": "Locagora Belém do Pará",
    "city": "Belém",
    "state": "PA",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Passagem José de Alencar, 26 - Castanheira, Belém - PA, 66645-020",
    "phone": "0800 000 1372",
    "phoneNote": "Central Locagora",
    "lat": -1.4558,
    "lng": -48.4902,
    "future": false
  },
  {
    "id": "n8",
    "type": "locadora",
    "name": "Locagora São João de Meriti",
    "city": "São João de Meriti",
    "state": "RJ",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Automóvel Clube, 43 - Vilar dos Teles, São João de Meriti - RJ",
    "phone": "0800 000 1372",
    "phoneNote": "Central Locagora",
    "lat": -22.8058,
    "lng": -43.3729,
    "future": false
  },
  {
    "id": "n9",
    "type": "locadora",
    "name": "Locagora Campo Grande",
    "city": "Campo Grande",
    "state": "MS",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Calógera, 514 - Jardim Alvorada, Campo Grande - MS",
    "phone": "0800 000 1372",
    "phoneNote": "Central Locagora",
    "lat": -20.4697,
    "lng": -54.6201,
    "future": false
  },
  {
    "id": "n10",
    "type": "locadora",
    "name": "Locagora Uberlândia",
    "city": "Uberlândia",
    "state": "MG",
    "country": "Brasil",
    "status": "Em operação",
    "address": "R. Duque de Caxias, 1876 - Saraiva, Uberlândia - MG, 38408-382",
    "phone": "0800 000 1372",
    "phoneNote": "Central Locagora",
    "lat": -18.9146,
    "lng": -48.2754,
    "future": false
  },
  {
    "id": "n11",
    "type": "locadora",
    "name": "Locagora Campinas",
    "city": "Campinas",
    "state": "SP",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Avenida Brasil, 807 - Guanabara, Campinas - SP, 13073-012",
    "phone": "(19) 99823-2764",
    "phoneNote": "Contato público da unidade",
    "lat": -22.9056,
    "lng": -47.0608,
    "future": false
  },
  {
    "id": "n12",
    "type": "locadora",
    "name": "Locagora Feira de Santana",
    "city": "Feira de Santana",
    "state": "BA",
    "country": "Brasil",
    "status": "Em operação",
    "address": "R. Castro Alves, 443 - Serraria Brasil, Feira de Santana - BA, 44001-648",
    "phone": "(71) 98178-9918",
    "phoneNote": "Contato público da unidade",
    "lat": -12.2664,
    "lng": -38.9663,
    "future": false
  },
  {
    "id": "n13",
    "type": "locadora",
    "name": "Locagora Manaus",
    "city": "Manaus",
    "state": "AM",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Mulateiro, 1069 - Santa Etelvina, Manaus - AM",
    "phone": "(92) 8482-7320",
    "phoneNote": "Contato público da unidade",
    "lat": -3.119,
    "lng": -60.0217,
    "future": false
  },
  {
    "id": "n14",
    "type": "locadora",
    "name": "Locagora Cuiabá",
    "city": "Cuiabá",
    "state": "MT",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Miguel Sutil, 11.990 - Cidade Alta, Cuiabá - MT, 78015-100",
    "phone": "(65) 99946-8486",
    "phoneNote": "Contato público da unidade",
    "lat": -15.6014,
    "lng": -56.0979,
    "future": false
  },
  {
    "id": "n15",
    "type": "locadora",
    "name": "Locagora Florianópolis",
    "city": "Florianópolis",
    "state": "SC",
    "country": "Brasil",
    "status": "Em operação",
    "address": "R. Waldemar Ouríques, 549 - Capoeiras, Florianópolis - SC, 88090-050",
    "phone": "(48) 3036-4088",
    "phoneNote": "Contato público da unidade",
    "lat": -27.5949,
    "lng": -48.5482,
    "future": false
  },
  {
    "id": "n16",
    "type": "locadora",
    "name": "Locagora Curitiba",
    "city": "Curitiba",
    "state": "PR",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Anne Frank, 3687 - Hauer, Curitiba - PR, 81650-020",
    "phone": "(41) 98465-5167",
    "phoneNote": "Contato público da unidade",
    "lat": -25.4284,
    "lng": -49.2733,
    "future": false
  },
  {
    "id": "n17",
    "type": "locadora",
    "name": "Locagora Goiânia",
    "city": "Goiânia",
    "state": "GO",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. T-9, 2294 - Q. 528, Lt. 02 - Jardim América, Goiânia - GO, 74255-220",
    "phone": "(62) 98466-0017",
    "phoneNote": "Contato público da unidade",
    "lat": -16.6869,
    "lng": -49.2648,
    "future": false
  },
  {
    "id": "n18",
    "type": "locadora",
    "name": "Locagora João Pessoa",
    "city": "João Pessoa",
    "state": "PB",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Vasco da Gama, 379 - Jaguaribe, João Pessoa - PB",
    "phone": "(83) 9621-1799",
    "phoneNote": "Contato público da unidade",
    "lat": -7.1195,
    "lng": -34.845,
    "future": false
  },
  {
    "id": "n19",
    "type": "locadora",
    "name": "Locagora Maceió",
    "city": "Maceió",
    "state": "AL",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Rua Manoel Luiz Santana, 110A - Tabuleiro do Martins, Maceió - AL, 57061-110",
    "phone": "(82) 99314-8726",
    "phoneNote": "Contato público da unidade",
    "lat": -9.6498,
    "lng": -35.7089,
    "future": false
  },
  {
    "id": "n20",
    "type": "locadora",
    "name": "Locagora Porto Alegre",
    "city": "Porto Alegre",
    "state": "RS",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Pres. Franklin Roosevelt, 1579 - São Geraldo, Porto Alegre - RS, 90230-002",
    "phone": "(51) 99671-2228",
    "phoneNote": "Contato público da unidade",
    "lat": -30.0346,
    "lng": -51.2177,
    "future": false
  },
  {
    "id": "n21",
    "type": "locadora",
    "name": "Locagora Bragança Paulista",
    "city": "Bragança Paulista",
    "state": "SP",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Antonio Pires Pimentel, 865 - Centro, Bragança Paulista - SP, 12914-001",
    "phone": "(11) 91321-0710",
    "phoneNote": "Contato público da unidade",
    "lat": -22.9527,
    "lng": -46.5419,
    "future": false
  },
  {
    "id": "n22",
    "type": "locadora",
    "name": "Locagora Joinville",
    "city": "Joinville",
    "state": "SC",
    "country": "Brasil",
    "status": "Em operação",
    "address": "R. Esteves Júnior, 19 - Guanabara, Joinville - SC, 89207-590",
    "phone": "(47) 9180-4370",
    "phoneNote": "Contato público da unidade",
    "lat": -26.3044,
    "lng": -48.8487,
    "future": false
  },
  {
    "id": "n23",
    "type": "locadora",
    "name": "Locagora Recife",
    "city": "Recife",
    "state": "PE",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Recife, 4030 - Areias, Recife - PE, 50865-030",
    "phone": "(81) 99104-6373",
    "phoneNote": "Contato público da unidade",
    "lat": -8.0476,
    "lng": -34.877,
    "future": false
  },
  {
    "id": "n24",
    "type": "locadora",
    "name": "Locagora Ribeirão Preto",
    "city": "Ribeirão Preto",
    "state": "SP",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Independência, 239 - Vila Seixas, Ribeirão Preto - SP, 14020-010",
    "phone": "(16) 99759-8800",
    "phoneNote": "Contato público da unidade",
    "lat": -21.1704,
    "lng": -47.8103,
    "future": false
  },
  {
    "id": "n25",
    "type": "locadora",
    "name": "Locagora Barueri",
    "city": "Barueri",
    "state": "SP",
    "country": "Brasil",
    "status": "Em operação",
    "address": "R. Lapa, 243 - Chácaras Marco, Barueri - SP, 06419-020",
    "phone": "(11) 97590-2865",
    "phoneNote": "Contato público da unidade",
    "lat": -23.5114,
    "lng": -46.8765,
    "future": false
  },
  {
    "id": "n26",
    "type": "locadora",
    "name": "Locagora Belo Horizonte - Floramar",
    "city": "Belo Horizonte",
    "state": "MG",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Rua Desembargador Arthur Albino, 454 - Floramar, Belo Horizonte - MG, 30110-001",
    "phone": "(31) 99328-8008",
    "phoneNote": "Contato público da unidade",
    "lat": -19.9167,
    "lng": -43.9345,
    "future": false
  },
  {
    "id": "n27",
    "type": "locadora",
    "name": "Locagora Fortaleza",
    "city": "Fortaleza",
    "state": "CE",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Eduardo Girão, 901 - Fátima, Fortaleza - CE, 60415-540",
    "phone": "(85) 8182-5354",
    "phoneNote": "Contato público da unidade",
    "lat": -3.7319,
    "lng": -38.5267,
    "future": false
  },
  {
    "id": "n28",
    "type": "locadora",
    "name": "Locagora Tatuapé",
    "city": "São Paulo",
    "state": "SP",
    "country": "Brasil",
    "status": "Em operação",
    "address": "R. Nova Jerusalém, 807 - Chácara Santo Antônio, São Paulo - SP, 03410-000",
    "phone": "(11) 99492-7643",
    "phoneNote": "Contato público da unidade",
    "lat": -23.5505,
    "lng": -46.6333,
    "future": false
  },
  {
    "id": "n29",
    "type": "locadora",
    "name": "Locagora Limão",
    "city": "São Paulo",
    "state": "SP",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Prof. Celestino Bourroul, 581 - Limão, São Paulo - SP, 02710-000",
    "phone": "0800 000 1372",
    "phoneNote": "Central Locagora",
    "lat": -23.5505,
    "lng": -46.6333,
    "future": false
  },
  {
    "id": "n30",
    "type": "locadora",
    "name": "Locagora Brasília",
    "city": "Brasília",
    "state": "DF",
    "country": "Brasil",
    "status": "Em operação",
    "address": "SCIA Quadra 15 Conjunto 4, Lote 10 - Zona Industrial, Brasília - DF, 71250-020",
    "phone": "(61) 3978-1500",
    "phoneNote": "Contato público da unidade",
    "lat": -15.7939,
    "lng": -47.8828,
    "future": false
  },
  {
    "id": "n31",
    "type": "locadora",
    "name": "Locagora Salvador",
    "city": "Salvador",
    "state": "BA",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Mestre Manoel, 149 - Boca do Rio, Salvador - BA, 41705-715",
    "phone": "(71) 98406-4538",
    "phoneNote": "Contato público da unidade",
    "lat": -12.9777,
    "lng": -38.5016,
    "future": false
  },
  {
    "id": "n32",
    "type": "locadora",
    "name": "Locagora Freguesia do Ó",
    "city": "São Paulo",
    "state": "SP",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Rua Ribeiro de Morais, 211 - Vila Albertina, São Paulo - SP, 02731-030",
    "phone": "0800 000 1372",
    "phoneNote": "Central Locagora",
    "lat": -23.5505,
    "lng": -46.6333,
    "future": false
  },
  {
    "id": "n33",
    "type": "locadora",
    "name": "Locagora Rio de Janeiro",
    "city": "Rio de Janeiro",
    "state": "RJ",
    "country": "Brasil",
    "status": "Em operação",
    "address": "R. Luís Sérgio Person, 127 - Rio de Janeiro - RJ, 22775-043",
    "phone": "(21) 99556-4631",
    "phoneNote": "Contato público da unidade",
    "lat": -22.9068,
    "lng": -43.1729,
    "future": false
  },
  {
    "id": "n34",
    "type": "locadora",
    "name": "Locagora Teresina",
    "city": "Teresina",
    "state": "PI",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Avenida Miguel Rosa, 7500 - Tabuleta, Teresina - PI",
    "phone": "(86) 99189-191",
    "phoneNote": "Contato público da unidade",
    "lat": -5.0892,
    "lng": -42.8016,
    "future": false
  },
  {
    "id": "n35",
    "type": "locadora",
    "name": "Locagora São Luís",
    "city": "São Luís",
    "state": "MA",
    "country": "Brasil",
    "status": "Em operação",
    "address": "R. São Domingos, 05 - São Luís - MA, 65067-460",
    "phone": "(98) 98800-0111",
    "phoneNote": "Contato público da unidade",
    "lat": -2.5307,
    "lng": -44.3068,
    "future": false
  },
  {
    "id": "n36",
    "type": "seminovos",
    "name": "Locagora Seminovos Canindé",
    "city": "São Paulo",
    "state": "SP",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Cruzeiro do Sul, 130 - Canindé, São Paulo - SP, 03033-020",
    "phone": "(11) 1524-3404",
    "phoneNote": "Cadastro público",
    "lat": -23.5505,
    "lng": -46.6333,
    "future": false
  },
  {
    "id": "n37",
    "type": "seminovos",
    "name": "Locagora Seminovos Tatuapé",
    "city": "São Paulo",
    "state": "SP",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Rua Nova Jerusalém, 807 - Chácara Santo Antônio, São Paulo - SP, 03410-000",
    "phone": "(11) 1524-3404",
    "phoneNote": "Cadastro público",
    "lat": -23.5505,
    "lng": -46.6333,
    "future": false
  },
  {
    "id": "n38",
    "type": "seminovos",
    "name": "Locagora Seminovos Limão",
    "city": "São Paulo",
    "state": "SP",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Av. Prof. Celestino Bourroul, 602, Sala 2 - Limão, São Paulo - SP, 02710-000",
    "phone": "(11) 1524-3404",
    "phoneNote": "Cadastro público",
    "lat": -23.5505,
    "lng": -46.6333,
    "future": false
  },
  {
    "id": "n39",
    "type": "seminovos",
    "name": "Locagora Seminovos Amazonas",
    "city": "Belo Horizonte",
    "state": "MG",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Avenida Amazonas, 3441 - Barroca, Belo Horizonte - MG, 30431-061",
    "phone": "(11) 1524-3404",
    "phoneNote": "Cadastro público",
    "lat": -19.9167,
    "lng": -43.9345,
    "future": false
  },
  {
    "id": "n40",
    "type": "escritorio",
    "name": "Locagora - Sede / Escritório Belo Horizonte",
    "city": "Belo Horizonte",
    "state": "MG",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Rua Marechal Deodoro, 293, 2º andar - Floresta, Belo Horizonte - MG, 30150-110",
    "phone": "(31) 99109-9716",
    "phoneNote": "Cadastro público da matriz",
    "lat": -19.9167,
    "lng": -43.9345,
    "future": false
  },
  {
    "id": "n41",
    "type": "escritorio",
    "name": "Locagora São Paulo II - Escritório / Gestão",
    "city": "São Paulo",
    "state": "SP",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Rua Tte. Gomes Ribeiro, 208, Box 1 - Vila Clementino, São Paulo - SP, 04038-040",
    "phone": "(17) 3234-5037",
    "phoneNote": "Cadastro público",
    "lat": -23.5505,
    "lng": -46.6333,
    "future": false
  },
  {
    "id": "n42",
    "type": "galpao",
    "name": "Galpão Locagora Sorocaba",
    "city": "Sorocaba",
    "state": "SP",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Rua Antonio de Andrade, 276, Galpão 1 Box - Jardim Faculdade, Sorocaba - SP, 18030-300",
    "phone": "0800 000 1372",
    "phoneNote": "Endereço cadastral público; contato central",
    "lat": -23.5015,
    "lng": -47.4526,
    "future": false
  },
  {
    "id": "n43",
    "type": "galpao",
    "name": "Galpão Locagora Salvador",
    "city": "Salvador",
    "state": "BA",
    "country": "Brasil",
    "status": "Em operação",
    "address": "Avenida Mestre Manoel, 149 - Boca do Rio, Salvador - BA, 41705-715",
    "phone": "(71) 98406-4538",
    "phoneNote": "Endereço público com referência a Galpão Locagora",
    "lat": -12.9777,
    "lng": -38.5016,
    "future": false
  },
  {
    "id": "n44",
    "type": "master",
    "name": "Master Brasília",
    "city": "Brasília",
    "state": "DF",
    "country": "Brasil",
    "status": "Em operação / referência pública",
    "address": "SCIA Quadra 15 Conjunto 4, Lote 10 - Zona Industrial, Brasília - DF, 71250-020",
    "phone": "(61) 3978-1500",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -15.7939,
    "lng": -47.8828,
    "future": false
  },
  {
    "id": "n45",
    "type": "master",
    "name": "Master São José dos Campos",
    "city": "São José dos Campos",
    "state": "SP",
    "country": "Brasil",
    "status": "Inaugurada",
    "address": "Endereço público específico não localizado nesta consulta",
    "phone": "—",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -23.2237,
    "lng": -45.9009,
    "future": false
  },
  {
    "id": "n46",
    "type": "master",
    "name": "Master Vitória da Conquista",
    "city": "Vitória da Conquista",
    "state": "BA",
    "country": "Brasil",
    "status": "Em processo de inauguração",
    "address": "Endereço público específico não localizado nesta consulta",
    "phone": "—",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -14.8619,
    "lng": -40.8442,
    "future": false
  },
  {
    "id": "n47",
    "type": "master",
    "name": "Master Betim",
    "city": "Betim",
    "state": "MG",
    "country": "Brasil",
    "status": "Em processo de inauguração",
    "address": "Endereço público específico não localizado nesta consulta",
    "phone": "—",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -19.9678,
    "lng": -44.1983,
    "future": false
  },
  {
    "id": "n48",
    "type": "master",
    "name": "Master BH Centro Sul",
    "city": "Belo Horizonte",
    "state": "MG",
    "country": "Brasil",
    "status": "Em processo de inauguração",
    "address": "Endereço público específico não localizado nesta consulta",
    "phone": "—",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -19.9167,
    "lng": -43.9345,
    "future": false
  },
  {
    "id": "n49",
    "type": "master",
    "name": "Master Guarulhos",
    "city": "Guarulhos",
    "state": "SP",
    "country": "Brasil",
    "status": "Em processo de inauguração",
    "address": "Endereço público específico não localizado nesta consulta",
    "phone": "—",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -23.4543,
    "lng": -46.5337,
    "future": false
  },
  {
    "id": "n50",
    "type": "master",
    "name": "Master Bragança Paulista",
    "city": "Bragança Paulista",
    "state": "SP",
    "country": "Brasil",
    "status": "Praça cadastrada",
    "address": "Av. Antonio Pires Pimentel, 865 - Centro, Bragança Paulista - SP, 12914-001",
    "phone": "(11) 91321-0710",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -22.9527,
    "lng": -46.5419,
    "future": false
  },
  {
    "id": "n51",
    "type": "master",
    "name": "Master Campo Grande",
    "city": "Campo Grande",
    "state": "MS",
    "country": "Brasil",
    "status": "Praça cadastrada",
    "address": "Av. Calógera, 514 - Jardim Alvorada, Campo Grande - MS",
    "phone": "0800 000 1372",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -20.4697,
    "lng": -54.6201,
    "future": false
  },
  {
    "id": "n52",
    "type": "master",
    "name": "Master Joinville",
    "city": "Joinville",
    "state": "SC",
    "country": "Brasil",
    "status": "Praça cadastrada",
    "address": "R. Esteves Júnior, 19 - Guanabara, Joinville - SC, 89207-590",
    "phone": "(47) 9180-4370",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -26.3044,
    "lng": -48.8487,
    "future": false
  },
  {
    "id": "n53",
    "type": "master",
    "name": "Master São Luís",
    "city": "São Luís",
    "state": "MA",
    "country": "Brasil",
    "status": "Praça cadastrada",
    "address": "R. São Domingos, 05 - São Luís - MA, 65067-460",
    "phone": "(98) 98800-0111",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -2.5307,
    "lng": -44.3068,
    "future": false
  },
  {
    "id": "n54",
    "type": "master",
    "name": "Master Porto Alegre",
    "city": "Porto Alegre",
    "state": "RS",
    "country": "Brasil",
    "status": "Praça cadastrada",
    "address": "Av. Pres. Franklin Roosevelt, 1579 - São Geraldo, Porto Alegre - RS, 90230-002",
    "phone": "(51) 99671-2228",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -30.0346,
    "lng": -51.2177,
    "future": false
  },
  {
    "id": "n55",
    "type": "master",
    "name": "Master Uberlândia",
    "city": "Uberlândia",
    "state": "MG",
    "country": "Brasil",
    "status": "Praça cadastrada",
    "address": "R. Duque de Caxias, 1876 - Saraiva, Uberlândia - MG, 38408-382",
    "phone": "0800 000 1372",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -18.9146,
    "lng": -48.2754,
    "future": false
  },
  {
    "id": "n56",
    "type": "master",
    "name": "Master Cuiabá",
    "city": "Cuiabá",
    "state": "MT",
    "country": "Brasil",
    "status": "Praça cadastrada",
    "address": "Av. Miguel Sutil, 11.990 - Cidade Alta, Cuiabá - MT, 78015-100",
    "phone": "(65) 99946-8486",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -15.6014,
    "lng": -56.0979,
    "future": false
  },
  {
    "id": "n57",
    "type": "master",
    "name": "Master Maceió",
    "city": "Maceió",
    "state": "AL",
    "country": "Brasil",
    "status": "Praça cadastrada",
    "address": "Rua Manoel Luiz Santana, 110A - Tabuleiro do Martins, Maceió - AL, 57061-110",
    "phone": "(82) 99314-8726",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -9.6498,
    "lng": -35.7089,
    "future": false
  },
  {
    "id": "n58",
    "type": "master",
    "name": "Master Manaus",
    "city": "Manaus",
    "state": "AM",
    "country": "Brasil",
    "status": "Praça cadastrada",
    "address": "Av. Mulateiro, 1069 - Santa Etelvina, Manaus - AM",
    "phone": "(92) 8482-7320",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -3.119,
    "lng": -60.0217,
    "future": false
  },
  {
    "id": "n59",
    "type": "master",
    "name": "Master Itajaí",
    "city": "Itajaí",
    "state": "SC",
    "country": "Brasil",
    "status": "Filial vinculada a Joinville",
    "address": "Endereço público específico não localizado nesta consulta",
    "phone": "—",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -26.9101,
    "lng": -48.6705,
    "future": false
  },
  {
    "id": "n60",
    "type": "master",
    "name": "Master Caxias do Sul",
    "city": "Caxias do Sul",
    "state": "RS",
    "country": "Brasil",
    "status": "Filial vinculada a Porto Alegre",
    "address": "Endereço público específico não localizado nesta consulta",
    "phone": "—",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -29.1634,
    "lng": -51.1797,
    "future": false
  },
  {
    "id": "n61",
    "type": "master",
    "name": "Master Balneário Camboriú",
    "city": "Balneário Camboriú",
    "state": "SC",
    "country": "Brasil",
    "status": "Filial vinculada à operação regional",
    "address": "Endereço público específico não localizado nesta consulta",
    "phone": "—",
    "phoneNote": "Base territorial / endereço público quando localizado",
    "lat": -26.9926,
    "lng": -48.6352,
    "future": false
  }
];
