-- Locagora Central V14 — Fase 1: autorização e premissas imutáveis/versionadas
create table if not exists public.commercial_memberships (
  auth_user_id uuid primary key references auth.users(id) on delete cascade,
  app_user_id uuid null,
  role text not null check(role in ('admin','gestor','closer','visualizacao')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);
alter table public.commercial_memberships enable row level security;

create or replace function public.has_commercial_role(required_roles text[])
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.commercial_memberships m where m.auth_user_id=auth.uid() and m.active and m.role=any(required_roles));
$$;
grant execute on function public.has_commercial_role(text[]) to authenticated;

create policy "membership self read" on public.commercial_memberships for select to authenticated using (auth_user_id=auth.uid() or public.has_commercial_role(array['admin','gestor']));
create policy "admin manages memberships" on public.commercial_memberships for all to authenticated using (public.has_commercial_role(array['admin'])) with check (public.has_commercial_role(array['admin']));

insert into public.commercial_memberships(auth_user_id,role)
select user_id,'admin' from public.commercial_admins
on conflict(auth_user_id) do nothing;

create table if not exists public.commercial_premise_versions (
  id uuid primary key default gen_random_uuid(),
  version integer generated by default as identity,
  status text not null default 'draft' check(status in ('draft','review','published','archived')),
  config jsonb not null,
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  published_by uuid references auth.users(id),
  published_at timestamptz,
  archived_at timestamptz
);
create unique index if not exists commercial_premise_versions_version_uq on public.commercial_premise_versions(version);
create unique index if not exists commercial_premise_one_published_uq on public.commercial_premise_versions((status)) where status='published';
alter table public.commercial_premise_versions enable row level security;
create policy "published premises public read" on public.commercial_premise_versions for select to anon,authenticated using (status='published' or public.has_commercial_role(array['admin','gestor','closer','visualizacao']));
create policy "admin gestor create premises" on public.commercial_premise_versions for insert to authenticated with check (public.has_commercial_role(array['admin','gestor']) and status in ('draft','review'));
create policy "admin gestor update nonpublished premises" on public.commercial_premise_versions for update to authenticated using (public.has_commercial_role(array['admin','gestor']) and status<>'published') with check (public.has_commercial_role(array['admin','gestor']));

create or replace function public.publish_commercial_premise_version(p_id uuid)
returns public.commercial_premise_versions language plpgsql security definer set search_path=public as $$
declare v public.commercial_premise_versions;
begin
  if not public.has_commercial_role(array['admin','gestor']) then raise exception 'forbidden'; end if;
  update public.commercial_premise_versions set status='archived',archived_at=now() where status='published' and id<>p_id;
  update public.commercial_premise_versions set status='published',published_at=now(),published_by=auth.uid() where id=p_id and status in ('draft','review') returning * into v;
  if v.id is null then raise exception 'premise_version_not_publishable'; end if;
  return v;
end;$$;
grant execute on function public.publish_commercial_premise_version(uuid) to authenticated;

insert into public.commercial_premise_versions(status,config,notes)
select 'published',value,'Importação automática da configuração V13' from public.commercial_settings where key='pricing' and published=true
and not exists(select 1 from public.commercial_premise_versions)
limit 1;

alter table if exists public.commercial_simulations add column if not exists premise_version_id uuid references public.commercial_premise_versions(id);
alter table if exists public.commercial_simulations add column if not exists premise_version integer;
alter table if exists public.commercial_simulations add column if not exists premise_snapshot jsonb;
alter table if exists public.commercial_proposals add column if not exists premise_version_id uuid references public.commercial_premise_versions(id);
alter table if exists public.commercial_proposals add column if not exists premise_version integer;
alter table if exists public.commercial_proposals add column if not exists premise_snapshot jsonb;
