import { NextRequest } from "next/server";
type Locale={hl:string;gl:string;ceid:string};type QueryDef={q:string;category:string;country:string;city?:string};type Group={locale:Locale;queries:QueryDef[]};
const BR={hl:"pt-BR",gl:"BR",ceid:"BR:pt-419"},PT={hl:"pt-PT",gl:"PT",ceid:"PT:pt-150"},ES={hl:"es",gl:"ES",ceid:"ES:es"};
const GROUPS:Record<string,Group>={
 todas:{locale:BR,queries:[{q:'"Locagora" motos',category:"Locagora",country:"Brasil"},{q:'locação motos Brasil',category:"Locação de motos",country:"Brasil"},{q:'locação carros Brasil',category:"Locação de carros",country:"Brasil"},{q:'investimentos Brasil mercado financeiro',category:"Investimentos",country:"Brasil"},{q:'finanças juros crédito Brasil',category:"Finanças",country:"Brasil"},{q:'Portugal imigração trabalho brasileiros',category:"Imigração",country:"Portugal"},{q:'Lisboa turismo investimento mobilidade',category:"Turismo",country:"Portugal",city:"Lisboa"},{q:'Porto turismo mobilidade investimento',category:"Turismo",country:"Portugal",city:"Porto"},{q:'España inmigración trabajo extranjeros',category:"Imigração",country:"Espanha"},{q:'Barcelona turismo movilidad motos alquiler',category:"Turismo",country:"Espanha",city:"Barcelona"},{q:'Madrid turismo movilidad inversión',category:"Turismo",country:"Espanha",city:"Madrid"}]},
 locagora:{locale:BR,queries:[{q:'"Locagora" motos',category:"Locagora",country:"Brasil"},{q:'"Locagora" franquia',category:"Locagora",country:"Brasil"},{q:'"Locagora" investimento',category:"Locagora",country:"Brasil"},{q:'"Locagora" aluguel de motos',category:"Locagora",country:"Brasil"},{q:'"Locagora" motoboy',category:"Locagora",country:"Brasil"}]},
 motos:{locale:BR,queries:[{q:'locação motos Brasil',category:"Locação de motos",country:"Brasil"},{q:'aluguel motos delivery Brasil',category:"Locação de motos",country:"Brasil"},{q:'motos assinatura mobilidade Brasil',category:"Mobilidade",country:"Brasil"},{q:'Mottu aluguel motos',category:"Concorrentes",country:"Brasil"},{q:'franquia aluguel motos Brasil',category:"Franquias",country:"Brasil"}]},
 carros:{locale:BR,queries:[{q:'locação carros Brasil Localiza Movida',category:"Locação de carros",country:"Brasil"},{q:'assinatura carro Brasil mobilidade',category:"Mobilidade",country:"Brasil"},{q:'gestão frotas locadoras Brasil',category:"Frotas",country:"Brasil"}]},
 investimentos:{locale:BR,queries:[{q:'investimentos Brasil mercado financeiro renda fixa bolsa',category:"Investimentos",country:"Brasil"},{q:'juros Selic inflação investimentos Brasil',category:"Finanças",country:"Brasil"},{q:'fundos imobiliários dividendos Brasil',category:"Investimentos",country:"Brasil"},{q:'franquias Brasil investimento empreendedorismo',category:"Franquias",country:"Brasil"}]},
 portugal:{locale:PT,queries:[{q:'Portugal imigração autorização residência trabalho estrangeiros',category:"Imigração",country:"Portugal"},{q:'Lisboa turismo visitantes investimento',category:"Turismo",country:"Portugal",city:"Lisboa"},{q:'Porto turismo visitantes investimento',category:"Turismo",country:"Portugal",city:"Porto"},{q:'Portugal investimento empreendedorismo franquias',category:"Investimentos",country:"Portugal"},{q:'Portugal mobilidade motos scooters aluguer',category:"Locação de motos",country:"Portugal"},{q:'Portugal rent a car aluguer automóveis',category:"Locação de carros",country:"Portugal"}]},
 espanha:{locale:ES,queries:[{q:'España inmigración residencia trabajo extranjeros',category:"Imigração",country:"Espanha"},{q:'Barcelona turismo visitantes inversión',category:"Turismo",country:"Espanha",city:"Barcelona"},{q:'Madrid turismo visitantes inversión',category:"Turismo",country:"Espanha",city:"Madrid"},{q:'España inversión emprendimiento franquicias',category:"Investimentos",country:"Espanha"},{q:'España movilidad motos scooter alquiler',category:"Locação de motos",country:"Espanha"},{q:'España alquiler coches movilidad',category:"Locação de carros",country:"Espanha"}]}
};
function decode(s:string){return s.replace(/<!\[CDATA\[(.*?)\]\]>/gs,"$1").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">");}
function tag(xml:string,name:string){const m=xml.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,"i"));return m?decode(m[1].trim()):"";}
function attr(xml:string,name:string,attrName:string){const m=xml.match(new RegExp(`<${name}[^>]*${attrName}=["']([^"']+)["'][^>]*>`,"i"));return m?decode(m[1]):"";}
function cleanTitle(title:string){return title.replace(/\s+-\s+[^-]{2,80}$/," ").trim();}
const SOURCE_DOMAINS:Record<string,string>={
 "Folha de S.Paulo":"folha.uol.com.br","Folha de S.Paulo - UOL":"folha.uol.com.br","g1":"g1.globo.com","G1":"g1.globo.com","O Globo":"oglobo.globo.com","Valor Econômico":"valor.globo.com","Estadão":"estadao.com.br","Estado de Minas":"em.com.br","Gazeta da Semana":"gazetadasemana.com.br","A Gazeta":"agazeta.com.br","Observador":"observador.pt","PÚBLICO":"publico.pt","Jornal de Notícias":"jn.pt","Diário de Notícias":"dn.pt","Sincopesp-SP":"sincopesp.org.br","GZH":"gauchazh.clicrbs.com.br","CNN Brasil":"cnnbrasil.com.br","Exame":"exame.com","InfoMoney":"infomoney.com.br","InvestNews":"investnews.com.br","UOL":"uol.com.br","VEJA":"veja.abril.com.br","YouTube • LocAgora":"youtube.com"
};
function sourceDomain(source:string){const exact=SOURCE_DOMAINS[source];if(exact)return exact;const key=Object.keys(SOURCE_DOMAINS).find(k=>source.toLowerCase().includes(k.toLowerCase()));return key?SOURCE_DOMAINS[key]:"";}

async function googleNews(def:QueryDef,locale:Locale,days:number){const q=`${def.q} when:${days}d`;const url=`https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=${encodeURIComponent(locale.hl)}&gl=${encodeURIComponent(locale.gl)}&ceid=${encodeURIComponent(locale.ceid)}`;const r=await fetch(url,{next:{revalidate:900},headers:{"User-Agent":"LocagoraCentral/12.9.2"}});if(!r.ok)return[];const xml=await r.text();const chunks=xml.match(/<item>[\s\S]*?<\/item>/g)||[];return chunks.slice(0,12).map(x=>{const source=tag(x,"source")||"Google News";return{title:cleanTitle(tag(x,"title")),link:tag(x,"link"),publishedAt:tag(x,"pubDate"),source,sourceDomain:sourceDomain(source),category:def.category,country:def.country,city:def.city||"",kind:"news" as const,imageUrl:attr(x,"media:content","url")||attr(x,"enclosure","url")||""}}).filter(x=>x.title&&x.link);}
async function youtubeLocagora(){const channelId="UCcQbi10ML7sGnI600-eB8bw";const url=`https://www.youtube.com/feeds/videos.xml?channel_id=${channelId}`;const r=await fetch(url,{next:{revalidate:900},headers:{"User-Agent":"LocagoraCentral/12.9.2"}});if(!r.ok)return[];const xml=await r.text();const chunks=xml.match(/<entry>[\s\S]*?<\/entry>/g)||[];return chunks.slice(0,10).map(x=>{const title=tag(x,"title"),videoId=tag(x,"yt:videoId"),published=tag(x,"published");return{title,link:videoId?`https://www.youtube.com/watch?v=${videoId}`:"",publishedAt:published,source:"YouTube • LocAgora",sourceDomain:"youtube.com",category:"Locagora",country:"Brasil",city:"",kind:"youtube" as const,imageUrl:videoId?`https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`:""};}).filter(x=>x.title&&x.link);}
function dedupe(items:any[]){const seen=new Set<string>();return items.filter(x=>{const key=(x.title||"").toLowerCase().replace(/\W/g,"").slice(0,95);if(!key||seen.has(key))return false;seen.add(key);return true;});}
async function ogImage(url:string){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),2800);try{const r=await fetch(url,{redirect:"follow",signal:controller.signal,next:{revalidate:3600},headers:{"User-Agent":"Mozilla/5.0 LocagoraCentral/12.9.2"}});if(!r.ok)return"";const html=(await r.text()).slice(0,350000);const m=html.match(/<meta[^>]+(?:property|name)=["'](?:og:image|twitter:image)["'][^>]+content=["']([^"']+)["']/i)||html.match(/<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["'](?:og:image|twitter:image)["']/i);return m?.[1]||"";}catch{return"";}finally{clearTimeout(timer)}}
async function enrichTop(items:any[]){const top=items.slice(0,12);await Promise.all(top.map(async x=>{if(!x.imageUrl)x.imageUrl=await ogImage(x.link)}));return items;}
export async function GET(req:NextRequest){const category=req.nextUrl.searchParams.get("category")||"todas";const days=Math.min(60,Math.max(1,Number(req.nextUrl.searchParams.get("days")||30)));const group=GROUPS[category]||GROUPS.todas;try{const batches=await Promise.all(group.queries.map(q=>googleNews(q,group.locale,days)));let items=dedupe(batches.flat());if(category==="locagora"||category==="todas"){const youtube=await youtubeLocagora();items=dedupe([...youtube,...items]);}items.sort((a,b)=>new Date(b.publishedAt||0).getTime()-new Date(a.publishedAt||0).getTime());items=await enrichTop(items);return Response.json({updatedAt:new Date().toISOString(),category,items:items.slice(0,60),sourceCount:new Set(items.map(x=>x.source).filter(Boolean)).size},{headers:{"Cache-Control":"public, s-maxage=900, stale-while-revalidate=1800"}});}catch{return Response.json({updatedAt:new Date().toISOString(),category,items:[],error:"feed_unavailable"},{status:200});}}
