-- Consolidação de dados verificáveis do comparador.
-- Fonte prioritária: Portal do Franchising / ABF (dados informados pelas próprias redes).
-- Campos sem publicação verificável permanecem NULL; não estimar.

update public.commercial_franchise_benchmarks set initial_investment_min=100000, initial_investment_max=340000, source_name='Portal do Franchising / ABF', source_url='https://franquias.portaldofranchising.com.br/franquia-ate-100-mil/', updated_at=now() where brand_name='Colchões Ortobom';
update public.commercial_franchise_benchmarks set initial_investment_min=80000, initial_investment_max=340000, source_name='Portal do Franchising / ABF — CVC Brasil', source_url='https://franquias.portaldofranchising.com.br/franquia-cvc-turismo/', source_reference_date='2026-08-31', updated_at=now() where brand_name='CVC Brasil';
update public.commercial_franchise_benchmarks set initial_investment_min=245000, initial_investment_max=975000, source_name='Portal do Franchising / ABF', source_url='https://franquias.portaldofranchising.com.br/franquia-de-emporios-mercados-e-lojas-de-conveniencia/', updated_at=now() where brand_name='AM/PM';
update public.commercial_franchise_benchmarks set initial_investment_min=235000, initial_investment_max=400000, source_name='Portal do Franchising / ABF — Shell Select', source_url='https://franquias.portaldofranchising.com.br/franquia-shell-select/', updated_at=now() where brand_name='Shell Select';
update public.commercial_franchise_benchmarks set initial_investment_min=168000, initial_investment_max=280000, payback_months_min=18, payback_months_max=36, source_name='Portal do Franchising / ABF — Chilli Beans', source_url='https://franquias.portaldofranchising.com.br/franquia-chilli-beans-acessorios-pessoais/', source_reference_date='2026-09-03', updated_at=now() where brand_name='Chilli Beans';
update public.commercial_franchise_benchmarks set initial_investment_min=2200000, initial_investment_max=5000000, payback_months_min=60, payback_months_max=84, source_name='Portal do Franchising / ABF — Burger King Brasil', source_url='https://franquias.portaldofranchising.com.br/franquia-burger-king-valor/', source_reference_date='2025-12-26', updated_at=now() where brand_name='Burger King Brasil';
update public.commercial_franchise_benchmarks set initial_investment_min=358000, initial_investment_max=641000, payback_months_min=18, payback_months_max=18, average_profit_margin_pct=22.5, source_name='Portal do Franchising / ABF — OdontoCompany', source_url='https://franquias.portaldofranchising.com.br/franquia-odontocompany-odontologica/', source_reference_date='2026-08-04', updated_at=now() where brand_name='Odontocompany';

-- O Boticário permanece sem valor numérico: a listagem atual da ABF informa “Sob Consulta”.
update public.commercial_franchise_benchmarks set initial_investment_min=null, initial_investment_max=null, source_name='Portal do Franchising / ABF — investimento sob consulta', source_url='https://franquias.portaldofranchising.com.br/franquia-loja/', updated_at=now() where brand_name='O Boticário';
